package com.projecthero.mod.client.gui;

import com.projecthero.mod.ProjectHeroMod;
import com.projecthero.mod.ironman.IronManEnergy;
import com.projecthero.mod.ironman.fabricator.IronManSuitPlatformBlockEntity;
import com.projecthero.mod.ironman.fabricator.IronManSuitPlatformMenu;
import com.projecthero.mod.ironman.item.IronManArmorItem;
import com.projecthero.mod.ironman.suit.IronManSuit;
import com.projecthero.mod.ironman.suit.IronManSuits;
import com.projecthero.mod.ironman.ui.IronManUiLayout;

import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.Util;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.item.ItemStack;

/**
 * Iron Man Suit Platform screen (v0.14.21 redesign) on a textured panel ({@code textures/gui/iron_man_suit_platform.png},
 * generated by {@code scratchpad/gen_v01421_ironman_gui.js}). Slot positions are unchanged from
 * {@link IronManSuitPlatformMenu}:
 * <pre>
 *   y 5        title
 *   x 7..48    y 18..113   rotating 3D preview of the stored suit (holo well)
 *   y 19       stored mark name (or "No suit stored")
 *   y 32       the four armour slots (empty ones show the vanilla armour silhouettes)
 *   x 136..170 y 29..51    REGEN plate (v0.14.27: the flat platform charge rate; the reserve is gone)
 *   y 57 / 65  CHARGE  label + %, Slab bar with the exact energy inside
 *   y 78 / 86  INTEGRITY label + %, Slab bar with the exact integrity inside
 *   y 97..115  v0.15.4: the Stark Gantry hint (the Deploy / Retrieve buttons are gone)
 *   y 124 / 182 player inventory / hotbar
 * </pre>
 */
public class IronManSuitPlatformScreen extends AbstractContainerScreen<IronManSuitPlatformMenu> {
	private static final ResourceLocation BG = ProjectHeroMod.id("textures/gui/iron_man_suit_platform.png");
	/** The vanilla empty-armour-slot silhouettes (block-atlas sprites, as the player inventory uses). */
	private static final ResourceLocation[] EMPTY_SLOT = {
			net.minecraft.world.inventory.InventoryMenu.EMPTY_ARMOR_SLOT_HELMET,
			net.minecraft.world.inventory.InventoryMenu.EMPTY_ARMOR_SLOT_CHESTPLATE,
			net.minecraft.world.inventory.InventoryMenu.EMPTY_ARMOR_SLOT_LEGGINGS,
			net.minecraft.world.inventory.InventoryMenu.EMPTY_ARMOR_SLOT_BOOTS };
	private static final int MX = IronManUiLayout.PLAT_METER_X;
	private static final int MW = IronManUiLayout.PLAT_METER_W;
	private final long openedAt = Util.getMillis();
	/** v0.15.4: the side tab that hands out the Colantotte Bracelets -- only shown while a Mark 7 is stored. */
	private IronManGui.StarkButton bracelets;
	/** v0.15.6: the side tab that packs a racked Mark 5 into its suitcase -- only shown while a Mark 5 is stored. */
	private IronManGui.StarkButton suitcase;

	public IronManSuitPlatformScreen(IronManSuitPlatformMenu menu, Inventory inv, Component title) {
		super(menu, inv, title);
		this.imageWidth = 176;
		this.imageHeight = 202;
		this.titleLabelX = 8;
		this.titleLabelY = 5;
	}

	// v0.15.4: no DEPLOY / RETRIEVE buttons any more -- the strip they used says where suiting up happens now (renderLabels)
	@Override
	protected void init() {
		super.init();
		// v0.15.4: a small tab off the right edge of the panel (the panel itself has no free row)
		bracelets = new IronManGui.StarkButton(leftPos + imageWidth + 2, topPos + 98, BRACELETS_W, 15,
				Component.translatable("screen.projecthero.suit_platform.bracelets"),
				() -> click(IronManSuitPlatformMenu.BRACELETS_BUTTON));
		bracelets.accent = IronManGui.RED;
		bracelets.visible = menu.offersBracelets();
		addRenderableWidget(bracelets);
		// v0.15.6: the same tab spot packs a racked Mark 5 back into its suitcase (a platform holds one suit at a time)
		suitcase = new IronManGui.StarkButton(leftPos + imageWidth + 2, topPos + 98, BRACELETS_W, 15,
				Component.translatable("screen.projecthero.suit_platform.suitcase"),
				() -> click(IronManSuitPlatformMenu.SUITCASE_BUTTON));
		suitcase.visible = menu.offersSuitcase();
		addRenderableWidget(suitcase);
	}

	/** v0.15.4: width of the Bracelets tab. */
	public static final int BRACELETS_W = 60;

	private void click(int id) {
		if (minecraft != null && minecraft.gameMode != null) {
			minecraft.gameMode.handleInventoryButtonClick(menu.containerId, id);
		}
	}

	private ItemStack[] pieces() {
		ItemStack[] out = new ItemStack[4];
		for (int i = 0; i < 4; i++) {
			out[i] = menu.slots.get(i).getItem();
		}
		return out;
	}

	private String storedSuitId() {
		for (ItemStack s : pieces()) {
			if (s.getItem() instanceof IronManArmorItem a) {
				return a.suitId();
			}
		}
		return null;
	}

	@Override
	protected void renderBg(GuiGraphics g, float partialTick, int mouseX, int mouseY) {
		int x = leftPos;
		int y = topPos;
		g.blit(BG, x, y, 0, 0, imageWidth, imageHeight, 256, 256);
		for (int i = 0; i < 4; i++) {
			if (menu.slots.get(i).getItem().isEmpty()) {
				var sprite = minecraft.getTextureAtlas(net.minecraft.world.inventory.InventoryMenu.BLOCK_ATLAS).apply(EMPTY_SLOT[i]);
				g.blit(x + 53 + i * 20, y + 32, 0, 16, 16, sprite);
			}
		}
		// rotating preview of whatever is stored
		float secs = (Util.getMillis() - openedAt) / 1000f;
		IronManGui.suitPreview(g, x + 8, y + 19, x + 47, y + 112, pieces(), 180f + secs * 40f);
	}

	@Override
	protected void renderLabels(GuiGraphics g, int mouseX, int mouseY) {
		g.drawString(font, IronManGui.fit(font, title, imageWidth - 16), titleLabelX, titleLabelY, IronManGui.CYAN, false);

		String suitId = storedSuitId();
		IronManSuit suit = suitId == null ? null : IronManSuits.byId(suitId);
		Component head = menu.hasStoredSuit() && suit != null
				? Component.translatable(suit.nameKey())
				: Component.translatable("screen.projecthero.suit_platform.empty");
		g.drawString(font, IronManGui.fit(font, head, 80), MX + 1, 19, suit != null ? IronManGui.TEXT : IronManGui.TEXT_MUTED, false);

		// v0.14.27: the reserve is gone -- the plate shows the flat regen rate instead
		g.drawString(font, IronManGui.fit(font, Component.translatable("screen.projecthero.suit_platform.regen_short"), 30),
				139, 31, IronManGui.TEXT_DIM, false);
		// v0.15.20: the energy rate is the stored suit's own passive rate (a dash when empty)
		String rv = IronManGui.fit(font, suit == null ? "-" : "+" + rate(IronManEnergy.platformEnergyPerSecond(suit)) + "/s", 30);
		g.drawString(font, rv, 139, 41, IronManGui.CYAN, false);

		if (menu.hasStoredSuit()) {
			float cap = Math.max(1f, menu.suitCapacityExact());
			float energy = Math.max(0f, Math.min(cap, menu.suitEnergyExact()));
			float integPct = Math.max(0f, Math.min(100f, menu.suitIntegrityPercentExact()));
			float maxI = suitId == null ? IronManEnergy.MAX_INTEGRITY : IronManEnergy.maxIntegrity(suitId);
			meter(g, 57, Component.translatable("screen.projecthero.suit_call.charge").getString(), energy / cap,
					IronManUiLayout.exact(energy, cap), energy / cap < 0.15f ? IronManGui.ORANGE : IronManGui.BLUE);
			meter(g, 78, Component.translatable("screen.projecthero.suit_call.integrity").getString(), integPct / 100f,
					IronManUiLayout.exact(integPct / 100f * maxI, maxI), integPct < 30f ? IronManGui.RED : IronManGui.GREEN);
		}
		// v0.15.4: the Stark Gantry hint, word-wrapped into the old button strip (y 97..115)
		int gy = 97;
		for (var line : font.split(Component.translatable("screen.projecthero.suit_platform.gantry_hint"), MW)) {
			g.drawString(font, line, MX + 1, gy, IronManGui.CYAN_DIM, false);
			gy += 9;
			if (gy > 106) {
				break;
			}
		}
		if (!menu.hasStoredSuit()) {
			String hint = Component.translatable("screen.projecthero.suit_platform.empty_hint").getString();
			int ty = 60;
			for (var line : font.split(Component.literal(hint), MW)) {
				g.drawString(font, line, MX + 1, ty, IronManGui.TEXT_MUTED, false);
				ty += 10;
				if (ty > 90) {
					break;
				}
			}
		}
	}

	private IronManSuit platformSuit() {
		String id = storedSuitId();
		return id == null ? null : IronManSuits.byId(id);
	}

	/** "5", or "0.5" for a fractional rate. */
	private static String rate(float perSecond) {
		return perSecond == Math.round(perSecond) ? Integer.toString(Math.round(perSecond))
				: String.format(java.util.Locale.ROOT, "%.1f", perSecond);
	}

	private void meter(GuiGraphics g, int y, String label, float frac, String exact, int fill) {
		g.drawString(font, label, MX, y, IronManGui.TEXT_DIM, false);
		String p = IronManUiLayout.pct(frac);
		g.drawString(font, p, MX + MW - font.width(p), y, IronManGui.TEXT, false);
		IronManGui.slab(g, font, MX + 1, y + 9, MW - 2, frac, fill, exact);
	}

	@Override
	public void render(GuiGraphics g, int mouseX, int mouseY, float partialTick) {
		if (bracelets != null) {
			bracelets.visible = menu.offersBracelets(); // v0.15.4: only while a Mark 7 is stored
		}
		if (suitcase != null) {
			suitcase.visible = menu.offersSuitcase(); // v0.15.6: only while a Mark 5 is stored
		}
		super.render(g, mouseX, mouseY, partialTick);
		this.renderTooltip(g, mouseX, mouseY);
		if (bracelets != null && bracelets.visible && bracelets.isHovered()) {
			g.renderTooltip(font, font.split(Component.translatable("screen.projecthero.suit_platform.bracelets_tip"), 160),
					mouseX, mouseY);
		}
		if (suitcase != null && suitcase.visible && suitcase.isHovered()) {
			g.renderTooltip(font, font.split(Component.translatable("screen.projecthero.suit_platform.suitcase_tip"), 160),
					mouseX, mouseY);
		}
		if (mouseX >= leftPos + 136 && mouseX < leftPos + 170 && mouseY >= topPos + 29 && mouseY < topPos + 51) {
			g.renderTooltip(font, Component.translatable("screen.projecthero.suit_platform.regen_tip",
					platformSuit() == null ? "-" : rate(IronManEnergy.platformEnergyPerSecond(platformSuit())),
					rate(IronManSuitPlatformBlockEntity.REGEN_INTEGRITY_PER_SECOND)), mouseX, mouseY);
		}
	}
}
