package com.projecthero.mod.client.gui;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import com.projecthero.mod.ProjectHeroMod;
import com.projecthero.mod.ironman.fabricator.FabricationRecipe;
import com.projecthero.mod.ironman.fabricator.FabricatorRecipes;
import com.projecthero.mod.ironman.fabricator.StarkFabricatorMenu;
import com.projecthero.mod.ironman.item.BlueprintItem;
import com.projecthero.mod.ironman.item.IronManItems;
import com.projecthero.mod.ironman.suit.IronManSuit;
import com.projecthero.mod.ironman.suit.IronManSuits;
import com.projecthero.mod.ironman.ui.IronManUiLayout;
import com.projecthero.mod.ironman.ui.IronManUiLayout.Rect;

import net.minecraft.ChatFormatting;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.FormattedCharSequence;
import net.minecraft.Util;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.item.ItemStack;

/**
 * The Stark Fabricator screen (v0.14.21 redesign) on a textured panel ({@code textures/gui/stark_fabricator.png},
 * generated by {@code scratchpad/gen_v01421_ironman_gui.js}). Slot geometry matches {@link StarkFabricatorMenu}.
 * <pre>
 *   y 5          title, energy % (right)
 *   y 17..71     blueprint slot (12,35) | 3x3 inputs (44,17) | progress arrow | output (120,35) | energy gauge
 *   y 75..79     progress bar (fill + travelling glow while fabricating)
 *   y 82         status (left) + exact energy (right)
 *   y 92..110    piece tabs Helmet / Chest / Legs / Boots (with a suit blueprint; 44 x 18 hit areas)
 *   y 112..152   checklist: piece needs + View more, then each input as icon + green check or red have/need
 *   y 156 / 214  inventory / hotbar (moved up from 164 / 224 with StarkFabricatorMenu: 248 px did not fit GUI scale 4)
 * </pre>
 * "changes 18" behaviour kept: picking a piece shows that piece's components as ghost stacks in the empty grid
 * cells, and View more opens a scrollable modal listing every component plus the finished suit's stats.
 */
public class StarkFabricatorScreen extends AbstractContainerScreen<StarkFabricatorMenu> {
	private static final ResourceLocation BG = ProjectHeroMod.id("textures/gui/stark_fabricator.png");
	private static final String[] PIECE_KEYS = { "helmet", "chestplate", "leggings", "boots" };
	private static final net.minecraft.world.item.ArmorItem.Type[] PIECE_TYPES = {
			net.minecraft.world.item.ArmorItem.Type.HELMET, net.minecraft.world.item.ArmorItem.Type.CHESTPLATE,
			net.minecraft.world.item.ArmorItem.Type.LEGGINGS, net.minecraft.world.item.ArmorItem.Type.BOOTS };

	// geometry (panel-relative) -- shared with the gametests through IronManUiLayout
	static final int TAB_Y = IronManUiLayout.FAB_TAB_Y;
	static final int TAB_W = IronManUiLayout.FAB_TAB_W;
	static final int TAB_H = IronManUiLayout.FAB_TAB_H;
	static final int BOX_X = IronManUiLayout.FAB_BOX_X;
	static final int BOX_Y = IronManUiLayout.FAB_BOX_Y;
	static final int BOX_W = IronManUiLayout.FAB_BOX_W;
	static final int BOX_H = IronManUiLayout.FAB_BOX_H;
	static final int MORE_W = IronManUiLayout.FAB_MORE_W;
	static final int CHECK_PER_ROW = IronManUiLayout.FAB_CHECK_PER_ROW;
	static final int CHECK_CELL_W = IronManUiLayout.FAB_CHECK_CELL_W;
	static final int CHECK_ROW_H = IronManUiLayout.FAB_CHECK_ROW_H;

	private boolean showInfo;
	private int infoScroll;
	private int infoScrollMax;

	public StarkFabricatorScreen(StarkFabricatorMenu menu, Inventory inv, Component title) {
		super(menu, inv, title);
		this.imageWidth = 200;
		this.imageHeight = IronManUiLayout.FAB_H;
		this.titleLabelX = 8;
		this.titleLabelY = 5;
	}

	private boolean hasSuitBlueprint() {
		return menu.blueprintStack().getItem() instanceof BlueprintItem bp && bp.suitId() != null
				&& FabricatorRecipes.hasArmorRecipes(bp.suitId());
	}

	private String blueprintSuitId() {
		return menu.blueprintStack().getItem() instanceof BlueprintItem bp ? bp.suitId() : null;
	}

	private FabricationRecipe selectedRecipe() {
		String suitId = blueprintSuitId();
		int piece = menu.selectedPiece();
		if (suitId == null || piece < 1 || piece > 4) {
			return null;
		}
		var type = FabricatorRecipes.pieceType(piece);
		return type == null ? null : FabricatorRecipes.byId("iron_man_" + suitId + "_" + type.getName());
	}

	private List<ItemStack> inputStacks() {
		List<ItemStack> out = new ArrayList<>(9);
		for (int i = 0; i < 9; i++) {
			out.add(menu.slots.get(i).getItem());
		}
		return out;
	}

	private int tabX(int i) {
		return IronManUiLayout.fabTab(i).x();
	}

	private static boolean inRect(double mx, double my, int rx, int ry, int rw, int rh) {
		return mx >= rx && mx < rx + rw && my >= ry && my < ry + rh;
	}

	// ------------------------------------------------------------------ background

	@Override
	protected void renderBg(GuiGraphics g, float partialTick, int mouseX, int mouseY) {
		int x = leftPos;
		int y = topPos;
		g.blit(BG, x, y, 0, 0, imageWidth, imageHeight, 256, 256);

		// energy gauge: vertical fill with a lit top edge
		int gx = x + 177;
		int gTop = y + 17;
		int gBot = y + 71;
		int maxE = Math.max(1, menu.maxEnergy());
		float ef = IronManUiLayout.clamp01(menu.energy() / (float) maxE);
		int lvl = Math.round((gBot - gTop) * ef);
		g.fillGradient(gx, gBot - lvl, gx + 10, gBot, 0xFF6FC8FF, 0xFF2A6FC0);
		if (lvl > 0) {
			g.fill(gx, gBot - lvl, gx + 10, gBot - lvl + 1, 0xFFDDF6FF);
		}

		// progress: arrow + full-width bar with a travelling glow
		if (menu.maxProgress() > 0) {
			float pf = IronManUiLayout.clamp01(menu.progress() / (float) menu.maxProgress());
			g.fill(x + 103, y + 40, x + 103 + Math.round(10 * pf), y + 44, IronManGui.CYAN);
			int bx = x + 12;
			int bw = 176;
			int by = y + IronManUiLayout.FAB_PROGRESS_Y;
			int pw = Math.round(bw * pf);
			g.fill(bx, by, bx + pw, by + 4, 0xFF3FB07A);
			g.fill(bx, by, bx + pw, by + 1, 0xFF9CF0C4);
			long ms = Util.getMillis();
			int glowX = (int) ((ms / 6) % (bw + 40)) - 20;
			for (int k = -10; k <= 10; k++) {
				int gxk = bx + glowX + k;
				if (gxk >= bx && gxk < bx + pw) {
					int a = Math.round(150 * (1f - Math.abs(k) / 11f));
					g.fill(gxk, by, gxk + 1, by + 4, (a << 24) | 0xFFFFFF);
				}
			}
		}

		// empty blueprint slot: a faded blank-blueprint ghost
		if (menu.blueprintStack().isEmpty()) {
			g.renderFakeItem(new ItemStack(IronManItems.BLANK_BLUEPRINT), x + 12, y + 35);
			g.fill(x + 12, y + 35, x + 28, y + 51, 0xC0101319);
		}
		renderGhostInputs(g, x, y);
		if (hasSuitBlueprint()) {
			renderTabs(g, x, y, mouseX, mouseY);
		}
	}

	private void renderGhostInputs(GuiGraphics g, int x, int y) {
		FabricationRecipe recipe = selectedRecipe();
		if (recipe == null) {
			return;
		}
		List<FabricationRecipe.Input> inputs = recipe.inputs();
		for (int i = 0; i < inputs.size() && i < 9; i++) {
			FabricationRecipe.Input in = inputs.get(i);
			ItemStack present = menu.slots.get(i).getItem();
			if (present.is(in.item()) && present.getCount() >= in.count()) {
				continue;
			}
			int cx = x + 44 + (i % 3) * 18;
			int cy = y + 17 + (i / 3) * 18;
			g.renderFakeItem(new ItemStack(in.item()), cx, cy);
			g.fill(cx, cy, cx + 16, cy + 16, 0xB0141820);
			String n = String.valueOf(in.count());
			g.pose().pushPose();
			g.pose().translate(0, 0, 250);
			g.drawString(this.font, n, cx + 17 - this.font.width(n), cy + 9, 0xFF9AA6D0, true);
			g.pose().popPose();
		}
	}

	private void renderTabs(GuiGraphics g, int x, int y, int mouseX, int mouseY) {
		int sel = menu.selectedPiece();
		IronManSuit suit = IronManSuits.byId(blueprintSuitId());
		for (int i = 0; i < 4; i++) {
			int bx = x + tabX(i);
			int by = y + TAB_Y;
			boolean selected = sel == i + 1;
			boolean hover = inRect(mouseX, mouseY, bx, by, TAB_W, TAB_H);
			int bg = selected ? 0xF0183044 : hover ? 0xF0142230 : 0xE00C121A;
			g.fill(bx, by, bx + TAB_W, by + TAB_H, bg);
			g.renderOutline(bx, by, TAB_W, TAB_H, selected ? IronManGui.GOLD : hover ? IronManGui.CYAN : IronManGui.PANEL_BORDER);
			if (selected) {
				g.fill(bx + 1, by + TAB_H - 2, bx + TAB_W - 1, by + TAB_H - 1, IronManGui.GOLD);
			}
			ItemStack icon = suit != null && suit.armor(PIECE_TYPES[i]) != null ? new ItemStack(suit.armor(PIECE_TYPES[i])) : ItemStack.EMPTY;
			// icon-only tab: "Helmet" does not fit beside a 16 px icon in 44 px -- the piece name is in the
			// tooltip and in the checklist header below
			if (!icon.isEmpty()) {
				g.renderFakeItem(icon, bx + (TAB_W - 16) / 2, by + 1);
			}
		}
	}

	// ------------------------------------------------------------------ labels (screen-relative)

	@Override
	protected void renderLabels(GuiGraphics g, int mouseX, int mouseY) {
		int maxE = Math.max(1, menu.maxEnergy());
		String ePct = String.format(Locale.ROOT, "%.1f%%", 100.0 * menu.energy() / maxE).replace('.', ',');
		g.drawString(font, ePct, imageWidth - 8 - font.width(ePct), titleLabelY, IronManGui.CYAN, false);
		g.drawString(font, IronManGui.fit(font, title, imageWidth - 24 - font.width(ePct)), titleLabelX, titleLabelY,
				IronManGui.CYAN, false);

		// status (left) + exact energy (right)
		String energy = menu.energy() + " / " + menu.maxEnergy();
		g.drawString(font, energy, imageWidth - 10 - font.width(energy), IronManUiLayout.FAB_STATUS_Y, IronManGui.TEXT_MUTED, false);
		String status;
		int statusColor;
		FabricationRecipe recipe = selectedRecipe();
		if (menu.maxProgress() > 0) {
			int pct = Math.round(100f * menu.progress() / menu.maxProgress());
			status = Component.translatable("screen.projecthero.stark_fabricator.fabricating", pct).getString();
			statusColor = IronManGui.GREEN;
		} else if (recipe != null && !missingAny(recipe)) {
			status = Component.translatable(menu.energy() < recipe.energyCost()
					? "screen.projecthero.stark_fabricator.status.low_energy"
					: "screen.projecthero.stark_fabricator.status.ready").getString();
			statusColor = menu.energy() < recipe.energyCost() ? IronManGui.ORANGE : IronManGui.CYAN;
		} else if (recipe != null) {
			status = Component.translatable("screen.projecthero.stark_fabricator.status.missing").getString();
			statusColor = IronManGui.TEXT_DIM;
		} else {
			status = Component.translatable("screen.projecthero.stark_fabricator.status.idle").getString();
			statusColor = IronManGui.TEXT_DIM;
		}
		g.drawString(font, IronManGui.fit(font, status, imageWidth - 26 - font.width(energy)), 10, IronManUiLayout.FAB_STATUS_Y, statusColor, false);

		renderChecklist(g, recipe, mouseX - leftPos, mouseY - topPos);
	}

	private boolean missingAny(FabricationRecipe recipe) {
		List<ItemStack> grid = inputStacks();
		for (FabricationRecipe.Input in : recipe.inputs()) {
			if (IronManUiLayout.have(grid, in.item()) < in.count()) {
				return true;
			}
		}
		return false;
	}

	private void renderChecklist(GuiGraphics g, FabricationRecipe recipe, int mx, int my) {
		int tx = BOX_X + 4;
		int tw = BOX_W - 8;
		if (!hasSuitBlueprint()) {
			int y = BOX_Y + 3;
			for (FormattedCharSequence line : font.split(Component.translatable("screen.projecthero.stark_fabricator.idle_hint"), tw)) {
				if (y > BOX_Y + BOX_H - 9) {
					break;
				}
				g.drawString(font, line, tx, y, IronManGui.TEXT_DIM, false);
				y += 10;
			}
			return;
		}
		// "View more" (top-right of the box)
		int moreX = BOX_X + BOX_W - MORE_W - 3;
		int moreY = BOX_Y + 2;
		boolean moreHover = inRect(mx, my, moreX, moreY, MORE_W, 11);
		g.fill(moreX, moreY, moreX + MORE_W, moreY + 11, moreHover ? 0xF0183044 : 0xE00C121A);
		g.renderOutline(moreX, moreY, MORE_W, 11, moreHover ? IronManGui.CYAN : IronManGui.PANEL_BORDER);
		String more = IronManGui.fit(font, Component.translatable("screen.projecthero.stark_fabricator.view_more"), MORE_W - 4);
		g.drawString(font, more, moreX + (MORE_W - font.width(more)) / 2, moreY + 2, moreHover ? 0xFFFFFFFF : IronManGui.TEXT, false);

		if (recipe == null) {
			int y = BOX_Y + 3;
			for (FormattedCharSequence line : font.split(Component.translatable("screen.projecthero.stark_fabricator.pick_piece"),
					tw - MORE_W - 6)) {
				if (y > BOX_Y + BOX_H - 9) {
					break;
				}
				g.drawString(font, line, tx, y, IronManGui.TEXT_DIM, false);
				y += 10;
			}
			return;
		}
		Component header = Component.translatable("screen.projecthero.stark_fabricator.needs_short",
				Component.translatable("screen.projecthero.stark_fabricator.piece." + PIECE_KEYS[menu.selectedPiece() - 1]));
		g.drawString(font, IronManGui.fit(font, header, tw - MORE_W - 6), tx, BOX_Y + 3, IronManGui.GOLD, false);

		List<ItemStack> grid = inputStacks();
		List<FabricationRecipe.Input> inputs = recipe.inputs();
		ItemStack hoverStack = ItemStack.EMPTY;
		String hoverCount = null;
		for (int i = 0; i < inputs.size() && i < 12; i++) {
			FabricationRecipe.Input in = inputs.get(i);
			Rect c = IronManUiLayout.checklistCell(i, tx, IronManUiLayout.FAB_CHECK_TOP, CHECK_PER_ROW, CHECK_CELL_W, CHECK_ROW_H);
			int have = IronManUiLayout.have(grid, in.item());
			boolean ok = have >= in.count();
			ItemStack stack = new ItemStack(in.item());
			g.pose().pushPose();
			g.pose().translate(c.x(), c.y(), 0);
			g.pose().scale(0.5f, 0.5f, 1f);
			g.renderFakeItem(stack, 0, 0);
			g.pose().popPose();
			g.pose().pushPose();
			g.pose().translate(0, 0, 200);
			String t = ok ? "✓ " + in.count() : Math.min(have, 999) + "/" + in.count();
			g.drawString(font, IronManGui.fit(font, t, c.w() - 12), c.x() + 10, c.y(), ok ? IronManGui.GREEN : 0xFFFF6A6A, false);
			g.pose().popPose();
			if (c.contains(mx, my)) {
				hoverStack = stack;
				hoverCount = have + " / " + in.count();
			}
		}
		if (!hoverStack.isEmpty() && !showInfo) {
			pendingTip = List.of(hoverStack.getHoverName(),
					Component.translatable("screen.projecthero.stark_fabricator.have_need", hoverCount).withStyle(ChatFormatting.GRAY));
		}
	}

	private List<Component> pendingTip;

	// ------------------------------------------------------------------ render + modal

	@Override
	public void render(GuiGraphics g, int mouseX, int mouseY, float partialTick) {
		pendingTip = null;
		super.render(g, mouseX, mouseY, partialTick);
		if (showInfo && hasSuitBlueprint()) {
			renderInfoOverlay(g);
			return;
		}
		if (pendingTip != null) {
			g.renderComponentTooltip(font, pendingTip, mouseX, mouseY);
			return;
		}
		if (hasSuitBlueprint()) {
			for (int i = 0; i < 4; i++) {
				if (inRect(mouseX, mouseY, leftPos + tabX(i), topPos + TAB_Y, TAB_W, TAB_H)) {
					g.renderTooltip(font, Component.translatable("screen.projecthero.stark_fabricator.tab_tip",
							Component.translatable("screen.projecthero.stark_fabricator.piece." + PIECE_KEYS[i])), mouseX, mouseY);
					return;
				}
			}
		}
		if (inRect(mouseX, mouseY, leftPos + 176, topPos + 16, 12, 56)) {
			g.renderTooltip(font, Component.translatable("screen.projecthero.stark_fabricator.energy",
					menu.energy(), menu.maxEnergy()), mouseX, mouseY);
			return;
		}
		if (menu.blueprintStack().isEmpty() && inRect(mouseX, mouseY, leftPos + 12, topPos + 35, 16, 16)) {
			g.renderTooltip(font, Component.translatable("screen.projecthero.stark_fabricator.blueprint"), mouseX, mouseY);
			return;
		}
		if (menu.slots.get(10).getItem().isEmpty() && inRect(mouseX, mouseY, leftPos + 120, topPos + 35, 16, 16)) {
			g.renderTooltip(font, Component.translatable("screen.projecthero.stark_fabricator.output"), mouseX, mouseY);
			return;
		}
		this.renderTooltip(g, mouseX, mouseY);
	}

	/** The View-more modal: drawn above everything (item icons sit at ~232 z), opaque, scrollable. */
	private void renderInfoOverlay(GuiGraphics g) {
		var pose = g.pose();
		pose.pushPose();
		pose.translate(0, 0, 400);
		g.fill(0, 0, this.width, this.height, 0xCC05080C);

		int w = Math.min(224, this.width - 20);
		int h = Math.min(190, this.height - 20);
		int rx = (this.width - w) / 2;
		int ry = (this.height - h) / 2;
		int hdr = 16;
		IronManGui.panel(g, rx, ry, w, h, 0xFF0B1018, IronManGui.PANEL_BORDER, IronManGui.CYAN);
		g.fill(rx + 1, ry + 1, rx + w - 1, ry + hdr, 0xFF111A26);
		g.fill(rx + 1, ry + hdr, rx + w - 1, ry + hdr + 1, IronManGui.alpha(IronManGui.CYAN_DIM, 0.8f));

		IronManSuit suit = IronManSuits.byId(blueprintSuitId());
		Component name = suit != null ? Component.translatable(suit.nameKey()) : Component.literal("Blueprint");
		g.drawString(this.font, IronManGui.fit(font, name, w - 30), rx + 6, ry + 4, IronManGui.CYAN, false);
		g.drawString(this.font, "x", rx + w - 10, ry + 4, IronManGui.TEXT_DIM, false);

		int top = ry + hdr + 4;
		int bot = ry + h - 4;
		int visible = bot - top;
		List<Component> lines = new ArrayList<>();
		for (Component c : buildInfoLines(suit)) {
			for (FormattedCharSequence seq : font.split(c, w - 18)) {
				lines.add(toComponent(seq));
			}
		}
		int contentH = lines.size() * 10;
		infoScrollMax = Math.max(0, contentH - visible);
		infoScroll = Math.max(0, Math.min(infoScroll, infoScrollMax));

		g.enableScissor(rx, top, rx + w, bot);
		int y = top - infoScroll;
		for (Component c : lines) {
			if (y + 10 >= top && y <= bot) {
				g.drawString(this.font, c, rx + 7, y, IronManGui.TEXT, false);
			}
			y += 10;
		}
		g.disableScissor();

		if (infoScrollMax > 0) {
			int trackX = rx + w - 5;
			g.fill(trackX, top, trackX + 2, bot, 0xFF1A2230);
			int thumbH = Math.max(14, visible * visible / contentH);
			int thumbY = top + (visible - thumbH) * infoScroll / infoScrollMax;
			g.fill(trackX, thumbY, trackX + 2, thumbY + thumbH, IronManGui.CYAN_DIM);
		}
		pose.popPose();
	}

	private static Component toComponent(FormattedCharSequence seq) {
		net.minecraft.network.chat.MutableComponent out = Component.empty();
		seq.accept((idx, style, cp) -> {
			out.append(Component.literal(new String(Character.toChars(cp))).withStyle(style));
			return true;
		});
		return out;
	}

	private List<Component> buildInfoLines(IronManSuit suit) {
		List<Component> out = new ArrayList<>();
		FabricationRecipe recipe = selectedRecipe();
		if (recipe != null) {
			int piece = menu.selectedPiece();
			out.add(Component.translatable("screen.projecthero.stark_fabricator.needs_for",
					Component.translatable("screen.projecthero.stark_fabricator.piece." + PIECE_KEYS[piece - 1]))
					.withStyle(ChatFormatting.GOLD));
			List<ItemStack> grid = inputStacks();
			for (FabricationRecipe.Input in : recipe.inputs()) {
				int have = IronManUiLayout.have(grid, in.item());
				boolean ok = have >= in.count();
				out.add(Component.literal(ok ? " ✓ " : " ✗ ").withStyle(ok ? ChatFormatting.GREEN : ChatFormatting.RED)
						.append(Component.literal(in.count() + "x ").withStyle(ChatFormatting.GRAY))
						.append(new ItemStack(in.item()).getHoverName().copy().withStyle(ChatFormatting.WHITE))
						.append(Component.literal(ok ? "" : "  (" + have + ")").withStyle(ChatFormatting.DARK_GRAY)));
			}
			out.add(Component.translatable("screen.projecthero.stark_fabricator.cost", recipe.energyCost(),
					String.format(Locale.ROOT, "%.1f", recipe.timeTicks() / 20.0)).withStyle(ChatFormatting.DARK_GRAY));
			out.add(Component.empty());
		} else {
			out.add(Component.translatable("screen.projecthero.stark_fabricator.pick_piece").withStyle(ChatFormatting.GRAY));
			out.add(Component.empty());
		}
		if (suit != null) {
			out.add(Component.translatable("screen.projecthero.stark_fabricator.suit_stats").withStyle(ChatFormatting.GOLD));
			out.add(statLine("armour_integrity", String.valueOf(Math.round(suit.maxIntegrity()))));
			out.add(statLine("energy_capacity", String.valueOf(Math.round(suit.energyCapacity()))));
			out.add(statLine("energy_regen", fmt(suit.energyRegenPerSecond())));
			if (suit.armorRegenPerSecond() > 0f) {
				// v0.14.29: the real worn rate (listed rate x WORN_REGEN_SCALE), matching the suit info screen
				out.add(statLine("armour_regen", fmt(suit.armorRegenPerSecond()
						* com.projecthero.mod.ironman.IronManEnergy.WORN_REGEN_SCALE)));
			}
			out.add(statLine("melee_bonus", "+" + (int) suit.strengthBonus()));
			out.add(statLine("flight_drain", fmt(suit.flightDrainMultiplier())));
		}
		return out;
	}

	private static String fmt(float v) {
		return String.format(Locale.ROOT, "%.2f", v);
	}

	private Component statLine(String key, String value) {
		return Component.literal(" ")
				.append(Component.translatable("screen.projecthero.stark_fabricator.stat." + key))
				.append(": ").withStyle(ChatFormatting.GRAY)
				.append(Component.literal(value).withStyle(ChatFormatting.WHITE));
	}

	@Override
	public boolean mouseScrolled(double mx, double my, double dx, double dy) {
		if (showInfo && hasSuitBlueprint()) {
			infoScroll = Math.max(0, Math.min(infoScrollMax, infoScroll - (int) Math.round(dy * 12)));
			return true;
		}
		return super.mouseScrolled(mx, my, dx, dy);
	}

	@Override
	public boolean mouseClicked(double mx, double my, int button) {
		if (showInfo && hasSuitBlueprint()) {
			// modal: any click closes it (there is nothing to click inside)
			showInfo = false;
			infoScroll = 0;
			return true;
		}
		if (button == 0 && hasSuitBlueprint()) {
			for (int i = 0; i < 4; i++) {
				if (inRect(mx, my, leftPos + tabX(i), topPos + TAB_Y, TAB_W, TAB_H)) {
					if (this.minecraft != null && this.minecraft.gameMode != null) {
						this.minecraft.gameMode.handleInventoryButtonClick(menu.containerId, i + 1);
					}
					return true;
				}
			}
			int moreX = leftPos + BOX_X + BOX_W - MORE_W - 3;
			if (inRect(mx, my, moreX, topPos + BOX_Y + 2, MORE_W, 11)) {
				showInfo = true;
				infoScroll = 0;
				return true;
			}
		}
		return super.mouseClicked(mx, my, button);
	}

	@Override
	public boolean keyPressed(int key, int scan, int mods) {
		if (showInfo && key == org.lwjgl.glfw.GLFW.GLFW_KEY_ESCAPE) {
			showInfo = false;
			return true;
		}
		return super.keyPressed(key, scan, mods);
	}
}
