package com.projecthero.mod.client.oathbreaker;

import com.projecthero.mod.ProjectHeroMod;
import com.projecthero.mod.oathbreaker.entity.OathbreakerEntity;

import net.minecraft.resources.ResourceLocation;

import software.bernie.geckolib.model.GeoModel;

/**
 * The GeckoLib {@link GeoModel} for the Oathbreaker. One geometry and animation set; the texture follows
 * the synced {@link OathbreakerEntity.Phase} (v0.14.0): the base knight, then the soul-fire-cracked
 * "Forsworn" and "Oathless" variants. Each texture has a {@code _glowmask} twin next to it that
 * {@code AutoGlowingGeoLayer} picks up automatically (all generated by {@code build_oathbreaker_assets.js}).
 */
public class OathbreakerModel extends GeoModel<OathbreakerEntity> {
	private static final ResourceLocation MODEL = ProjectHeroMod.id("geo/oathbreaker.geo.json");
	private static final ResourceLocation TEXTURE = ProjectHeroMod.id("textures/entity/oathbreaker.png");
	private static final ResourceLocation TEXTURE_PHASE2 = ProjectHeroMod.id("textures/entity/oathbreaker_phase2.png");
	private static final ResourceLocation TEXTURE_PHASE3 = ProjectHeroMod.id("textures/entity/oathbreaker_phase3.png");
	private static final ResourceLocation ANIMATION = ProjectHeroMod.id("animations/oathbreaker.animation.json");

	@Override
	public ResourceLocation getModelResource(OathbreakerEntity animatable) {
		return MODEL;
	}

	@Override
	public ResourceLocation getTextureResource(OathbreakerEntity animatable) {
		return switch (animatable.getPhase()) {
			case KNIGHT -> TEXTURE;
			case FORSWORN -> TEXTURE_PHASE2;
			case OATHLESS -> TEXTURE_PHASE3;
		};
	}

	@Override
	public ResourceLocation getAnimationResource(OathbreakerEntity animatable) {
		return ANIMATION;
	}
}
