package com.projecthero.mod.client.grave;

import java.util.function.Supplier;

import com.projecthero.mod.ProjectHeroMod;
import com.projecthero.mod.grave.item.GraveItems;

import net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents;
import net.fabricmc.fabric.api.client.model.loading.v1.ModelLoadingPlugin;
import net.fabricmc.fabric.api.renderer.v1.Renderer;
import net.fabricmc.fabric.api.renderer.v1.RendererAccess;
import net.fabricmc.fabric.api.renderer.v1.material.RenderMaterial;
import net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel;
import net.fabricmc.fabric.api.renderer.v1.render.RenderContext;
import net.fabricmc.fabric.api.util.TriState;

import net.minecraft.client.CameraType;
import net.minecraft.client.Minecraft;
import net.minecraft.client.resources.model.BakedModel;
import net.minecraft.core.particles.ColorParticleOption;
import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import net.minecraft.util.RandomSource;
import net.minecraft.world.entity.HumanoidArm;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemDisplayContext;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.phys.Vec3;

/**
 * v0.14.21: client side of the Necrotic Blade's look (models / textures generated by
 * {@code scratchpad/gen_v01421_necrotic_blade.js}).
 * <ul>
 *   <li><b>Two models</b> -- {@code item/necrotic_blade} is the 3D skeleton sword used in the hands, on the ground and
 *       in item frames; {@code item/necrotic_blade_icon} is the flat 16x16 sprite, swapped in for
 *       {@link ItemDisplayContext#GUI} so the hotbar / inventory reads like any other sword.</li>
 *   <li><b>Glow</b> -- every 3D face with {@code tintindex 0} (fuller runes, skull eyes, soul gem) is drawn full-bright
 *       and unshaded through the Fabric Renderer API. No colour provider is registered, so the index means nothing
 *       else.</li>
 *   <li><b>Soul wisps</b> -- an occasional green swirl particle beside the hand of anyone holding it. Client-only,
 *       nothing is sent over the network.</li>
 * </ul>
 * With no FRAPI renderer the 3D model is left as it is: it still renders everywhere (the GUI then shows the 3D model
 * flat-on, which its identity gui transform lines up with the icon), just without the full-bright glow.
 */
public final class NecroticBladeClient {
	private static final ResourceLocation ITEM_ID = ProjectHeroMod.id("necrotic_blade");
	private static final ResourceLocation ICON_MODEL = ProjectHeroMod.id("item/necrotic_blade_icon");
	private static final int WISP_COLOUR = 0xFF5FE85A;

	private NecroticBladeClient() {
	}

	public static void initialize() {
		ModelLoadingPlugin.register(plugin -> {
			plugin.addModels(ICON_MODEL);
			plugin.modifyModelAfterBake().register((model, context) -> {
				if (model == null || model instanceof Blade || context.topLevelId() == null
						|| !ITEM_ID.equals(context.topLevelId().id())) {
					return model;
				}
				Renderer renderer = RendererAccess.INSTANCE.getRenderer();
				if (renderer == null) {
					return model;
				}
				RenderMaterial glow = renderer.materialFinder().emissive(true).disableDiffuse(true)
						.ambientOcclusion(TriState.FALSE).find();
				return new Blade(model, glow);
			});
		});
		ClientTickEvents.END_CLIENT_TICK.register(NecroticBladeClient::tickWisps);
	}

	/** A soul wisp now and then beside the hand of each nearby player holding the blade. */
	private static void tickWisps(Minecraft mc) {
		if (mc.level == null || mc.player == null || mc.isPaused()) {
			return;
		}
		RandomSource random = mc.level.random;
		for (Player player : mc.level.players()) {
			if (player.isInvisible() || player.distanceToSqr(mc.player) > 48 * 48) {
				continue;
			}
			// the camera entity in first person would get wisps in its face; it sees the glow on the blade instead
			if (player == mc.getCameraEntity() && mc.options.getCameraType() == CameraType.FIRST_PERSON) {
				continue;
			}
			boolean main = player.getMainHandItem().is(GraveItems.NECROTIC_BLADE);
			boolean off = player.getOffhandItem().is(GraveItems.NECROTIC_BLADE);
			if (!main && !off) {
				continue;
			}
			if (random.nextInt(6) != 0) {
				continue;
			}
			HumanoidArm arm = main ? player.getMainArm() : player.getMainArm().getOpposite();
			double side = arm == HumanoidArm.RIGHT ? 1.0 : -1.0;
			float yaw = player.yBodyRot * Mth.DEG_TO_RAD;
			Vec3 forward = new Vec3(-Mth.sin(yaw), 0, Mth.cos(yaw));
			Vec3 right = new Vec3(-Mth.cos(yaw), 0, -Mth.sin(yaw));
			double along = random.nextDouble() * 0.7; // somewhere up the blade, which points forward from the fist
			Vec3 pos = player.position()
					.add(right.scale(0.38 * side))
					.add(forward.scale(0.25 + along))
					.add(0, (player.isCrouching() ? 0.55 : 0.75) + along * 0.25, 0);
			mc.level.addParticle(ColorParticleOption.create(ParticleTypes.ENTITY_EFFECT, WISP_COLOUR),
					pos.x + (random.nextDouble() - 0.5) * 0.1, pos.y, pos.z + (random.nextDouble() - 0.5) * 0.1,
					0.0, 0.015, 0.0);
		}
	}

	/** The 3D blade with full-bright glow faces, and the flat icon in the GUI. */
	private static final class Blade extends ForwardingBakedModel {
		private final RenderMaterial glow;

		Blade(BakedModel wrapped, RenderMaterial glow) {
			this.wrapped = wrapped;
			this.glow = glow;
		}

		@Override
		public boolean isVanillaAdapter() {
			return false;
		}

		@Override
		public void emitItemQuads(ItemStack stack, Supplier<RandomSource> randomSupplier, RenderContext context) {
			if (context.itemTransformationMode() == ItemDisplayContext.GUI) {
				BakedModel icon = Minecraft.getInstance().getModelManager().getModel(ICON_MODEL);
				if (icon != null && icon != Minecraft.getInstance().getModelManager().getMissingModel()) {
					icon.emitItemQuads(stack, randomSupplier, context);
					return;
				}
			}
			context.pushTransform(quad -> {
				if (quad.colorIndex() == 0) {
					quad.material(glow);
					quad.colorIndex(-1);
				}
				return true;
			});
			super.emitItemQuads(stack, randomSupplier, context);
			context.popTransform();
		}
	}
}
