package com.projecthero.mod.client.syndicate;

import java.util.function.Supplier;

import com.projecthero.mod.ProjectHeroMod;

import net.fabricmc.fabric.api.client.model.loading.v1.ModelLoadingPlugin;
import net.fabricmc.fabric.api.renderer.v1.RendererAccess;
import net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel;
import net.fabricmc.fabric.api.renderer.v1.render.RenderContext;

import net.minecraft.client.Minecraft;
import net.minecraft.client.resources.model.BakedModel;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.RandomSource;
import net.minecraft.world.item.ItemDisplayContext;
import net.minecraft.world.item.ItemStack;

/**
 * v0.14.31: client side of the Kingpin's Cane's look (models / textures generated by
 * {@code scratchpad/gen_v01431_kingpin_cane.js}). {@code item/kingpin_cane} is the 3D cane -- black lacquered shaft,
 * silver collar and ferrule, a large faceted diamond head -- used in the hands (players' and the Kingpin's), on the
 * ground and in item frames; {@code item/kingpin_cane_icon} is the flat 16x16 sprite, swapped in for
 * {@link ItemDisplayContext#GUI} so the hotbar / inventory reads like any other weapon. The strikes are
 * {@link KingpinCanePose}. With no FRAPI renderer the 3D model is left as it is (the GUI then shows it flat-on).
 */
public final class KingpinCaneClient {
	private static final ResourceLocation ITEM_ID = ProjectHeroMod.id("kingpin_cane");
	private static final ResourceLocation ICON_MODEL = ProjectHeroMod.id("item/kingpin_cane_icon");

	private KingpinCaneClient() {
	}

	public static void initialize() {
		ModelLoadingPlugin.register(plugin -> {
			plugin.addModels(ICON_MODEL);
			plugin.modifyModelAfterBake().register((model, context) -> {
				if (model == null || model instanceof Cane || context.topLevelId() == null
						|| !ITEM_ID.equals(context.topLevelId().id()) || RendererAccess.INSTANCE.getRenderer() == null) {
					return model;
				}
				return new Cane(model);
			});
		});
		KingpinCanePose.init();
	}

	/** The 3D cane, with the flat icon in the GUI. */
	private static final class Cane extends ForwardingBakedModel {
		Cane(BakedModel wrapped) {
			this.wrapped = wrapped;
		}

		@Override
		public boolean isVanillaAdapter() {
			return false;
		}

		@Override
		public void emitItemQuads(ItemStack stack, Supplier<RandomSource> randomSupplier, RenderContext context) {
			if (context.itemTransformationMode() == ItemDisplayContext.GUI) {
				BakedModel icon = Minecraft.getInstance().getModelManager().getModel(ICON_MODEL);
				if (icon != null && icon != Minecraft.getInstance().getModelManager().getMissingModel()) {
					icon.emitItemQuads(stack, randomSupplier, context);
					return;
				}
			}
			super.emitItemQuads(stack, randomSupplier, context);
		}
	}
}
