package com.projecthero.mod.titan.entity;

import java.util.UUID;

import com.projecthero.mod.event.EventBossBar;
import com.projecthero.mod.event.entity.RaidUndead;
import com.projecthero.mod.titan.TitanConfig;
import com.projecthero.mod.titan.TitanTerrain;

import net.minecraft.core.BlockPos;
import net.minecraft.util.Mth;
import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.BossEvent;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.Pose;
import net.minecraft.world.entity.EntityDimensions;
import net.minecraft.world.entity.ai.attributes.AttributeSupplier;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.ai.navigation.GroundPathNavigation;
import net.minecraft.world.entity.ai.navigation.PathNavigation;
import net.minecraft.world.entity.monster.Zombie;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.storage.loot.LootParams;
import net.minecraft.world.level.storage.loot.parameters.LootContextParamSets;
import net.minecraft.world.level.storage.loot.parameters.LootContextParams;
import net.minecraft.world.phys.Vec3;

import software.bernie.geckolib.animatable.GeoEntity;
import software.bernie.geckolib.animatable.instance.AnimatableInstanceCache;
import software.bernie.geckolib.animation.AnimatableManager;
import software.bernie.geckolib.animation.AnimationController;
import software.bernie.geckolib.animation.AnimationState;
import software.bernie.geckolib.animation.PlayState;
import software.bernie.geckolib.animation.RawAnimation;
import software.bernie.geckolib.util.GeckoLibUtil;

/**
 * The true Titan -- an ~18-block giant zombie-style boss (spec: temporary placeholder model/texture,
 * kept easy to swap later; see {@code TitanRenderer}). Spawned only via
 * {@link DisguisedTitanEntity#completeTransformation}, never naturally.
 *
 * <h2>Attack state machine</h2>
 * Tick-driven, matching this codebase's established boss-AI convention (e.g.
 * {@code JuggernautZombie}'s own charge state machine, {@code BossPowerController}) rather than a
 * stack of vanilla {@code Goal}s: {@link #tickCombat} runs every tick, resolving an in-progress
 * attack's wind-up/active/recovery phases or, if idle and off the global cooldown, picking a new one
 * via {@link #chooseAttack}.
 *
 * <p>v0.14.4: every move plays a synced body animation ({@link Anim}), two new moves (Leaping Slam, Grave Roar),
 * and targeting is a threat table ({@link #tickThreat}) instead of "lock the first player forever". Full move
 * list: {@code docs/TITAN_BOSS_REFERENCE.md}.
 *
 * <p>v0.14.20: a GeckoLib model of its own (a hunched, rotting giant -- {@code geo/titan.geo.json}, every asset
 * generated by {@code scratchpad/gen_v01420_titan_model.js}) animated from the same synced {@link Anim}: see
 * {@link #registerControllers} and {@code TitanRenderer}. Death is now a 4.5 s collapse ({@link #DEATH_TICKS}).
 */
public class TitanEntity extends RaidUndead implements GeoEntity {
	/** Height 18 / vanilla zombie height 1.95 -- see {@code TitanConfig.Stats#heightBlocks}'s javadoc
	 *  for why this is a compile-time constant rather than a live-reconfigurable one. */
	public static final float SCALE = 18.0f / 1.95f;

	private enum Attack { NONE, PUNCH, SWEEP, STOMP, SLAM, SHOCKWAVE, GRAB, BOULDER, CHARGE, LEAP, ROAR }

	/**
	 * v0.14.4: the body animation the client should be playing. Synced as {@link #DATA_ANIM} (ordinal in the
	 * low byte, a bump counter above it so replaying the same move still reads as a change); the client
	 * times it from the moment the value arrives ({@link #onSyncedDataUpdated}) and the GeckoLib controllers
	 * ({@link #registerControllers}) play the matching clip. Every telegraphed attack's clip strikes at tick
	 * {@link #WINDUP_TICKS} (clip tick {@code WINDUP_TICKS - ANIM_TRANSITION}, see {@link #ANIM_TRANSITION}),
	 * matching the server's resolution, so the swing lands on screen exactly when the damage does.
	 * v0.14.20: {@code DEATH} (appended, so older ordinals are unchanged).
	 */
	public enum Anim {
		NONE, PUNCH, SWEEP, STOMP, SLAM, SHOCKWAVE, GRAB, GRAB_THROW, BOULDER, CHARGE,
		LEAP, LEAP_AIR, LEAP_LAND, ROAR, SWAT, INTRO, DEATH;

		private static final Anim[] VALUES = values();

		public static Anim byId(int id) {
			return id >= 0 && id < VALUES.length ? VALUES[id] : NONE;
		}
	}

	private static final net.minecraft.network.syncher.EntityDataAccessor<Integer> DATA_ANIM =
			net.minecraft.network.syncher.SynchedEntityData.defineId(TitanEntity.class,
					net.minecraft.network.syncher.EntityDataSerializers.INT);

	/** Tag carried by the Husks a Grave Roar raises, so they can be counted (cap) and cleared on death. */
	public static final String MINION_TAG = "projecthero_titan_minion";

	/**
	 * v0.10.11: every telegraphed attack now winds up for a uniform 2 seconds, with its own distinct
	 * charge-up particle signature (see {@link #emitTelegraph}), so a player can read which move is
	 * coming and answer it. CHARGE keeps this as its launch delay; the rest resolve when it hits 0.
	 */
	private static final int WINDUP_TICKS = 40;

	private Attack activeAttack = Attack.NONE;
	private int attackTicks;
	private boolean attackResolved;
	private int globalAttackCooldown;
	private final int[] attackCooldowns = new int[Attack.values().length];

	private Vec3 chargeDirection = Vec3.ZERO;
	private double chargeDistanceLeft;

	private UUID grabbedPlayer;
	private int grabTicksLeft;

	private double lastDistanceToTarget = -1;
	private int fleeSignal;
	private int meleeCooldown;

	private Vec3 lastUnstickPos = Vec3.ZERO;
	private int stuckTicks;

	private EventBossBar bossBar;

	// v0.14.4 threat / aggro
	private final com.projecthero.mod.titan.TitanThreat threat = new com.projecthero.mod.titan.TitanThreat();
	private int retargetTimer;

	// v0.14.4 melee swat wind-up
	private int swatWindup;
	private Vec3 swatDir = Vec3.ZERO;

	// v0.14.4 Leaping Slam: 0 = winding up, 1 = airborne, 2 = landing ring travelling outward
	private int leapPhase;
	private int leapTick;
	private int leapFlightTicks;
	private double leapApex;
	private Vec3 leapFrom = Vec3.ZERO;
	private Vec3 leapTo = Vec3.ZERO;
	private Vec3 ringCenter = Vec3.ZERO;
	private double ringRadius;
	private final java.util.Set<UUID> ringHit = new java.util.HashSet<>();

	// v0.14.4 Grave Roar
	private int roarTick;

	// v0.14.4 animation sync -- server side
	private int animSeq;
	private int animTicksLeft;
	// ...and client side (plain fields, only ever written on the client copy of the entity)
	private Anim clientAnim = Anim.NONE;
	private int clientAnimStart;
	private Anim clientPrevAnim = Anim.NONE;
	private int clientPrevAnimStart;

	// v0.14.20 GeckoLib -- client side only
	private final AnimatableInstanceCache geoCache = GeckoLibUtil.createInstanceCache(this);
	private int mainClipStart = Integer.MIN_VALUE;
	private int upperClipStart = Integer.MIN_VALUE;
	private boolean clientRunning;
	/** Client: how much the head currently follows the look target (eased by the model, 0..1). */
	public float clientHeadWeight = 1.0f;

	public TitanEntity(EntityType<? extends TitanEntity> type, Level level) {
		super(type, level);
		this.xpReward = 200;
	}

	@Override
	protected void defineSynchedData(net.minecraft.network.syncher.SynchedEntityData.Builder builder) {
		super.defineSynchedData(builder);
		builder.define(DATA_ANIM, 0);
	}

	@Override
	public void onSyncedDataUpdated(net.minecraft.network.syncher.EntityDataAccessor<?> key) {
		super.onSyncedDataUpdated(key);
		if (DATA_ANIM.equals(key) && level() != null && level().isClientSide()) {
			clientPrevAnim = clientAnim;
			clientPrevAnimStart = clientAnimStart;
			clientAnim = Anim.byId(entityData.get(DATA_ANIM) & 0xFF);
			clientAnimStart = tickCount;
		}
	}

	/** Server: start playing {@code anim}; {@code duration > 0} returns to {@link Anim#NONE} after that many ticks. */
	private void setAnim(Anim anim, int duration) {
		animSeq = (animSeq + 1) & 0x7FFFFF;
		entityData.set(DATA_ANIM, anim.ordinal() | (animSeq << 8));
		animTicksLeft = duration;
	}

	private void tickAnim() {
		if (animTicksLeft > 0 && --animTicksLeft == 0) {
			setAnim(Anim.NONE, 0);
		}
	}

	/** The animation currently synced (server or client). */
	public Anim currentAnim() {
		return Anim.byId(entityData.get(DATA_ANIM) & 0xFF);
	}

	/** Client: the clip being played, when it started (entity tickCount) and the one it is blending from. */
	public Anim clientAnim() {
		return clientAnim;
	}

	public int clientAnimStart() {
		return clientAnimStart;
	}

	public Anim clientPrevAnim() {
		return clientPrevAnim;
	}

	public int clientPrevAnimStart() {
		return clientPrevAnimStart;
	}

	// ---------------- v0.14.20 GeckoLib animation ----------------

	/**
	 * Ticks the "main" controller spends blending into a new clip before the clip's own clock starts. Every attack
	 * clip in {@code titan.animation.json} therefore keys its strike at {@code WINDUP_TICKS - ANIM_TRANSITION}
	 * (the generator checks this), so the blow still lands on screen on the server's damage tick.
	 */
	public static final int ANIM_TRANSITION = 4;
	/** Blend-in of the "upper" controller, which only plays the Swat (its hit keyframe sits at 10 - this). */
	public static final int UPPER_TRANSITION = 2;
	/** Clip ticks of the Boulder clip during which the torn-up rock is drawn in its hands. */
	public static final int BOULDER_SHOWN_FROM = 14, BOULDER_SHOWN_TO = WINDUP_TICKS - ANIM_TRANSITION;
	/** Horizontal speed (blocks/tick) above which it plays the run cycle instead of the walk. */
	private static final double RUN_ABOVE = 0.27, WALK_BELOW = 0.23;

	private static final String CLIP = "animation.titan.";
	private static final RawAnimation IDLE = RawAnimation.begin().thenLoop(CLIP + "idle");
	private static final RawAnimation WALK = RawAnimation.begin().thenLoop(CLIP + "walk");
	private static final RawAnimation RUN = RawAnimation.begin().thenLoop(CLIP + "run");
	private static final RawAnimation SWAT_CLIP = RawAnimation.begin().thenPlay(CLIP + "swat");
	private static final RawAnimation CHARGE_CLIP = RawAnimation.begin().thenPlay(CLIP + "charge").thenLoop(CLIP + "charge_run");
	private static final java.util.Map<Anim, RawAnimation> HELD = new java.util.EnumMap<>(Anim.class);

	static {
		for (Anim a : Anim.values()) {
			if (a != Anim.NONE && a != Anim.SWAT && a != Anim.CHARGE) {
				HELD.put(a, RawAnimation.begin().thenPlayAndHold(CLIP + a.name().toLowerCase(java.util.Locale.ROOT)));
			}
		}
	}

	/** The clip played for {@code anim} on the main controller (null for NONE / SWAT). Package-visible for tests. */
	public static RawAnimation clipFor(Anim anim) {
		return anim == Anim.CHARGE ? CHARGE_CLIP : HELD.get(anim);
	}

	@Override
	public AnimatableInstanceCache getAnimatableInstanceCache() {
		return geoCache;
	}

	/**
	 * Two controllers. "main" owns the whole body: the synced attack clip whenever there is one (restarted when a
	 * new one arrives, even the same move twice -- {@link #clientAnimStart} changes), otherwise idle / walk / run by
	 * how fast the giant is actually moving. "upper" only plays the Swat, which keys just the torso, head and arms,
	 * so the legs keep walking under it (a later controller wins for the bones it animates).
	 */
	@Override
	public void registerControllers(AnimatableManager.ControllerRegistrar controllers) {
		controllers.add(new AnimationController<>(this, "main", ANIM_TRANSITION, this::mainPredicate));
		controllers.add(new AnimationController<>(this, "upper", UPPER_TRANSITION, this::upperPredicate));
	}

	private PlayState mainPredicate(AnimationState<TitanEntity> state) {
		AnimationController<TitanEntity> controller = state.getController();
		Anim anim = isDeadOrDying() ? Anim.DEATH : clientAnim;
		RawAnimation clip = anim == Anim.SWAT ? null : clipFor(anim);
		if (clip != null) {
			int start = anim == clientAnim ? clientAnimStart : Integer.MIN_VALUE + 1;
			if (start != mainClipStart) {
				mainClipStart = start;
				controller.forceAnimationReset();
			}
			return state.setAndContinue(clip);
		}
		mainClipStart = Integer.MIN_VALUE;
		double dx = getX() - xo;
		double dz = getZ() - zo;
		double speed = Math.sqrt(dx * dx + dz * dz);
		clientRunning = clientRunning ? speed > WALK_BELOW : speed > RUN_ABOVE;
		if (speed > 0.025) {
			return state.setAndContinue(clientRunning ? RUN : WALK);
		}
		return state.setAndContinue(IDLE);
	}

	private PlayState upperPredicate(AnimationState<TitanEntity> state) {
		if (clientAnim != Anim.SWAT || isDeadOrDying()) {
			upperClipStart = Integer.MIN_VALUE;
			return PlayState.STOP;
		}
		if (clientAnimStart != upperClipStart) {
			upperClipStart = clientAnimStart;
			state.getController().forceAnimationReset();
		}
		return state.setAndContinue(SWAT_CLIP);
	}

	/**
	 * "changes 23": strip vanilla {@code Zombie}'s own {@code ZombieAttackGoal} (a {@code MeleeAttackGoal}
	 * on a plain ~1s cadence, completely outside {@link #globalAttackCooldown}). Left in place, it fired
	 * a fast, untelegraphed vanilla punch on top of the deliberately slower, telegraphed
	 * {@link #tickCombat} state machine below -- since the Titan has no bespoke animations (it renders as
	 * a scaled-up vanilla zombie model, see {@code TitanEntityRenderers}), that extra attack was
	 * indistinguishable from -- and drowned out -- the intended PUNCH/STOMP/SLAM moves, which is what
	 * read as "the Titan spams its smash attack constantly." {@link #tickApproach} replaces the
	 * chase-into-range half of what that goal used to do; {@link DisguisedTitanEntity} is deliberately
	 * NOT touched here, since it must go on looking and acting like an ordinary zombie until it
	 * transforms.
	 */
	@Override
	protected void registerGoals() {
		super.registerGoals();
		// v0.10.10 (performance): strip every vanilla goal that runs an A* search. Path-finding cost
		// scales with the entity's own footprint -- the node evaluator samples a
		// ceil(width) x ceil(height) x ceil(width) box of block states for EVERY node it visits -- so on
		// an 18-block frame a single search is thousands of times more expensive than it is for an
		// ordinary zombie, and vanilla Zombie/Monster ships four goals that start one on a timer whether
		// or not anything is happening ("he lags out the world just by existing"). The Titan does not
		// need any of them: it hunts through {@link #tickApproach}'s direct steering, and terrain in the
		// way is handled by Step Assist plus {@link #tickUnstick}'s corridor carving.
		this.goalSelector.removeAllGoals(goal ->
				goal instanceof net.minecraft.world.entity.ai.goal.MeleeAttackGoal
						|| goal instanceof net.minecraft.world.entity.ai.goal.MoveThroughVillageGoal
						|| goal instanceof net.minecraft.world.entity.ai.goal.RandomStrollGoal
						|| goal instanceof net.minecraft.world.entity.ai.goal.MoveTowardsRestrictionGoal
						|| goal instanceof net.minecraft.world.entity.ai.goal.RemoveBlockGoal
						|| goal instanceof net.minecraft.world.entity.ai.goal.BreakDoorGoal);
		// Target scans are cheap, but only the player scan is wanted: a world boss chasing a wandering
		// villager or a turtle across the map is both wrong and (via the chase) expensive.
		//
		// v0.14.4: every target goal goes, HurtByTargetGoal included. That goal only retargets when it
		// *starts*; once running against player A it ignored every hit from player B -- the "he only targets
		// one person while the others hit him for free" report. Targeting is the threat table's job now
		// (tickThreat / TitanThreat).
		this.targetSelector.removeAllGoals(goal -> true);
	}

	public static AttributeSupplier.Builder createAttributes() {
		var stats = TitanConfig.stats();
		var atk = TitanConfig.attacks();
		return Zombie.createAttributes()
				.add(Attributes.MAX_HEALTH, stats.health)
				.add(Attributes.ATTACK_DAMAGE, atk.punchDamage)
				.add(Attributes.MOVEMENT_SPEED, stats.normalSpeed)
				.add(Attributes.FOLLOW_RANGE, stats.followRange)
				.add(Attributes.KNOCKBACK_RESISTANCE, stats.knockbackResistance)
				.add(Attributes.ARMOR, 10.0)
				.add(Attributes.ARMOR_TOUGHNESS, 8.0)
				.add(Attributes.STEP_HEIGHT, stats.stepHeight)
				.add(Attributes.ATTACK_KNOCKBACK, 2.0);
	}

	/**
	 * v0.9.22: a navigator tuned for a huge boss that must run players down across long distances and
	 * broken terrain. Floats over water rather than stalling in it, walks over fences, and searches
	 * many more nodes than a normal mob so it can actually find a route to a target up to
	 * {@link TitanConfig.Stats#followRange} blocks away. Getting physically wedged is handled
	 * separately by {@link #tickUnstick}.
	 */
	@Override
	protected PathNavigation createNavigation(Level level) {
		GroundPathNavigation nav = new GroundPathNavigation(this, level);
		nav.setCanFloat(true);
		nav.setCanWalkOverFences(true);
		// v0.10.10: back down to vanilla's default. Nothing routinely paths any more (see
		// registerGoals / tickApproach); this only bounds the cost if some other system ever asks.
		nav.setMaxVisitedNodesMultiplier(1.0f);
		return nav;
	}

	/**
	 * v0.9.22: the pathfinder may route the Titan down tall slopes and cliffs -- it takes no fall
	 * damage ({@link #causeFallDamage}), so a big "comfortable fall" keeps it from freezing at the top
	 * of every downhill instead of following the player down.
	 */
	@Override
	public int getMaxFallDistance() {
		return 32;
	}

	@Override
	public EntityDimensions getDefaultDimensions(Pose pose) {
		return super.getDefaultDimensions(pose).scale(SCALE);
	}

	@Override
	public boolean isBaby() {
		return false;
	}

	@Override
	public boolean causeFallDamage(float distance, float multiplier, DamageSource source) {
		return false; // no normal fall damage -- its own attacks are the only source of terrain interaction
	}

	@Override
	public boolean removeWhenFarAway(double distanceSq) {
		return false;
	}

	/** Called once, right after {@link DisguisedTitanEntity} spawns this entity. */
	public void onTransformed() {
		// setHealth(), not heal() -- heal() only applies while current health is already > 0, which is
		// not a safe assumption to make about a just-constructed entity.
		setHealth(getMaxHealth());
		if (level() instanceof ServerLevel server) {
			server.playSound(null, blockPosition(), SoundEvents.RAVAGER_ROAR, SoundSource.HOSTILE, 4.0f, 0.5f);
			server.sendParticles(ParticleTypes.EXPLOSION, getX(), getY() + getBbHeight() * 0.5, getZ(), 1, 0, 0, 0, 0);
			// v0.14.4: rises roaring -- and doesn't swing at anyone until the roar has finished.
			setAnim(Anim.INTRO, 56);
			globalAttackCooldown = Math.max(globalAttackCooldown, 50);
			// v0.13.5: was an unconditional (ServerLevel) cast on level() outside this guard -- harmless
			// today since this is only ever reached from the server-side transform, but a real
			// ClassCastException waiting to happen the moment that stops being true.
			bossBar().update(server, blockPosition(), TitanConfig.stats().detectionRange,
					Component.translatable("entity.projecthero.titan"), 1.0f);
		}
	}

	private EventBossBar bossBar() {
		if (bossBar == null) {
			bossBar = new EventBossBar(getUUID(), BossEvent.BossBarColor.RED, BossEvent.BossBarOverlay.PROGRESS, true);
		}
		return bossBar;
	}

	@Override
	public void aiStep() {
		super.aiStep();
		if (level().isClientSide()) {
			return;
		}
		ServerLevel server = (ServerLevel) level();
		tickAnim();
		if (deathTicks >= 0 || isDeadOrDying()) {
			return; // collapsing -- no more attacks, targeting or terrain
		}
		footsteps(server);
		if (TitanConfig.world().passiveWalkingDestructionEnabled) {
			passiveDestruction(server);
		}
		tickThreat(server);
		tickGrab(server);
		tickApproach();
		tickUnstick(server);
		tickMeleeSwipe(server);
		tickCombat(server);
		updateBossBar(server);
		yellowAura(server);
	}

	/**
	 * v0.10.19: a steady drift of yellow embers off the Titan's body -- makes the boss read as
	 * charged-up/powered even while it is just walking, on top of the yellow already layered into its
	 * attack bursts below.
	 */
	private void yellowAura(ServerLevel server) {
		if (tickCount % 5 != 0) {
			return;
		}
		double w = getBbWidth();
		double h = getBbHeight();
		for (int i = 0; i < 3; i++) {
			double ox = (server.random.nextDouble() - 0.5) * w;
			double oy = server.random.nextDouble() * h;
			double oz = (server.random.nextDouble() - 0.5) * w;
			server.sendParticles(new net.minecraft.core.particles.DustParticleOptions(
							new org.joml.Vector3f(1.0f, 0.82f, 0.15f), 2.2f),
					getX() + ox, getY() + oy, getZ() + oz, 1, 0.0, 0.02, 0.0, 0.0);
		}
	}

	// ---------------- v0.14.4 threat / aggro ----------------

	/** A player the Titan may chase: alive, in this level, and not creative or spectator. */
	public boolean isValidTarget(LivingEntity e) {
		return e instanceof Player p && p.isAlive() && !p.isRemoved() && !creativeOrSpectator(p) && p.level() == level();
	}

	/** Reads a server player's actual game mode (the GameTest mock player overrides {@code isCreative()}). */
	private static boolean creativeOrSpectator(Player p) {
		if (p instanceof ServerPlayer sp) {
			var mode = sp.gameMode.getGameModeForPlayer();
			return mode == net.minecraft.world.level.GameType.CREATIVE || mode == net.minecraft.world.level.GameType.SPECTATOR;
		}
		return p.isCreative() || p.isSpectator();
	}

	/** Damage from a player builds that player's threat (see {@link com.projecthero.mod.titan.TitanThreat}). */
	@Override
	public boolean hurt(DamageSource source, float amount) {
		boolean hurt = super.hurt(source, amount);
		if (hurt && !level().isClientSide() && source.getEntity() instanceof Player p && isValidTarget(p)) {
			var cfg = TitanConfig.aggro();
			threat.add(p, amount * cfg.damageThreatMultiplier, tickCount, cfg.threatHalfLifeTicks);
			if (!isValidTarget(getTarget())) {
				switchTarget(p);
			}
		}
		return hurt;
	}

	/**
	 * v0.14.4 (replaces "changes 25"'s acquireTarget): proximity threat every half second, and a re-evaluation
	 * of who to chase every {@link TitanConfig.Aggro#retargetIntervalTicks} -- immediately if the current target
	 * has become invalid (died, logged out, went creative/spectator, left the dimension or outran follow range).
	 * Not mid-attack or mid-grab: turning round halfway through a wind-up would make the telegraph lie.
	 */
	private void tickThreat(ServerLevel server) {
		var cfg = TitanConfig.aggro();
		if (tickCount % 10 == 0) {
			double range = cfg.proximityRange + getBbWidth() * 0.5;
			for (ServerPlayer p : server.players()) {
				if (!isValidTarget(p)) {
					continue;
				}
				double d = Math.sqrt(distanceToSqr(p));
				if (d <= range) {
					threat.add(p, cfg.proximityThreatPerSecond * 0.5 * (1.0 - 0.5 * d / range), tickCount,
							cfg.threatHalfLifeTicks);
				}
			}
			threat.prune(tickCount, cfg.threatHalfLifeTicks, this::isValidTarget);
		}
		LivingEntity current = getTarget();
		double follow = TitanConfig.stats().followRange;
		boolean currentValid = isValidTarget(current) && distanceToSqr(current) <= follow * follow;
		if (currentValid) {
			boolean busy = activeAttack != Attack.NONE || grabbedPlayer != null || swatWindup > 0;
			if (busy || --retargetTimer > 0) {
				return;
			}
		}
		retargetTimer = Math.max(1, cfg.retargetIntervalTicks);
		reevaluateTarget(server, false);
	}

	/**
	 * Pick who to chase from every valid player within detection range. {@code deterministic} skips the random
	 * pick (tests); the live loop passes false. Returns the chosen target (may be unchanged, or null).
	 */
	public LivingEntity reevaluateTarget(ServerLevel server, boolean deterministic) {
		double range = TitanConfig.stats().detectionRange;
		java.util.List<Player> candidates = new java.util.ArrayList<>();
		for (ServerPlayer p : server.players()) {
			if (isValidTarget(p) && distanceToSqr(p) <= range * range) {
				candidates.add(p);
			}
		}
		LivingEntity current = getTarget();
		Player currentPlayer = isValidTarget(current) ? (Player) current : null;
		if (currentPlayer != null && !candidates.contains(currentPlayer)) {
			double follow = TitanConfig.stats().followRange;
			if (distanceToSqr(currentPlayer) <= follow * follow) {
				candidates.add(currentPlayer); // still being chased, just past the detection radius
			}
		}
		Player chosen = threat.pick(candidates, currentPlayer, position(), tickCount, TitanConfig.aggro(),
				deterministic ? null : getRandom());
		if (chosen != current) {
			switchTarget(chosen);
		}
		return chosen;
	}

	private void switchTarget(Player next) {
		LivingEntity previous = getTarget();
		setTarget(next);
		lastDistanceToTarget = -1;
		fleeSignal = 0;
		if (next != null && previous != null && previous != next && level() instanceof ServerLevel server) {
			// A readable "he's coming for YOU now": a low growl and a burst of angry sparks over the new target.
			server.playSound(null, blockPosition(), SoundEvents.RAVAGER_AMBIENT, SoundSource.HOSTILE, 3.0f, 0.45f);
			server.sendParticles(ParticleTypes.ANGRY_VILLAGER, next.getX(), next.getY() + next.getBbHeight() + 0.6,
					next.getZ(), 4, 0.3, 0.2, 0.3, 0.0);
		}
	}

	/** Test/debug view of a player's current threat. */
	public double threatOf(Player p) {
		return threat.threatOf(p, tickCount, TitanConfig.aggro().threatHalfLifeTicks);
	}

	/**
	 * "changes 25": a plain, reliable melee so nobody can hug the leg untouched. v0.14.4: it now has a short,
	 * readable wind-up (a raised arm, {@link TitanConfig.Attacks#meleeWindupTicks}) and swats <em>every</em>
	 * player in reach in a wide frontal arc -- not just the current target -- so the rest of the group can't
	 * stand at his feet for free either.
	 */
	private void tickMeleeSwipe(ServerLevel server) {
		if (meleeCooldown > 0) {
			meleeCooldown--;
		}
		if (swatWindup > 0) {
			if (--swatWindup == 0) {
				doSwat(server);
			}
			return;
		}
		if (meleeCooldown > 0 || activeAttack != Attack.NONE || grabbedPlayer != null) {
			return;
		}
		double reach = TitanConfig.attacks().meleeRange + getBbWidth() * 0.5;
		LivingEntity target = getTarget();
		Player victim = null;
		if (isValidTarget(target) && inSwatReach(target, reach)) {
			victim = (Player) target;
		} else {
			double best = Double.MAX_VALUE;
			for (Player p : nearbyLiving(reach).stream().filter(le -> le instanceof Player).map(le -> (Player) le).toList()) {
				double d = distanceToSqr(p);
				if (inSwatReach(p, reach) && d < best) {
					best = d;
					victim = p;
				}
			}
		}
		if (victim == null) {
			return;
		}
		Vec3 dir = new Vec3(victim.getX() - getX(), 0, victim.getZ() - getZ());
		swatDir = dir.lengthSqr() < 1.0e-4 ? Vec3.directionFromRotation(0, getYRot()) : dir.normalize();
		faceDirection(swatDir);
		int windup = Math.max(1, TitanConfig.attacks().meleeWindupTicks);
		swatWindup = windup;
		setAnim(Anim.SWAT, windup + 14);
		server.playSound(null, blockPosition(), SoundEvents.ZOMBIE_AMBIENT, SoundSource.HOSTILE, 2.5f, 0.35f);
	}

	private boolean inSwatReach(LivingEntity e, double reach) {
		double dx = e.getX() - getX();
		double dz = e.getZ() - getZ();
		double dy = e.getY() - getY();
		return dx * dx + dz * dz <= reach * reach && dy >= -3.0 && dy <= getBbHeight() + 2.0;
	}

	private void doSwat(ServerLevel server) {
		double reach = TitanConfig.attacks().meleeRange + getBbWidth() * 0.5;
		boolean hitAny = false;
		for (LivingEntity le : nearbyLiving(reach)) {
			if (!inSwatReach(le, reach)) {
				continue;
			}
			Vec3 flat = new Vec3(le.getX() - getX(), 0, le.getZ() - getZ());
			if (flat.lengthSqr() > 1.0e-4 && flat.normalize().dot(swatDir) < -0.2) {
				continue; // behind the swing
			}
			le.hurt(damageSources().mobAttack(this), scaleForPlayer(le, TitanConfig.attacks().meleeDamage));
			Vec3 push = flat.lengthSqr() < 1.0e-4 ? swatDir : flat.normalize();
			le.setDeltaMovement(le.getDeltaMovement().add(push.x * 1.4, 0.42, push.z * 1.4));
			le.hurtMarked = true;
			server.sendParticles(ParticleTypes.CRIT, le.getX(), le.getY() + 1, le.getZ(), 12, 0.3, 0.3, 0.3, 0.1);
			hitAny = true;
		}
		meleeCooldown = TitanConfig.attacks().meleeCooldownTicks;
		server.playSound(null, blockPosition(), hitAny ? SoundEvents.PLAYER_ATTACK_STRONG : SoundEvents.PLAYER_ATTACK_SWEEP,
				SoundSource.HOSTILE, 2.0f, 0.6f);
	}

	/** Snap body, head and yaw to face along {@code dir} (flat), so the animation swings where the hit lands. */
	private void faceDirection(Vec3 dir) {
		if (dir.lengthSqr() < 1.0e-6) {
			return;
		}
		float yaw = (float) (Mth.atan2(dir.z, dir.x) * (180.0 / Math.PI)) - 90.0f;
		setYRot(yaw);
		yBodyRot = yaw;
		yHeadRot = yaw;
	}

	private void faceTarget(LivingEntity target) {
		if (target != null) {
			faceDirection(new Vec3(target.getX() - getX(), 0, target.getZ() - getZ()));
		}
	}

	/** Turn toward {@code target} by at most {@code maxDegrees} this tick (tracking during a wind-up). */
	private void turnToward(LivingEntity target, float maxDegrees) {
		if (target == null || !target.isAlive()) {
			return;
		}
		double dx = target.getX() - getX();
		double dz = target.getZ() - getZ();
		if (dx * dx + dz * dz < 1.0e-4) {
			return;
		}
		float want = (float) (Mth.atan2(dz, dx) * (180.0 / Math.PI)) - 90.0f;
		float yaw = Mth.approachDegrees(getYRot(), want, maxDegrees);
		setYRot(yaw);
		yBodyRot = yaw;
		yHeadRot = yaw;
	}

	private static final net.minecraft.resources.ResourceLocation CHASE_SPEED_ID =
			com.projecthero.mod.ProjectHeroMod.id("titan_chase_speed");
	private boolean chaseSpeedActive;

	/**
	 * Replaces the chase-into-range half of vanilla's {@code ZombieAttackGoal} (removed in
	 * {@link #registerGoals}) now that the goal supplying it is gone: keep walking toward the current
	 * target and facing it, but never apply damage here -- damage only ever comes from
	 * {@link #tickCombat}'s own attacks. Paused mid-attack ({@code beginAttack} already parks the
	 * navigator) and while holding a grabbed player, so it does not fight the grab-hold teleport.
	 *
	 * <p>"changes 24": also applies {@link TitanConfig.Stats#aggressiveSpeed} while a target is being
	 * chased -- that field existed in the config from the start but nothing ever read it, so the Titan
	 * always walked at its idle {@code normalSpeed} (0.225, i.e. an ordinary zombie's own pace) even
	 * mid-fight, which reads as sluggish on an 18-block frame with a correspondingly huge stride. A
	 * transient {@link net.minecraft.world.entity.ai.attributes.AttributeModifier} is added the moment a
	 * target appears and removed the moment it is lost, rather than baking the boost into the base
	 * attribute, so the Titan is genuinely calmer (and this boost genuinely readable as "it noticed you")
	 * outside of combat.
	 */
	private void tickApproach() {
		LivingEntity target = getTarget();
		boolean hasTarget = target != null && target.isAlive();
		if (hasTarget != chaseSpeedActive) {
			var speedAttr = getAttribute(Attributes.MOVEMENT_SPEED);
			if (speedAttr != null) {
				speedAttr.removeModifier(CHASE_SPEED_ID);
				if (hasTarget) {
					double boost = TitanConfig.stats().aggressiveSpeed - TitanConfig.stats().normalSpeed;
					speedAttr.addTransientModifier(new net.minecraft.world.entity.ai.attributes.AttributeModifier(
							CHASE_SPEED_ID, boost, net.minecraft.world.entity.ai.attributes.AttributeModifier.Operation.ADD_VALUE));
				}
			}
			chaseSpeedActive = hasTarget;
		}
		if (!hasTarget || activeAttack != Attack.NONE || grabbedPlayer != null) {
			return;
		}
		getLookControl().setLookAt(target, 30.0f, 30.0f);
		// v0.10.10 (performance): steer straight at the target instead of running an A* search at it.
		// MoveControl just points the body at a position and applies the movement-speed attribute -- no
		// graph search, no node sampling, so it costs effectively nothing however big the Titan is. The
		// old repath-every-10-ticks call was the single largest source of the "he lags out the world"
		// report: each search sampled an ~19x19x19 block box per visited node.
		//
		// Losing the pathfinder loses obstacle avoidance, which for this boss is the point -- terrain is
		// an inconvenience, not a barrier. Step Assist (STEP_HEIGHT 10) walks it up anything shorter
		// than itself and tickUnstick punches a corridor through whatever is left.
		getMoveControl().setWantedPosition(target.getX(), target.getY(), target.getZ(), 1.0);
	}

	/**
	 * v0.9.22: "the Titan can never be hard-stopped by terrain." If it is chasing a target, not
	 * mid-attack, and has made almost no horizontal progress for a full second despite wanting to
	 * close the distance, punch a Titan-sized corridor through whatever is in the way toward the
	 * target and give itself a shove. Step Assist (STEP_HEIGHT 10) covers ordinary ledges; this only
	 * ever fires when something genuinely walled it in.
	 */
	private void tickUnstick(ServerLevel server) {
		LivingEntity target = getTarget();
		if (target == null || !target.isAlive() || activeAttack != Attack.NONE || grabbedPlayer != null) {
			stuckTicks = 0;
			return;
		}
		if (distanceTo(target) <= TitanConfig.attacks().meleeRange) {
			stuckTicks = 0;
			return;
		}
		Vec3 pos = position();
		double dx = pos.x - lastUnstickPos.x;
		double dz = pos.z - lastUnstickPos.z;
		lastUnstickPos = pos;
		if (dx * dx + dz * dz < 0.02 * 0.02) {
			stuckTicks++;
		} else {
			stuckTicks = Math.max(0, stuckTicks - 3);
		}
		// v0.10.10: half a second, not a full one -- with the pathfinder gone (see tickApproach) this is
		// the only thing that gets the Titan past a wall, so it should not dither in front of one.
		if (stuckTicks < 10) {
			return;
		}
		stuckTicks = 0;
		Vec3 dir = new Vec3(target.getX() - getX(), 0, target.getZ() - getZ());
		if (dir.lengthSqr() < 1.0e-4) {
			return;
		}
		dir = dir.normalize();
		int width = (int) Math.ceil(getBbWidth()) + 2;
		Vec3 from = position().add(0, 0.5, 0);
		Vec3 to = from.add(dir.scale(width + 3.0));
		TitanTerrain.carveCorridor(server, from, to, width, Math.min(12, (int) Math.ceil(getBbHeight())));
		setDeltaMovement(getDeltaMovement().add(dir.x * 0.4, 0.05, dir.z * 0.4));
		// v0.10.10: steer, don't path -- see tickApproach for why no A* search runs here any more.
		getMoveControl().setWantedPosition(target.getX(), target.getY(), target.getZ(), 1.0);
	}

	private void updateBossBar(ServerLevel server) {
		if (isRemoved() || isDeadOrDying()) {
			return;
		}
		// v0.10.10: five times a second is plenty for a health bar, and each refresh walks the level's
		// whole player list to recompute the audience.
		if (tickCount % 4 != 0) {
			return;
		}
		float progress = Math.max(0.0f, getHealth() / getMaxHealth());
		bossBar().update(server, blockPosition(), TitanConfig.stats().followRange,
				Component.translatable("entity.projecthero.titan"), progress);
	}

	// ---------------- footsteps / terrain ----------------

	/**
	 * "changes 24": gated on actually walking, not just standing on the ground -- it used to fire every
	 * 8 ticks purely off {@code onGround()}, so an idle Titan just standing there (which is most of a
	 * fight: it stops moving for every attack windup, and now also whenever it has no target) kept
	 * booming a heavy impact sound nonstop for no visible reason. {@code getDeltaMovement()} is the
	 * server's own authoritative velocity, so this reads real movement rather than guessing from the
	 * navigator's state.
	 */
	private void footsteps(ServerLevel server) {
		if (tickCount % 8 != 0 || !onGround()) {
			return;
		}
		Vec3 delta = getDeltaMovement();
		if (delta.x * delta.x + delta.z * delta.z < 0.003) {
			return;
		}
		server.sendParticles(ParticleTypes.CLOUD, getX(), getY() + 0.1, getZ(), 8, getBbWidth() * 0.3, 0.05,
				getBbWidth() * 0.3, 0.02);
		server.playSound(null, blockPosition(), SoundEvents.GENERIC_BIG_FALL, SoundSource.HOSTILE, 2.5f, 0.5f);
	}

	/** Only genuinely fragile blocks the huge body intersects -- see {@link TitanTerrain#breakFragileAt}. */
	/**
	 * v0.10.10 (performance): this used to walk the Titan's ENTIRE bounding box -- ~10 x 18 x 10, near
	 * enough two thousand {@code getBlockState} lookups -- every 10 ticks, standing still or not. That
	 * is a per-tick average of a couple of hundred block reads spent almost entirely on air, for a
	 * cosmetic effect (brushing leaves and glass aside).
	 *
	 * <p>Now it only runs while the Titan is actually moving, and only scans the slab it is walking
	 * <em>through</em> -- from its feet to a little over head height on a player's scale -- rather than
	 * the full column up to its shoulders, which is where nothing it walks into ever is. That is roughly
	 * a twentieth of the work, and none of it while it is standing in a wind-up.
	 */
	private void passiveDestruction(ServerLevel server) {
		if (tickCount % 10 != 0 || !TitanConfig.world().blockDestructionEnabled) {
			return;
		}
		Vec3 delta = getDeltaMovement();
		if (delta.x * delta.x + delta.z * delta.z < 0.003) {
			return;
		}
		var box = getBoundingBox();
		int minY = Mth.floor(box.minY);
		int maxY = Math.min(Mth.floor(box.maxY), minY + 3);
		for (BlockPos p : BlockPos.betweenClosed(
				BlockPos.containing(box.minX, minY, box.minZ), BlockPos.containing(box.maxX, maxY, box.maxZ))) {
			TitanTerrain.breakFragileAt(server, p);
		}
	}

	// ---------------- attack state machine ----------------

	private void tickCombat(ServerLevel server) {
		for (int i = 0; i < attackCooldowns.length; i++) {
			if (attackCooldowns[i] > 0) {
				attackCooldowns[i]--;
			}
		}
		if (globalAttackCooldown > 0) {
			globalAttackCooldown--;
		}

		LivingEntity target = getTarget();
		if (activeAttack != Attack.NONE) {
			resolveActiveAttack(server, target);
			return;
		}
		if (target == null || !target.isAlive() || globalAttackCooldown > 0 || grabbedPlayer != null || swatWindup > 0) {
			return;
		}
		trackFleeSignal(target);
		Attack chosen = chooseAttack(target);
		if (chosen != Attack.NONE) {
			beginAttack(server, chosen, target);
		}
	}

	private void trackFleeSignal(LivingEntity target) {
		double d = distanceTo(target);
		if (lastDistanceToTarget >= 0) {
			fleeSignal = d > lastDistanceToTarget + 0.05 ? Math.min(20, fleeSignal + 1) : Math.max(0, fleeSignal - 1);
		}
		lastDistanceToTarget = d;
	}

	private Attack chooseAttack(LivingEntity target) {
		double dist = distanceTo(target);
		double dy = target.getY() - getY();
		boolean underfoot = dist < 5.0 && dy < -1.5;
		boolean veryClose = dist < 4.0;
		boolean fleeing = fleeSignal >= 8;
		boolean airborne = !target.onGround() && target.getY() - getY() > 3.0;

		java.util.List<Attack> pool = new java.util.ArrayList<>();
		if (dist <= TitanConfig.attacks().punchRange && ready(Attack.PUNCH)) {
			addWeighted(pool, Attack.PUNCH, 3);
		}
		// v0.10.11: a wide backhand sweep -- a mid-range alternative to the single-target punch that
		// catches a whole group standing in front of the Titan and hurls them back.
		if (dist <= 12.0 && ready(Attack.SWEEP)) {
			addWeighted(pool, Attack.SWEEP, veryClose ? 4 : 3);
		}
		// v0.10.11: a ground shockwave -- a big radial pulse that reaches much further than Stomp/Slam
		// and knocks everyone in the ring straight up.
		if (dist <= TitanConfig.attacks().shockwaveRadius && ready(Attack.SHOCKWAVE)) {
			addWeighted(pool, Attack.SHOCKWAVE, fleeing || dist > 8.0 ? 4 : 2);
		}
		if (underfoot && ready(Attack.STOMP)) {
			addWeighted(pool, Attack.STOMP, 6);
		} else if (dist <= 6.0 && ready(Attack.STOMP)) {
			addWeighted(pool, Attack.STOMP, 1);
		}
		// "changes 24": Ground Slam's actual damage is an AoE of only TitanConfig.attacks().slamRadius
		// (6.0 by default) centred on the Titan itself once the 18-tick windup ends -- and beginAttack()
		// stops the navigator for the whole windup, so the Titan does not close distance during it. The
		// old `dist <= 20.0` selection let it pick Slam from up to 20 blocks away, which is a guaranteed
		// total whiff against a target nowhere near the blast by the time it lands -- this is what read
		// as "his moves don't seem to do AoE damage like they should." Tightened to the radius plus a
		// small margin for the target's own movement during the windup, matching Stomp's existing
		// radius-plus-a-little-slack fallback range just above.
		if (dist <= TitanConfig.attacks().slamRadius + 3.0 && ready(Attack.SLAM)) {
			addWeighted(pool, Attack.SLAM, veryClose ? 4 : 2);
		}
		if (dist <= 6.0 && !airborne && ready(Attack.GRAB) && target instanceof ServerPlayer) {
			addWeighted(pool, Attack.GRAB, veryClose ? 4 : 2);
		}
		// v0.9.22: capped -- with a 150-block detection range the Titan would otherwise lob boulders
		// from across the map. Beyond this it just closes the distance on foot.
		if (dist > 6.0 && dist <= 48.0 && ready(Attack.BOULDER)) {
			addWeighted(pool, Attack.BOULDER, fleeing || airborne ? 5 : 2);
		}
		if (dist > 6.0 && dist < TitanConfig.attacks().chargeMaxDistance && hasLineOfSight(target) && ready(Attack.CHARGE)) {
			addWeighted(pool, Attack.CHARGE, fleeing ? 5 : 2);
		}
		// v0.14.4 Leaping Slam: the answer to a target kiting at mid range -- it lands on them.
		var atk = TitanConfig.attacks();
		if (dist >= atk.leapMinDistance && dist <= atk.leapMaxDistance && !airborne && ready(Attack.LEAP)) {
			addWeighted(pool, Attack.LEAP, fleeing ? 5 : 3);
		}
		// v0.14.4 Grave Roar: favoured when a group is around him (drags them all in, raises Husks on them) or
		// when the target is keeping its distance.
		if (dist <= atk.roarRadius && ready(Attack.ROAR)) {
			int around = countValidPlayersWithin(atk.roarRadius);
			addWeighted(pool, Attack.ROAR, (around >= 2 ? 3 : 1) + (fleeing || dist > 12.0 ? 2 : 0));
		}
		if (pool.isEmpty()) {
			return Attack.NONE;
		}
		return pool.get(getRandom().nextInt(pool.size()));
	}

	private static void addWeighted(java.util.List<Attack> pool, Attack a, int weight) {
		for (int i = 0; i < weight; i++) {
			pool.add(a);
		}
	}

	private boolean ready(Attack a) {
		return attackCooldowns[a.ordinal()] <= 0;
	}

	private void beginAttack(ServerLevel server, Attack attack, LivingEntity target) {
		activeAttack = attack;
		attackResolved = false;
		getNavigation().stop();
		// v0.10.10: the mover is what actually drives it now, so parking the (unused) navigator is not
		// enough on its own to hold it still for an attack wind-up.
		getMoveControl().setWantedPosition(getX(), getY(), getZ(), 0.0);
		// v0.10.11: uniform 2 s wind-up for every attack.
		attackTicks = WINDUP_TICKS;
		if (attack == Attack.CHARGE) {
			Vec3 dir = new Vec3(target.getX() - getX(), 0, target.getZ() - getZ());
			chargeDirection = dir.lengthSqr() < 1.0e-4 ? Vec3.directionFromRotation(0, getYRot()) : dir.normalize();
			chargeDistanceLeft = TitanConfig.attacks().chargeMaxDistance;
		}
		if (attack == Attack.LEAP) {
			leapPhase = 0;
			leapTick = 0;
		}
		if (attack == Attack.ROAR) {
			roarTick = 0;
		}
		// v0.14.4: square up to the target so the wind-up animation visibly points at who it's for.
		faceTarget(target);
		setAnim(animFor(attack), animLengthFor(attack));
		server.playSound(null, blockPosition(), telegraphSound(attack), SoundSource.HOSTILE, 2.6f, 0.5f);
	}

	private static Anim animFor(Attack a) {
		return switch (a) {
			case PUNCH -> Anim.PUNCH;
			case SWEEP -> Anim.SWEEP;
			case STOMP -> Anim.STOMP;
			case SLAM -> Anim.SLAM;
			case SHOCKWAVE -> Anim.SHOCKWAVE;
			case GRAB -> Anim.GRAB;
			case BOULDER -> Anim.BOULDER;
			case CHARGE -> Anim.CHARGE;
			case LEAP -> Anim.LEAP;
			case ROAR -> Anim.ROAR;
			default -> Anim.NONE;
		};
	}

	/** Server-side lifetime of each attack's clip: wind-up + ~1 s recovery; 0 = held until replaced. */
	private static int animLengthFor(Attack a) {
		return switch (a) {
			case CHARGE, LEAP -> 0;
			case ROAR -> WINDUP_TICKS + TitanConfig.attacks().roarDurationTicks + 16;
			default -> WINDUP_TICKS + 24;
		};
	}

	private static net.minecraft.sounds.SoundEvent telegraphSound(Attack a) {
		return switch (a) {
			case CHARGE -> SoundEvents.RAVAGER_ROAR;
			case LEAP -> SoundEvents.HOGLIN_ANGRY;
			case ROAR -> SoundEvents.WARDEN_AGITATED;
			case SLAM, SHOCKWAVE -> SoundEvents.WARDEN_SONIC_CHARGE;
			case BOULDER -> SoundEvents.RAVAGER_STUNNED;
			case GRAB -> SoundEvents.WARDEN_TENDRIL_CLICKS;
			case SWEEP -> SoundEvents.RAVAGER_ATTACK;
			default -> SoundEvents.RAVAGER_CELEBRATE;
		};
	}

	private void resolveActiveAttack(ServerLevel server, LivingEntity target) {
		attackTicks--;
		// The 2-second charge-up: a per-attack particle tell every tick until it resolves.
		if (attackTicks > 0) {
			emitTelegraph(server, activeAttack, attackTicks, target);
			if (activeAttack == Attack.CHARGE) {
				return; // still winding up
			}
			// v0.14.4: aimed moves keep slowly tracking their target through the wind-up (max 3 deg/tick), so
			// a sidestep still has to be a real one -- but the body visibly swings round to follow.
			if (activeAttack == Attack.PUNCH || activeAttack == Attack.GRAB || activeAttack == Attack.BOULDER
					|| activeAttack == Attack.SWEEP || activeAttack == Attack.LEAP) {
				turnToward(target, 3.0f);
			}
		}
		switch (activeAttack) {
			case PUNCH -> {
				if (attackTicks == 0 && !attackResolved) {
					doPunch(server, target);
				}
			}
			case SWEEP -> {
				if (attackTicks == 0 && !attackResolved) {
					doSweep(server);
				}
			}
			case STOMP -> {
				if (attackTicks == 0 && !attackResolved) {
					doStomp(server);
				}
			}
			case SLAM -> {
				if (attackTicks == 0 && !attackResolved) {
					doSlam(server);
				}
			}
			case SHOCKWAVE -> {
				if (attackTicks == 0 && !attackResolved) {
					doShockwave(server);
				}
			}
			case GRAB -> {
				if (attackTicks == 0 && !attackResolved) {
					doGrabAttempt(server, target);
				}
			}
			case BOULDER -> {
				if (attackTicks == 0 && !attackResolved) {
					doBoulder(server, target);
				}
			}
			case CHARGE -> {
				tickCharge(server);
				return;
			}
			case LEAP -> {
				if (attackTicks <= 0) {
					tickLeap(server);
				}
				return;
			}
			case ROAR -> {
				if (attackTicks <= 0) {
					tickRoar(server);
				}
				return;
			}
			default -> {
			}
		}
		if (attackTicks <= 0) {
			endAttack(activeAttack);
		}
	}

	/**
	 * The charge-up particle signature for {@code attack}, drawn every tick of its 2-second wind-up.
	 * Each move looks different so the telegraph is readable: a cocked fist, a sweeping arc at chest
	 * height, dust gathering under a raised foot, a crackling column overhead, a contracting ground
	 * ring, a reaching hand, a boulder forming in the palm, or the ground being pawed before a charge.
	 */
	private void emitTelegraph(ServerLevel server, Attack a, int remaining, LivingEntity target) {
		double cx = getX();
		double cy = getY();
		double cz = getZ();
		double h = getBbHeight();
		double w = getBbWidth();
		double progress = 1.0 - remaining / (double) WINDUP_TICKS;
		Vec3 aim = target != null && target.isAlive()
				? new Vec3(target.getX() - cx, 0, target.getZ() - cz)
				: Vec3.directionFromRotation(0, getYRot());
		aim = aim.lengthSqr() < 1.0e-4 ? Vec3.directionFromRotation(0, getYRot()) : aim.normalize();
		Vec3 side = new Vec3(-aim.z, 0, aim.x);
		switch (a) {
			case PUNCH -> {
				Vec3 fist = new Vec3(cx, cy + h * 0.78, cz).subtract(aim.scale(w * 0.45));
				server.sendParticles(ParticleTypes.CRIT, fist.x, fist.y, fist.z, 5, 0.35, 0.35, 0.35, 0.03);
			}
			case SWEEP -> {
				double ang = (remaining / (double) WINDUP_TICKS) * Math.PI - Math.PI / 2.0;
				Vec3 p = new Vec3(cx, cy + h * 0.55, cz)
						.add(side.scale(Math.cos(ang) * w * 0.9)).add(aim.scale(w * 0.6));
				server.sendParticles(ParticleTypes.SWEEP_ATTACK, p.x, p.y, p.z, 1, 0, 0, 0, 0);
				server.sendParticles(ParticleTypes.CLOUD, p.x, p.y, p.z, 2, 0.15, 0.15, 0.15, 0.0);
			}
			case STOMP -> {
				server.sendParticles(ParticleTypes.CLOUD, cx, cy + 0.1, cz, 4, w * 0.35, 0.05, w * 0.35, 0.01);
				server.sendParticles(ParticleTypes.POOF, cx, cy + 0.1, cz, 2, w * 0.3, 0.02, w * 0.3, 0.0);
			}
			case SLAM -> {
				server.sendParticles(ParticleTypes.ELECTRIC_SPARK, cx, cy + h + 0.6, cz,
						6, w * 0.4, 0.3, w * 0.4, 0.06);
				server.sendParticles(ParticleTypes.CRIT, cx, cy + h * (0.6 + 0.45 * progress), cz,
						4, w * 0.3, 0.4, w * 0.3, 0.02);
			}
			case SHOCKWAVE -> {
				double rad = 1.5 + 6.0 * (remaining / (double) WINDUP_TICKS);
				for (int i = 0; i < 8; i++) {
					double aa = server.random.nextDouble() * Math.PI * 2;
					server.sendParticles(ParticleTypes.SCULK_SOUL,
							cx + Math.cos(aa) * rad, cy + 0.35, cz + Math.sin(aa) * rad, 1, 0, 0, 0, 0);
				}
			}
			case GRAB -> {
				Vec3 hand = new Vec3(cx, cy + h * 0.6, cz).add(aim.scale(w * 0.7));
				server.sendParticles(ParticleTypes.PORTAL, hand.x, hand.y, hand.z, 6, 0.3, 0.4, 0.3, 0.05);
				server.sendParticles(ParticleTypes.ENCHANT, hand.x, hand.y + 1.0, hand.z, 4, 0.2, 0.2, 0.2, 0.1);
			}
			case BOULDER -> {
				Vec3 hand = new Vec3(cx, cy + h * 0.66, cz).add(aim.scale(w * 0.35));
				server.sendParticles(ParticleTypes.LARGE_SMOKE, hand.x, hand.y, hand.z,
						3, 0.35 + 0.3 * progress, 0.35, 0.35 + 0.3 * progress, 0.0);
				server.sendParticles(ParticleTypes.LAVA, hand.x, hand.y, hand.z, 1, 0.2, 0.2, 0.2, 0.0);
			}
			case CHARGE -> {
				Vec3 back = aim.scale(-1);
				server.sendParticles(ParticleTypes.ANGRY_VILLAGER, cx, cy + h * 0.85, cz, 1,
						w * 0.3, 0.2, w * 0.3, 0.0);
				server.sendParticles(ParticleTypes.CLOUD,
						cx + back.x * w * 0.5, cy + 0.1, cz + back.z * w * 0.5,
						4, w * 0.2, 0.05, w * 0.2, 0.03);
			}
			case LEAP -> {
				// Dust kicked up around the crouching feet, and a red warning ring on the target's spot.
				server.sendParticles(ParticleTypes.CLOUD, cx, cy + 0.1, cz, 3, w * 0.4, 0.05, w * 0.4, 0.02);
				if (target != null && target.isAlive() && remaining % 2 == 0) {
					leapWarningRing(server, target.position(), w * 0.5 + TitanConfig.attacks().leapCrushRadius);
				}
			}
			case ROAR -> {
				// The inhale: souls drawn up out of the ground into the Titan's chest.
				for (int i = 0; i < 4; i++) {
					double aa = server.random.nextDouble() * Math.PI * 2;
					double rr = w * (0.8 + 1.6 * (remaining / (double) WINDUP_TICKS));
					server.sendParticles(ParticleTypes.SOUL, cx + Math.cos(aa) * rr, cy + 0.3, cz + Math.sin(aa) * rr,
							0, -Math.cos(aa) * 0.3, 0.25, -Math.sin(aa) * 0.3, 0.6);
				}
				server.sendParticles(ParticleTypes.SCULK_SOUL, cx + aim.x * w * 0.4, cy + h * 0.9, cz + aim.z * w * 0.4,
						2, 0.4, 0.3, 0.4, 0.01);
			}
			default -> {
			}
		}
	}

	private static final net.minecraft.core.particles.DustParticleOptions WARNING_DUST =
			new net.minecraft.core.particles.DustParticleOptions(new org.joml.Vector3f(0.95f, 0.15f, 0.1f), 2.5f);

	private void leapWarningRing(ServerLevel server, Vec3 at, double radius) {
		int points = 16;
		for (int i = 0; i < points; i++) {
			double a = i / (double) points * Math.PI * 2;
			server.sendParticles(WARNING_DUST, at.x + Math.cos(a) * radius, at.y + 0.2, at.z + Math.sin(a) * radius,
					1, 0.0, 0.0, 0.0, 0.0);
		}
	}

	private void endAttack(Attack a) {
		if (a == Attack.CHARGE) {
			setAnim(Anim.NONE, 0);
		}
		attackCooldowns[a.ordinal()] = cooldownFor(a);
		globalAttackCooldown = TitanConfig.cooldowns().globalAttackDelay;
		activeAttack = Attack.NONE;
		attackResolved = false;
	}

	private int cooldownFor(Attack a) {
		var cd = TitanConfig.cooldowns();
		return switch (a) {
			case PUNCH -> cd.punch;
			case SWEEP -> cd.sweep;
			case STOMP -> cd.stomp;
			case SLAM -> cd.groundSlam;
			case SHOCKWAVE -> cd.shockwave;
			case GRAB -> cd.grab;
			case BOULDER -> cd.boulder;
			case CHARGE -> cd.charge;
			case LEAP -> cd.leap;
			case ROAR -> cd.roar;
			default -> 20;
		};
	}

	// ---------------- individual attacks ----------------

	/**
	 * v0.10.12: the Titan must not one-shot a healthy player. Every hit it lands on a player is
	 * capped at this fraction of their max health <em>before</em> armour is applied, so a full-diamond
	 * player takes a solid but survivable blow, and even an unarmoured one is left with a sliver
	 * rather than instantly dead. Non-players (its own thrown boulders, mobs) are unaffected.
	 */
	private static final double PLAYER_DAMAGE_CAP_FRACTION = 0.8;

	public static float scaleForPlayer(LivingEntity target, double amount) {
		if (target instanceof net.minecraft.world.entity.player.Player pl) {
			return (float) Math.min(amount, pl.getMaxHealth() * PLAYER_DAMAGE_CAP_FRACTION);
		}
		return (float) amount;
	}

	private void doPunch(ServerLevel server, LivingEntity target) {
		attackResolved = true;
		if (target == null || distanceTo(target) > TitanConfig.attacks().punchRange + 1.0) {
			return;
		}
		target.hurt(damageSources().mobAttack(this), scaleForPlayer(target, TitanConfig.attacks().punchDamage));
		Vec3 push = target.position().subtract(position()).normalize();
		target.setDeltaMovement(target.getDeltaMovement().add(push.x * 1.6, 0.4, push.z * 1.6));
		target.hurtMarked = true;
		server.sendParticles(ParticleTypes.CLOUD, target.getX(), target.getY() + 1, target.getZ(), 10, 0.3, 0.3, 0.3, 0.05);
		server.playSound(null, blockPosition(), SoundEvents.PLAYER_ATTACK_KNOCKBACK, SoundSource.HOSTILE, 2.0f, 0.5f);
	}

	/** Wide backhand: a ~180-degree forward arc, big damage-free-ish knockback, catches a whole group. */
	private void doSweep(ServerLevel server) {
		attackResolved = true;
		Vec3 facing = Vec3.directionFromRotation(0, getYRot());
		Vec3 center = position();
		double reach = TitanConfig.attacks().sweepRange + getBbWidth() * 0.5;
		for (LivingEntity le : nearbyLiving(reach)) {
			Vec3 flat = new Vec3(le.getX() - center.x, 0, le.getZ() - center.z);
			if (flat.lengthSqr() > 1.0e-4 && flat.normalize().dot(facing) < 0.0) {
				continue; // behind the swing
			}
			le.hurt(damageSources().mobAttack(this), scaleForPlayer(le, TitanConfig.attacks().sweepDamage));
			Vec3 push = flat.lengthSqr() < 1.0e-4 ? facing : flat.normalize();
			le.setDeltaMovement(push.x * 2.6, 0.55, push.z * 2.6);
			le.hurtMarked = true;
		}
		server.sendParticles(ParticleTypes.SWEEP_ATTACK, getX() + facing.x * getBbWidth() * 0.6,
				getY() + getBbHeight() * 0.5, getZ() + facing.z * getBbWidth() * 0.6,
				8, getBbWidth() * 0.6, 0.4, getBbWidth() * 0.6, 0.0);
		server.playSound(null, blockPosition(), SoundEvents.PLAYER_ATTACK_SWEEP, SoundSource.HOSTILE, 2.6f, 0.4f);
	}

	/** Ground shockwave: a big radial pulse that reaches far past Stomp/Slam and knocks everyone up. */
	private void doShockwave(ServerLevel server) {
		attackResolved = true;
		double r = TitanConfig.attacks().shockwaveRadius;
		Vec3 center = position();
		for (LivingEntity le : nearbyLiving(r)) {
			double d = le.position().distanceTo(center);
			float dmg = (float) (TitanConfig.attacks().shockwaveDamage * (1.0 - Math.min(0.6, d / r)));
			le.hurt(damageSources().mobAttack(this), scaleForPlayer(le, dmg));
			Vec3 push = le.position().subtract(center);
			push = push.lengthSqr() < 1.0e-4 ? Vec3.directionFromRotation(0, getYRot()) : push.normalize();
			le.setDeltaMovement(push.x * 1.3, 0.95, push.z * 1.3);
			le.hurtMarked = true;
		}
		for (int step = 1; step <= (int) r; step += 2) {
			for (int i = 0; i < 24; i++) {
				double a = i / 24.0 * Math.PI * 2;
				server.sendParticles(ParticleTypes.CLOUD, center.x + Math.cos(a) * step, center.y + 0.25,
						center.z + Math.sin(a) * step, 1, 0.0, 0.0, 0.0, 0.0);
			}
		}
		TitanTerrain.breakCluster(server, blockPosition(), Math.min(6.0, r * 0.4), false);
		server.sendParticles(ParticleTypes.EXPLOSION_EMITTER, getX(), getY(), getZ(), 1, 0, 0, 0, 0);
		server.sendParticles(new net.minecraft.core.particles.DustParticleOptions(
						new org.joml.Vector3f(1.0f, 0.82f, 0.15f), 2.6f),
				getX(), getY() + 1.0, getZ(), 40, getBbWidth() * 0.5, 0.6, getBbWidth() * 0.5, 0.1);
		server.playSound(null, blockPosition(), SoundEvents.WARDEN_SONIC_BOOM, SoundSource.HOSTILE, 3.0f, 0.5f);
	}

	private void doStomp(ServerLevel server) {
		attackResolved = true;
		Vec3 center = position();
		for (LivingEntity le : nearbyLiving(TitanConfig.attacks().stompRadius)) {
			le.hurt(damageSources().mobAttack(this), scaleForPlayer(le, TitanConfig.attacks().stompDamage));
			Vec3 push = le.position().subtract(center).normalize();
			le.setDeltaMovement(push.x * 1.4, 0.6, push.z * 1.4);
			le.hurtMarked = true;
		}
		TitanTerrain.breakCluster(server, blockPosition(), TitanConfig.attacks().stompRadius, false);
		server.sendParticles(ParticleTypes.EXPLOSION, getX(), getY(), getZ(), 1, 0, 0, 0, 0);
		server.sendParticles(new net.minecraft.core.particles.DustParticleOptions(
						new org.joml.Vector3f(1.0f, 0.82f, 0.15f), 2.6f),
				getX(), getY() + 0.5, getZ(), 30, getBbWidth() * 0.5, 0.4, getBbWidth() * 0.5, 0.08);
		server.playSound(null, blockPosition(), SoundEvents.GENERIC_EXPLODE.value(), SoundSource.HOSTILE, 2.5f, 0.6f);
	}

	private void doSlam(ServerLevel server) {
		attackResolved = true;
		Vec3 center = position();
		for (LivingEntity le : nearbyLiving(TitanConfig.attacks().slamRadius)) {
			le.hurt(damageSources().mobAttack(this), scaleForPlayer(le, TitanConfig.attacks().slamDamage));
			Vec3 push = le.position().subtract(center).normalize();
			le.setDeltaMovement(push.x * 1.2, 0.5, push.z * 1.2);
			le.hurtMarked = true;
		}
		TitanTerrain.breakCluster(server, blockPosition(), TitanConfig.attacks().slamRadius, false);
		server.sendParticles(ParticleTypes.EXPLOSION_EMITTER, getX(), getY(), getZ(), 1, 0, 0, 0, 0);
		server.sendParticles(new net.minecraft.core.particles.DustParticleOptions(
						new org.joml.Vector3f(1.0f, 0.82f, 0.15f), 2.6f),
				getX(), getY() + 0.5, getZ(), 40, getBbWidth() * 0.5, 0.5, getBbWidth() * 0.5, 0.1);
		server.playSound(null, blockPosition(), SoundEvents.GENERIC_EXPLODE.value(), SoundSource.HOSTILE, 3.0f, 0.4f);
	}

	private void doGrabAttempt(ServerLevel server, LivingEntity target) {
		attackResolved = true;
		if (!(target instanceof ServerPlayer player) || distanceTo(player) > 7.0) {
			return;
		}
		player.hurt(damageSources().mobAttack(this), scaleForPlayer(player, TitanConfig.attacks().grabDamage));
		grabbedPlayer = player.getUUID();
		grabTicksLeft = 30; // 1.5s hold
		setAnim(Anim.GRAB_THROW, 30 + 22); // lift to the shoulder, wind back, hurl (clip throws at tick 30)
		server.sendParticles(ParticleTypes.CLOUD, player.getX(), player.getY() + 1, player.getZ(), 10, 0.3, 0.3, 0.3, 0.02);
		server.playSound(null, blockPosition(), SoundEvents.PLAYER_HURT, SoundSource.HOSTILE, 2.0f, 0.4f);
	}

	private void tickGrab(ServerLevel server) {
		if (grabbedPlayer == null) {
			return;
		}
		ServerPlayer player = server.getServer().getPlayerList().getPlayer(grabbedPlayer);
		boolean stillValid = player != null && player.isAlive() && !player.isRemoved()
				&& player.level() == level() && distanceTo(player) < 16.0 && this.isAlive();
		if (!stillValid) {
			releaseGrab();
			return;
		}
		// Hold in the Titan's right fist. v0.14.4: moved out to where the animated arm actually holds it
		// (in front and to the right, just under shoulder height) -- the old spot was inside its own body.
		Vec3 look = Vec3.directionFromRotation(0, yBodyRot);
		Vec3 side = new Vec3(-look.z, 0, look.x);
		Vec3 hold = position().add(0, getBbHeight() * 0.62, 0).add(look.scale(getBbWidth() * 1.05))
				.add(side.scale(getBbWidth() * 0.5));
		player.teleportTo(hold.x, hold.y, hold.z);
		player.setDeltaMovement(Vec3.ZERO);
		player.fallDistance = 0;
		player.hurtMarked = true;

		grabTicksLeft--;
		if (grabTicksLeft <= 0) {
			player.hurt(damageSources().mobAttack(this), scaleForPlayer(player, TitanConfig.attacks().holdDamage));
			throwPlayer(server, player);
			releaseGrab();
		}
	}

	private void throwPlayer(ServerLevel server, ServerPlayer player) {
		double dist = TitanConfig.attacks().throwHorizontalMin
				+ getRandom().nextDouble() * (TitanConfig.attacks().throwHorizontalMax - TitanConfig.attacks().throwHorizontalMin);
		double up = TitanConfig.attacks().throwVerticalMin
				+ getRandom().nextDouble() * (TitanConfig.attacks().throwVerticalMax - TitanConfig.attacks().throwVerticalMin);
		Vec3 dir = player.position().subtract(position());
		Vec3 flat = new Vec3(dir.x, 0, dir.z);
		flat = flat.lengthSqr() < 1.0e-4 ? Vec3.directionFromRotation(0, getYRot()) : flat.normalize();
		// Convert the desired horizontal distance into a launch speed under gravity (v^2 = d*g / sin(2*45)).
		double speed = Math.sqrt(Math.max(1.0, dist * 0.07 * 2));
		player.setDeltaMovement(flat.x * speed * 0.35, up * 0.11, flat.z * speed * 0.35);
		player.hurtMarked = true;
		player.hasImpulse = true;
		player.connection.send(new net.minecraft.network.protocol.game.ClientboundSetEntityMotionPacket(player));
		player.hurt(damageSources().mobAttack(this), scaleForPlayer(player, TitanConfig.attacks().throwDamage));
		server.playSound(null, blockPosition(), SoundEvents.PLAYER_ATTACK_KNOCKBACK, SoundSource.HOSTILE, 2.5f, 0.4f);
	}

	/** Release paths: end-of-hold throw, Titan death, player death, disconnect, dimension change. */
	public void releaseGrab() {
		grabbedPlayer = null;
		grabTicksLeft = 0;
	}

	public boolean isGrabbing(UUID playerId) {
		return playerId.equals(grabbedPlayer);
	}

	/**
	 * Test/debug: start attack {@code name} (an {@code Attack} constant, e.g. "LEAP", "ROAR") against the current
	 * target right now, ignoring cooldowns and range checks. {@code skipWindup} resolves it on the next tick.
	 * Returns false for an unknown name or when no server level is available.
	 */
	public boolean debugBeginAttack(String name, boolean skipWindup) {
		if (!(level() instanceof ServerLevel server)) {
			return false;
		}
		Attack a;
		try {
			a = Attack.valueOf(name);
		} catch (IllegalArgumentException e) {
			return false;
		}
		if (a == Attack.NONE) {
			return false;
		}
		LivingEntity t = getTarget();
		beginAttack(server, a, t != null ? t : this);
		if (skipWindup) {
			attackTicks = 1;
		}
		return true;
	}

	public boolean isAttacking() {
		return activeAttack != Attack.NONE;
	}

	/** Test/debug (v0.14.20): play a body animation with none of its gameplay ({@code duration} 0 = held). */
	public void debugPlayAnim(Anim anim, int duration) {
		setAnim(anim, duration);
	}

	private void doBoulder(ServerLevel server, LivingEntity target) {
		attackResolved = true;
		if (target == null) {
			return;
		}
		var ground = server.getBlockState(blockPosition().below());
		TitanBoulderEntity boulder = new TitanBoulderEntity(server, this, TitanBoulderEntity.itemForGround(ground));
		// v0.14.4: released from above the head and a little forward, where the throw animation's hands are.
		Vec3 from = position().add(0, getBbHeight() * 0.8, 0)
				.add(Vec3.directionFromRotation(0, yBodyRot).scale(getBbWidth() * 0.5));
		// Lead the target's current velocity a little -- a simple, dodgeable prediction.
		Vec3 aim = target.position().add(target.getDeltaMovement().scale(8)).subtract(from);
		double dist = aim.length();
		boulder.setPos(from.x, from.y, from.z);
		float velocity = (float) Math.min(2.2, 0.9 + dist * 0.03);
		boulder.shoot(aim.x, aim.y + dist * 0.08, aim.z, velocity, 2.0f);
		server.addFreshEntity(boulder);
		server.sendParticles(ParticleTypes.POOF, from.x, from.y, from.z, 20, 0.4, 0.2, 0.4, 0.05);
		server.playSound(null, blockPosition(), SoundEvents.GENERIC_EXPLODE.value(), SoundSource.HOSTILE, 1.5f, 1.2f);
	}

	private void tickCharge(ServerLevel server) {
		// First tick of the run (the 20-tick wind-up has just finished): re-lock the charge line onto
		// where the target actually is NOW, so a player who side-stepped during the wind-up is still
		// chased rather than the Titan barrelling at their old position. `attackResolved` doubles as the
		// "charge has launched" flag here (CHARGE never uses it for anything else).
		if (!attackResolved) {
			attackResolved = true;
			LivingEntity t = getTarget();
			if (t != null && t.isAlive()) {
				Vec3 d = new Vec3(t.getX() - getX(), 0, t.getZ() - getZ());
				if (d.lengthSqr() > 1.0e-4) {
					chargeDirection = d.normalize();
				}
			}
			server.playSound(null, blockPosition(), SoundEvents.RAVAGER_ROAR, SoundSource.HOSTILE, 3.5f, 0.4f);
		}
		// chargeSpeed is already in blocks/tick -- apply it straight to the velocity. (The old code
		// multiplied it by 20, launching the Titan ~7 blocks/tick: it crossed the whole charge distance
		// in a couple of ticks, usually clipping a wall and ending instantly -- "the charge is broken".)
		double speed = TitanConfig.stats().chargeSpeed;
		setDeltaMovement(chargeDirection.x * speed, getDeltaMovement().y, chargeDirection.z * speed);
		hasImpulse = true;
		chargeDistanceLeft -= speed;
		TitanTerrain.breakAlongPath(server, position(), position().add(chargeDirection.scale(2)), getBbWidth());
		if (server.getGameTime() % 3 == 0) {
			server.sendParticles(ParticleTypes.CLOUD, getX(), getY(), getZ(), 3, getBbWidth() * 0.3, 0.1, getBbWidth() * 0.3, 0.0);
		}

		boolean hitSomething = false;
		for (LivingEntity le : nearbyLiving(getBbWidth() * 0.6 + 1.0)) {
			le.hurt(damageSources().mobAttack(this), scaleForPlayer(le, TitanConfig.attacks().chargeDamage));
			double throwDist = TitanConfig.attacks().chargeThrowMin
					+ getRandom().nextDouble() * (TitanConfig.attacks().chargeThrowMax - TitanConfig.attacks().chargeThrowMin);
			Vec3 push = chargeDirection.scale(throwDist * 0.12).add(0, 0.5, 0);
			le.setDeltaMovement(push);
			le.hurtMarked = true;
			hitSomething = true;
		}
		if (hitSomething || chargeDistanceLeft <= 0 || horizontalCollision) {
			setDeltaMovement(0, getDeltaMovement().y, 0);
			endAttack(Attack.CHARGE);
		}
	}

	/** Every player the Titan can hurt within {@code radius} of its bounding box. v0.14.4: creative and
	 *  spectator players are skipped (they used to still be flung around by the knockback). */
	private java.util.List<LivingEntity> nearbyLiving(double radius) {
		return level().getEntitiesOfClass(LivingEntity.class, getBoundingBox().inflate(radius),
				le -> le != this && isValidTarget(le));
	}

	private int countValidPlayersWithin(double radius) {
		if (!(level() instanceof ServerLevel server)) {
			return 0;
		}
		int n = 0;
		for (ServerPlayer p : server.players()) {
			if (isValidTarget(p) && distanceToSqr(p) <= radius * radius) {
				n++;
			}
		}
		return n;
	}

	// ---------------- v0.14.4 Leaping Slam ----------------

	/**
	 * Leaping Slam. After the 2 s crouch (red warning ring on the target's spot), the Titan launches on a
	 * scripted arc -- its velocity is set every tick to follow the parabola, so an 18-block body lands where it
	 * meant to rather than wherever vanilla drag/gravity would drop it -- onto the target's position at launch.
	 * Landing crushes everyone under it, then a shockwave ring travels outward along the ground: anyone standing
	 * on the ground when the ring passes is hit and thrown, anyone mid-jump is not.
	 */
	private void tickLeap(ServerLevel server) {
		var atk = TitanConfig.attacks();
		if (leapPhase == 0) {
			LivingEntity t = getTarget();
			Vec3 facing = Vec3.directionFromRotation(0, getYRot());
			Vec3 dest = t != null && t.isAlive() ? t.position() : position().add(facing.scale(atk.leapMinDistance));
			Vec3 flat = new Vec3(dest.x - getX(), 0, dest.z - getZ());
			double d = flat.length();
			if (d > atk.leapMaxDistance) {
				flat = flat.scale(atk.leapMaxDistance / d);
				d = atk.leapMaxDistance;
			}
			leapFrom = position();
			leapTo = new Vec3(getX() + flat.x, dest.y, getZ() + flat.z);
			leapFlightTicks = (int) Mth.clamp(18 + d * 0.6, 20, 40);
			leapApex = 7.0 + d * 0.2;
			leapTick = 0;
			leapPhase = 1;
			faceDirection(flat);
			setAnim(Anim.LEAP_AIR, 0);
			server.playSound(null, blockPosition(), SoundEvents.GENERIC_EXPLODE.value(), SoundSource.HOSTILE, 2.5f, 0.5f);
			server.sendParticles(ParticleTypes.EXPLOSION, getX(), getY() + 0.5, getZ(), 3, getBbWidth() * 0.4, 0.2,
					getBbWidth() * 0.4, 0.0);
			server.sendParticles(ParticleTypes.CLOUD, getX(), getY() + 0.2, getZ(), 30, getBbWidth() * 0.6, 0.1,
					getBbWidth() * 0.6, 0.08);
		}
		if (leapPhase == 1) {
			leapTick++;
			fallDistance = 0;
			if (leapTick % 3 == 0) {
				leapWarningRing(server, leapTo, getBbWidth() * 0.5 + atk.leapCrushRadius);
			}
			if (leapTick > leapFlightTicks / 2 && onGround() && getDeltaMovement().y <= 0.0) {
				leapLand(server); // came down early (a hill in the way) -- land here
				return;
			}
			if (leapTick <= leapFlightTicks) {
				Vec3 next = leapPoint(Math.min(1.0, leapTick / (double) leapFlightTicks));
				Vec3 step = next.subtract(position());
				double maxH = Math.max(1.0, leapFrom.distanceTo(leapTo) / leapFlightTicks * 1.6);
				double h = Math.sqrt(step.x * step.x + step.z * step.z);
				if (h > maxH) {
					step = new Vec3(step.x * maxH / h, step.y, step.z * maxH / h);
				}
				setDeltaMovement(step);
				hasImpulse = true;
				return;
			}
			// Past the arc's end: let gravity finish it if it's still above the ground (landing lower down).
			setDeltaMovement(0, Math.min(getDeltaMovement().y, -0.4), 0);
			if (onGround() || leapTick > leapFlightTicks + 40) {
				leapLand(server);
			}
			return;
		}
		// phase 2: the ring travels outward
		double prev = ringRadius;
		ringRadius += Math.max(0.1, atk.leapRingSpeed);
		for (LivingEntity le : level().getEntitiesOfClass(LivingEntity.class,
				new net.minecraft.world.phys.AABB(ringCenter, ringCenter).inflate(ringRadius + 1.0, 4.0, ringRadius + 1.0),
				le -> le != this && isValidTarget(le))) {
			double dx = le.getX() - ringCenter.x;
			double dz = le.getZ() - ringCenter.z;
			double r = Math.sqrt(dx * dx + dz * dz);
			double dy = le.getY() - ringCenter.y;
			boolean grounded = le.onGround() ? Math.abs(dy) <= 3.0 : dy < 0.5 && dy > -3.0;
			if (r <= prev || r > ringRadius || !grounded || ringHit.contains(le.getUUID())) {
				continue;
			}
			ringHit.add(le.getUUID());
			le.hurt(damageSources().mobAttack(this), scaleForPlayer(le, atk.leapRingDamage));
			Vec3 push = r < 1.0e-3 ? Vec3.directionFromRotation(0, getYRot()) : new Vec3(dx / r, 0, dz / r);
			le.setDeltaMovement(push.x * 0.9, 0.8, push.z * 0.9);
			le.hurtMarked = true;
		}
		int points = Math.min(28, Math.max(10, (int) (ringRadius * 2.0)));
		for (int i = 0; i < points; i++) {
			double a = (i + server.random.nextDouble() * 0.5) / points * Math.PI * 2;
			server.sendParticles(ParticleTypes.CLOUD, ringCenter.x + Math.cos(a) * ringRadius, ringCenter.y + 0.3,
					ringCenter.z + Math.sin(a) * ringRadius, 1, 0.0, 0.05, 0.0, 0.0);
		}
		if (ringRadius >= atk.leapRingRadius) {
			leapPhase = 0;
			endAttack(Attack.LEAP);
		}
	}

	/** The scripted arc: a straight line from take-off to landing plus a parabola of height {@link #leapApex}. */
	private Vec3 leapPoint(double s) {
		double x = Mth.lerp(s, leapFrom.x, leapTo.x);
		double z = Mth.lerp(s, leapFrom.z, leapTo.z);
		double y = Mth.lerp(s, leapFrom.y, leapTo.y) + 4.0 * leapApex * s * (1.0 - s);
		return new Vec3(x, y, z);
	}

	private void leapLand(ServerLevel server) {
		var atk = TitanConfig.attacks();
		leapPhase = 2;
		setDeltaMovement(0, getDeltaMovement().y, 0);
		ringCenter = position();
		ringRadius = getBbWidth() * 0.5 + atk.leapCrushRadius;
		ringHit.clear();
		for (LivingEntity le : nearbyLiving(atk.leapCrushRadius + 1.0)) {
			double dx = le.getX() - getX();
			double dz = le.getZ() - getZ();
			if (dx * dx + dz * dz > ringRadius * ringRadius) {
				continue;
			}
			ringHit.add(le.getUUID()); // crushed -- the ring won't hit them a second time
			le.hurt(damageSources().mobAttack(this), scaleForPlayer(le, atk.leapDamage));
			Vec3 push = new Vec3(dx, 0, dz);
			push = push.lengthSqr() < 1.0e-4 ? Vec3.directionFromRotation(0, getYRot()) : push.normalize();
			le.setDeltaMovement(push.x * 1.6, 0.6, push.z * 1.6);
			le.hurtMarked = true;
		}
		setAnim(Anim.LEAP_LAND, 34);
		// Floor-preserving (includeBelow = false) -- see the v0.9.17 "dug itself into a hole" fix.
		TitanTerrain.breakCluster(server, blockPosition(), Math.min(4.0, atk.leapCrushRadius), false);
		server.sendParticles(ParticleTypes.EXPLOSION_EMITTER, getX(), getY(), getZ(), 1, 0, 0, 0, 0);
		server.sendParticles(new net.minecraft.core.particles.DustParticleOptions(
						new org.joml.Vector3f(1.0f, 0.82f, 0.15f), 2.6f),
				getX(), getY() + 0.5, getZ(), 40, getBbWidth() * 0.6, 0.4, getBbWidth() * 0.6, 0.1);
		server.playSound(null, blockPosition(), SoundEvents.GENERIC_EXPLODE.value(), SoundSource.HOSTILE, 3.5f, 0.35f);
		server.playSound(null, blockPosition(), SoundEvents.WARDEN_SONIC_BOOM, SoundSource.HOSTILE, 2.5f, 0.6f);
	}

	/** Test/debug: was {@code id} hit by the last Leaping Slam's crush or ring? */
	public boolean debugHitByLeap(UUID id) {
		return ringHit.contains(id);
	}

	/** Test/debug: where the last Leaping Slam aimed and where it actually landed. */
	public String debugLeapInfo() {
		return "from=" + leapFrom + " to=" + leapTo + " landed=" + ringCenter + " flightTicks=" + leapFlightTicks
				+ " phase=" + leapPhase + " hits=" + ringHit.size();
	}

	// ---------------- v0.14.4 Grave Roar ----------------

	/**
	 * Grave Roar. After a 2 s inhale (souls drawn up into its chest) the Titan roars for
	 * {@link TitanConfig.Attacks#roarDurationTicks}: the release hits every player in {@code roarRadius} for a
	 * little damage and Slowness II and raises Husks out of the ground beside them (spread across the group,
	 * players it isn't chasing first -- so the undead pressure the people the Titan itself is ignoring), then a
	 * drag pulse every 5 ticks pulls everyone toward it. Kiting at range stops being free.
	 */
	private void tickRoar(ServerLevel server) {
		var atk = TitanConfig.attacks();
		roarTick++;
		java.util.List<LivingEntity> inRange = nearbyLiving(atk.roarRadius);
		inRange.removeIf(le -> le.distanceToSqr(this) > atk.roarRadius * atk.roarRadius);
		if (roarTick == 1) {
			server.playSound(null, blockPosition(), SoundEvents.WARDEN_ROAR, SoundSource.HOSTILE, 4.0f, 0.55f);
			server.playSound(null, blockPosition(), SoundEvents.ENDER_DRAGON_GROWL, SoundSource.HOSTILE, 3.0f, 0.5f);
			Vec3 mouth = position().add(0, getBbHeight() * 0.9, 0)
					.add(Vec3.directionFromRotation(0, yBodyRot).scale(getBbWidth() * 0.5));
			server.sendParticles(ParticleTypes.SONIC_BOOM, mouth.x, mouth.y, mouth.z, 1, 0, 0, 0, 0);
			for (LivingEntity le : inRange) {
				le.hurt(damageSources().mobAttack(this), scaleForPlayer(le, atk.roarDamage));
				le.addEffect(new net.minecraft.world.effect.MobEffectInstance(
						net.minecraft.world.effect.MobEffects.MOVEMENT_SLOWDOWN, Math.max(1, atk.roarSlownessTicks), 1), this);
			}
			summonMinions(server, inRange);
		}
		if (roarTick % 5 == 1) {
			double stop = getBbWidth() * 0.5 + 4.0;
			for (LivingEntity le : inRange) {
				Vec3 to = new Vec3(getX() - le.getX(), 0, getZ() - le.getZ());
				double d = to.length();
				if (d <= stop || d < 1.0e-3) {
					continue;
				}
				double s = atk.roarPullStrength * (0.6 + 0.4 * Math.min(1.0, d / atk.roarRadius));
				le.setDeltaMovement(to.x / d * s, 0.2, to.z / d * s);
				le.hurtMarked = true;
			}
			// A visible pressure wave rolling in from the edge.
			double r = atk.roarRadius * (1.0 - (roarTick % 20) / 20.0);
			for (int i = 0; i < 16; i++) {
				double a = i / 16.0 * Math.PI * 2;
				server.sendParticles(ParticleTypes.SCULK_SOUL, getX() + Math.cos(a) * r, getY() + 0.5,
						getZ() + Math.sin(a) * r, 1, 0, 0.05, 0, 0.0);
			}
		}
		if (roarTick >= Math.max(1, atk.roarDurationTicks)) {
			roarTick = 0;
			endAttack(Attack.ROAR);
		}
	}

	private void summonMinions(ServerLevel server, java.util.List<LivingEntity> victims) {
		var atk = TitanConfig.attacks();
		if (victims.isEmpty() || atk.roarSummonCount <= 0) {
			return;
		}
		int alive = server.getEntitiesOfClass(net.minecraft.world.entity.monster.Zombie.class,
				getBoundingBox().inflate(64.0), z -> z.isAlive() && z.getTags().contains(MINION_TAG)).size();
		int toSpawn = Math.min(atk.roarSummonCount, atk.roarMaxMinions - alive);
		if (toSpawn <= 0) {
			return;
		}
		// Players the Titan is NOT chasing come first: the Husks are its way of pressuring the rest of the group.
		java.util.List<LivingEntity> order = new java.util.ArrayList<>(victims);
		LivingEntity target = getTarget();
		order.sort((a, b) -> Boolean.compare(a == target, b == target));
		for (int i = 0; i < toSpawn; i++) {
			LivingEntity victim = order.get(i % order.size());
			BlockPos spot = findMinionSpot(server, victim.blockPosition());
			if (spot == null) {
				continue;
			}
			var husk = EntityType.HUSK.create(server);
			if (husk == null) {
				continue;
			}
			husk.moveTo(spot.getX() + 0.5, spot.getY(), spot.getZ() + 0.5, server.random.nextFloat() * 360.0f, 0.0f);
			husk.addTag(MINION_TAG);
			husk.setTarget(victim);
			server.addFreshEntity(husk);
			var ground = server.getBlockState(spot.below());
			server.sendParticles(new net.minecraft.core.particles.BlockParticleOption(ParticleTypes.BLOCK, ground),
					spot.getX() + 0.5, spot.getY() + 0.2, spot.getZ() + 0.5, 20, 0.4, 0.2, 0.4, 0.1);
			server.sendParticles(ParticleTypes.SOUL, spot.getX() + 0.5, spot.getY() + 0.5, spot.getZ() + 0.5,
					6, 0.3, 0.5, 0.3, 0.02);
			server.playSound(null, spot, SoundEvents.HUSK_AMBIENT, SoundSource.HOSTILE, 1.5f, 0.7f);
		}
	}

	/** A free, floored spot 3-6 blocks from {@code near} (searching a few blocks up and down), or null. */
	private BlockPos findMinionSpot(ServerLevel server, BlockPos near) {
		for (int attempt = 0; attempt < 8; attempt++) {
			double a = server.random.nextDouble() * Math.PI * 2;
			double r = 3.0 + server.random.nextDouble() * 3.0;
			int x = near.getX() + (int) Math.round(Math.cos(a) * r);
			int z = near.getZ() + (int) Math.round(Math.sin(a) * r);
			for (int dy = 3; dy >= -4; dy--) {
				BlockPos p = new BlockPos(x, near.getY() + dy, z);
				if (!server.getBlockState(p.below()).isFaceSturdy(server, p.below(), net.minecraft.core.Direction.UP)) {
					continue;
				}
				if (server.noCollision(EntityType.HUSK.getSpawnAABB(x + 0.5, p.getY(), z + 0.5))) {
					return p;
				}
			}
		}
		// Fallback: right where the player stands, if that's open.
		return server.noCollision(EntityType.HUSK.getSpawnAABB(near.getX() + 0.5, near.getY(), near.getZ() + 0.5))
				? near : null;
	}

	/** On the Titan's death its raised undead crumble with it. */
	private void clearMinions(ServerLevel server) {
		for (var z : server.getEntitiesOfClass(net.minecraft.world.entity.monster.Zombie.class,
				getBoundingBox().inflate(96.0), z -> z.getTags().contains(MINION_TAG))) {
			server.sendParticles(ParticleTypes.SOUL, z.getX(), z.getY() + 1.0, z.getZ(), 8, 0.3, 0.5, 0.3, 0.02);
			z.discard();
		}
	}

	// ---------------- death ----------------

	private int deathTicks = -1;

	/**
	 * v0.14.20: the death collapse is a 4.5 s animation (staggers back roaring, drops to its knees, sways, topples
	 * face-first) -- the body stays until it has finished. Was 30 ticks and no animation.
	 */
	public static final int DEATH_TICKS = 90;
	/** Clip tick at which the falling body hits the ground (generator constant DEATH_IMPACT). */
	public static final int DEATH_IMPACT_CLIP_TICK = 62;

	@Override
	public void die(DamageSource source) {
		if (deathTicks >= 0) {
			return;
		}
		releaseGrab();
		activeAttack = Attack.NONE;
		swatWindup = 0;
		leapPhase = 0;
		setDeltaMovement(Vec3.ZERO);
		setNoAi(true);
		deathTicks = DEATH_TICKS;
		if (level() instanceof ServerLevel server) {
			setAnim(Anim.DEATH, 0);
			clearMinions(server);
			threat.clear();
			server.playSound(null, blockPosition(), SoundEvents.RAVAGER_DEATH, SoundSource.HOSTILE, 4.0f, 0.4f);
			server.playSound(null, blockPosition(), SoundEvents.ZOMBIE_DEATH, SoundSource.HOSTILE, 4.0f, 0.3f);
			dropLoot(server, source);
		}
	}

	/** The facing direction the body falls along, and where its chest lands. */
	private Vec3 fallDirection() {
		return Vec3.directionFromRotation(0, yBodyRot);
	}

	/**
	 * Vanilla removes a dead mob 20 ticks after death; the Titan's collapse takes {@link #DEATH_TICKS}, and
	 * {@link #tick} removes it at the end. The client keeps vanilla's counter (it never removes anything itself).
	 */
	@Override
	protected void tickDeath() {
		if (deathTicks >= 0 && !level().isClientSide()) {
			if (deathTime < 20) {
				deathTime++;
			}
			return;
		}
		super.tickDeath();
	}

	/** Test: ticks left of the death collapse (-1 = not dying). */
	public int deathTicksLeft() {
		return deathTicks;
	}

	private void dropLoot(ServerLevel server, DamageSource source) {
		var lootTable = server.getServer().reloadableRegistries().getLootTable(
				net.minecraft.resources.ResourceKey.create(net.minecraft.core.registries.Registries.LOOT_TABLE,
						com.projecthero.mod.ProjectHeroMod.id("entities/titan")));
		LootParams.Builder params = new LootParams.Builder(server)
				.withParameter(LootContextParams.THIS_ENTITY, this)
				.withParameter(LootContextParams.ORIGIN, position())
				.withParameter(LootContextParams.DAMAGE_SOURCE, source)
				.withOptionalParameter(LootContextParams.ATTACKING_ENTITY, source.getEntity())
				.withOptionalParameter(LootContextParams.DIRECT_ATTACKING_ENTITY, source.getDirectEntity())
				.withLuck(0);
		lootTable.getRandomItems(params.create(LootContextParamSets.ENTITY), this.getLootTableSeed(), stack -> spawnAtLocation(stack));
	}

	@Override
	public void tick() {
		super.tick();
		if (deathTicks < 0) {
			return;
		}
		if (level() instanceof ServerLevel server) {
			int elapsed = DEATH_TICKS - deathTicks;
			Vec3 dir = fallDirection();
			if (elapsed == 26 + ANIM_TRANSITION) {
				// knees hit the ground
				server.sendParticles(ParticleTypes.CLOUD, getX(), getY() + 0.3, getZ(), 30, getBbWidth() * 0.5, 0.2,
						getBbWidth() * 0.5, 0.05);
				server.playSound(null, blockPosition(), SoundEvents.GENERIC_BIG_FALL, SoundSource.HOSTILE, 3.0f, 0.4f);
			}
			if (elapsed == DEATH_IMPACT_CLIP_TICK + ANIM_TRANSITION) {
				// the body slams down face-first along its facing: a line of dust and a boom
				for (int i = 2; i <= 16; i += 2) {
					Vec3 p = position().add(dir.scale(i));
					server.sendParticles(ParticleTypes.EXPLOSION, p.x, p.y + 0.5, p.z, 1, 0.8, 0.2, 0.8, 0.0);
					server.sendParticles(ParticleTypes.CLOUD, p.x, p.y + 0.3, p.z, 12, 1.8, 0.3, 1.8, 0.06);
				}
				server.playSound(null, blockPosition(), SoundEvents.GENERIC_EXPLODE.value(), SoundSource.HOSTILE, 3.0f, 0.35f);
			}
			if (deathTicks <= 12 && deathTicks % 3 == 0) {
				// crumbles to ash where it lies
				for (int i = 0; i <= 14; i += 2) {
					Vec3 p = position().add(dir.scale(i));
					server.sendParticles(ParticleTypes.LARGE_SMOKE, p.x, p.y + 1.0, p.z, 4, 1.5, 0.6, 1.5, 0.02);
					server.sendParticles(ParticleTypes.POOF, p.x, p.y + 1.0, p.z, 3, 1.5, 0.6, 1.5, 0.02);
				}
			}
		}
		deathTicks--;
		if (deathTicks == 0) {
			if (bossBar != null && level() instanceof ServerLevel server) {
				bossBar.clear(server);
			}
			remove(Entity.RemovalReason.KILLED);
		}
	}

	@Override
	public void remove(Entity.RemovalReason reason) {
		releaseGrab();
		if (bossBar != null && level() instanceof ServerLevel server) {
			bossBar.clear(server);
		}
		super.remove(reason);
	}

	@Override
	public void addAdditionalSaveData(CompoundTag tag) {
		super.addAdditionalSaveData(tag);
	}
}
