package com.projecthero.mod.client.horde;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;

import com.projecthero.mod.ProjectHeroMod;
import com.projecthero.mod.horde.entity.BroodQueen;

import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.resources.ResourceLocation;

import software.bernie.geckolib.cache.object.BakedGeoModel;
import software.bernie.geckolib.model.GeoModel;
import software.bernie.geckolib.renderer.GeoEntityRenderer;
import software.bernie.geckolib.renderer.layer.AutoGlowingGeoLayer;

/**
 * v0.14.16: renders the Brood Queen through GeckoLib. Her geo ({@code geo/brood_queen.geo.json}, generated by
 * {@code scratchpad/gen_brood_queen_v01416.js}) is authored at half size and doubled here -- on the main pass only,
 * since the glow layer re-renders inside the already-scaled stack. The glowmask keeps her ten eyes, the hourglass, the
 * egg sacs' veins and her fang tips burning in the dark. No vanilla tip-over on death: the death clip curls her up.
 */
public class BroodQueenRenderer extends GeoEntityRenderer<BroodQueen> {
	/** Model units are authored at 8 per block; the renderer doubles them to vanilla's 16. */
	public static final float MODEL_SCALE = 2.0f;

	public BroodQueenRenderer(EntityRendererProvider.Context context) {
		super(context, new Model());
		this.shadowRadius = 3.2f;
		addRenderLayer(new AutoGlowingGeoLayer<>(this));
	}

	static final class Model extends GeoModel<BroodQueen> {
		private static final ResourceLocation MODEL = ProjectHeroMod.id("geo/brood_queen.geo.json");
		private static final ResourceLocation TEXTURE = ProjectHeroMod.id("textures/entity/brood_queen.png");
		private static final ResourceLocation ANIMATION = ProjectHeroMod.id("animations/brood_queen.animation.json");

		@Override
		public ResourceLocation getModelResource(BroodQueen animatable) {
			return MODEL;
		}

		@Override
		public ResourceLocation getTextureResource(BroodQueen animatable) {
			return TEXTURE;
		}

		@Override
		public ResourceLocation getAnimationResource(BroodQueen animatable) {
			return ANIMATION;
		}
	}

	@Override
	public void preRender(PoseStack poseStack, BroodQueen animatable, BakedGeoModel model, MultiBufferSource bufferSource,
			VertexConsumer buffer, boolean isReRender, float partialTick, int packedLight, int packedOverlay, int colour) {
		super.preRender(poseStack, animatable, model, bufferSource, buffer, isReRender, partialTick, packedLight, packedOverlay, colour);
		if (!isReRender) {
			poseStack.scale(MODEL_SCALE, MODEL_SCALE, MODEL_SCALE);
		}
	}

	@Override
	protected float getDeathMaxRotation(BroodQueen animatable) {
		return 0.0f;
	}
}
