package com.projecthero.mod.client.sentinel;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;

import com.projecthero.mod.ProjectHeroMod;
import com.projecthero.mod.client.darkseid.BeamDraw;
import com.projecthero.mod.client.darkseid.EnergyTrailRenderer;
import com.projecthero.mod.sentinel.entity.MasterMoldEntity;
import com.projecthero.mod.sentinel.entity.SentinelDroneEntity;
import com.projecthero.mod.sentinel.entity.SentinelEntity;
import com.projecthero.mod.sentinel.entity.SentinelEntityTypes;
import com.projecthero.mod.sentinel.entity.SentinelAimedShot;
import com.projecthero.mod.sentinel.entity.SentinelBeamEntity;
import com.projecthero.mod.sentinel.entity.SentinelRobot;

import net.fabricmc.fabric.api.client.rendering.v1.EntityRendererRegistry;

import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.culling.Frustum;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.Vec3;

import software.bernie.geckolib.animatable.GeoEntity;
import software.bernie.geckolib.animation.AnimationState;
import software.bernie.geckolib.cache.object.GeoBone;
import software.bernie.geckolib.constant.DataTickets;
import software.bernie.geckolib.model.GeoModel;
import software.bernie.geckolib.model.data.EntityModelData;
import software.bernie.geckolib.renderer.GeoEntityRenderer;
import software.bernie.geckolib.renderer.layer.AutoGlowingGeoLayer;

/**
 * v0.15.1: the Sentinel Purge's renderers. All three robots are GeckoLib models generated by
 * {@code scratchpad/gen_sentinel_v0151.js} -- except the Sentinel, which since v0.15.3 is the user's Blockbench skin-rig
 * model ({@code scratchpad/gen_v0153_sentinel.js}); their eyes, emitters, thrusters and Master Mold's fabrication core
 * glow in the dark through their {@code _glowmask} textures. GeckoLib applies the SCALE attribute itself (Sentinel 1.75, Master
 * Mold 5.5), so nothing here rescales. The bolts use the Darkseid Raid's shared ribbon renderer; Master Mold's Purge Beam
 * is drawn from its synced beam state with the same two-pass glow/core geometry as the Omega Sweep.
 */
public final class SentinelRenderers {
	private SentinelRenderers() {
	}

	public static void initialize() {
		EntityRendererRegistry.register(SentinelEntityTypes.SENTINEL_DRONE, DroneRenderer::new);
		EntityRendererRegistry.register(SentinelEntityTypes.SENTINEL, SentinelRenderer::new);
		EntityRendererRegistry.register(SentinelEntityTypes.MASTER_MOLD, MasterMoldRenderer::new);
		EntityRendererRegistry.register(SentinelEntityTypes.SENTINEL_BEAM, EnergyTrailRenderer::new);
	}

	/** One geo/texture/animation triple, with the head following the gaze while the robot isn't mid-attack. */
	static class Model<T extends Mob & GeoEntity> extends GeoModel<T> {
		private final ResourceLocation model;
		private final ResourceLocation texture;
		private final ResourceLocation animation;

		Model(String name) {
			this.model = ProjectHeroMod.id("geo/" + name + ".geo.json");
			this.texture = ProjectHeroMod.id("textures/entity/" + name + ".png");
			this.animation = ProjectHeroMod.id("animations/" + name + ".animation.json");
		}

		@Override
		public ResourceLocation getModelResource(T animatable) {
			return model;
		}

		@Override
		public ResourceLocation getTextureResource(T animatable) {
			return texture;
		}

		@Override
		public ResourceLocation getAnimationResource(T animatable) {
			return animation;
		}

		/** Whether the head may turn to follow the gaze right now. */
		boolean headFree(T animatable) {
			return !animatable.isDeadOrDying();
		}

		/**
		 * Yaw only, and set (not added): the idle clip only nudges the head, and adding to a bone's rotation every frame
		 * accumulates whenever a clip stops touching it (the Hulk lesson).
		 */
		@Override
		public void setCustomAnimations(T animatable, long instanceId, AnimationState<T> state) {
			super.setCustomAnimations(animatable, instanceId, state);
			if (!headFree(animatable)) {
				return;
			}
			GeoBone head = getAnimationProcessor().getBone("head");
			EntityModelData data = state.getData(DataTickets.ENTITY_MODEL_DATA);
			if (head != null && data != null) {
				head.setRotY(Mth.clamp(data.netHeadYaw(), -50f, 50f) * Mth.DEG_TO_RAD);
			}
		}
	}

	// ---------------------------------------------------------------- the Drone

	static final class DroneRenderer extends GeoEntityRenderer<SentinelDroneEntity> {
		DroneRenderer(EntityRendererProvider.Context context) {
			super(context, new Model<>("sentinel_drone") {
				@Override
				boolean headFree(SentinelDroneEntity animatable) {
					return false; // no head bone: the whole pod turns with the body
				}
			});
			this.shadowRadius = 0.4f;
			addRenderLayer(new AutoGlowingGeoLayer<>(this));
		}

		@Override
		protected float getDeathMaxRotation(SentinelDroneEntity animatable) {
			return 0.0f; // the death clip spins it
		}

		@Override
		public void render(SentinelDroneEntity entity, float yaw, float partialTick, PoseStack poseStack, MultiBufferSource buffers, int light) {
			super.render(entity, yaw, partialTick, poseStack, buffers, light);
			renderShot(entity, partialTick, poseStack, buffers, entityRenderDispatcher.camera.getPosition());
		}

		@Override
		public boolean shouldRender(SentinelDroneEntity entity, Frustum frustum, double camX, double camY, double camZ) {
			return super.shouldRender(entity, frustum, camX, camY, camZ) || shotVisible(entity, frustum);
		}
	}

	// ---------------------------------------------------------------- the Sentinel

	static final class SentinelRenderer extends GeoEntityRenderer<SentinelEntity> {
		SentinelRenderer(EntityRendererProvider.Context context) {
			super(context, new Model<>("sentinel") {
				@Override
				boolean headFree(SentinelEntity animatable) {
					return !animatable.isDeadOrDying() && !animatable.isBusy();
				}

				@Override
				public void setCustomAnimations(SentinelEntity animatable, long instanceId, AnimationState<SentinelEntity> state) {
					super.setCustomAnimations(animatable, instanceId, state);
					// the boot thruster flame bones only show in flight (v0.15.3: the user's model gives them no cubes -- they
					// stay as locators, and the flames themselves are the server's particles)
					boolean flames = animatable.isFlying() && !animatable.isDeadOrDying();
					for (String name : new String[] { "right_flame", "left_flame" }) {
						GeoBone flame = getAnimationProcessor().getBone(name);
						if (flame != null) {
							flame.setHidden(!flames);
						}
					}
				}
			});
			this.shadowRadius = 0.9f;
			addRenderLayer(new AutoGlowingGeoLayer<>(this));
		}

		@Override
		protected float getDeathMaxRotation(SentinelEntity animatable) {
			return 0.0f; // the death clip kneels it and crashes it forward
		}

		@Override
		public void render(SentinelEntity entity, float yaw, float partialTick, PoseStack poseStack, MultiBufferSource buffers, int light) {
			super.render(entity, yaw, partialTick, poseStack, buffers, light);
			renderShot(entity, partialTick, poseStack, buffers, entityRenderDispatcher.camera.getPosition());
		}

		@Override
		public boolean shouldRender(SentinelEntity entity, Frustum frustum, double camX, double camY, double camZ) {
			return super.shouldRender(entity, frustum, camX, camY, camZ) || shotVisible(entity, frustum);
		}
	}

	// ---------------------------------------------------------------- v0.15.3: aimed-shot telegraph and beam

	/**
	 * A robot's {@link SentinelAimedShot}: while tracking, a thin dim aiming line from the emitter; once locked, a brighter,
	 * fast-pulsing line with a white core (the "move now" warning); on the shot, the full beam with a hot core. Same
	 * two-pass glow/core geometry as Master Mold's Purge Beam (all glow first, then all core).
	 */
	static void renderShot(SentinelRobot entity, float partialTick, PoseStack poseStack, MultiBufferSource buffers, Vec3 camera) {
		int state = entity.shotState();
		if (state == SentinelAimedShot.STATE_OFF || entity.isDeadOrDying()) {
			return;
		}
		SentinelBeamEntity.Kind kind = entity.shotKind();
		Vec3 base = new Vec3(Mth.lerp(partialTick, entity.xo, entity.getX()), Mth.lerp(partialTick, entity.yo, entity.getY()),
				Mth.lerp(partialTick, entity.zo, entity.getZ()));
		Vec3 start = entity.shotFrom().subtract(base);
		Vec3 end = entity.shotTo().subtract(base);
		if (end.subtract(start).lengthSqr() < 1.0e-4) {
			return;
		}
		Vec3 cam = camera.subtract(base);
		PoseStack.Pose pose = poseStack.last();
		float t = entity.tickCount + partialTick;
		float w = kind.beamWidth();
		int glowColor = kind.glowColor();
		VertexConsumer glow = buffers.getBuffer(RenderType.debugQuads());
		switch (state) {
			case SentinelAimedShot.STATE_TRACK -> {
				float flicker = 0.35f + 0.1f * Mth.sin(t * 0.9f);
				BeamDraw.beam(glow, true, pose, start, end, cam, w * 0.22f, glowColor, flicker);
			}
			case SentinelAimedShot.STATE_LOCK -> {
				float pulse = 0.55f + 0.45f * Math.abs(Mth.sin(t * 1.6f));
				BeamDraw.beam(glow, true, pose, start, end, cam, w * 0.45f, glowColor, pulse);
				BeamDraw.beam(glow, true, pose, start, start.add(end.subtract(start).normalize().scale(0.6)), cam, w * 1.4f, glowColor, pulse);
				VertexConsumer hot = buffers.getBuffer(RenderType.lightning());
				BeamDraw.beam(hot, false, pose, start, end, cam, w * 0.45f, 0xFFFFFF, pulse * 0.7f);
			}
			default -> {
				float flicker = 0.85f + 0.15f * Mth.sin(t * 1.9f);
				BeamDraw.beam(glow, true, pose, start, end, cam, w * 1.6f, glowColor, flicker);
				BeamDraw.beam(glow, true, pose, start, start.add(end.subtract(start).normalize().scale(0.8)), cam, w * 3.0f, glowColor, flicker * 0.8f);
				VertexConsumer hot = buffers.getBuffer(RenderType.lightning());
				BeamDraw.beam(hot, false, pose, start, end, cam, w * 1.6f, kind.hotColor(), flicker);
			}
		}
	}

	/** Don't cull an aiming line or beam just because the robot's box is off-screen. */
	static boolean shotVisible(SentinelRobot entity, Frustum frustum) {
		if (entity.shotState() == SentinelAimedShot.STATE_OFF) {
			return false;
		}
		Vec3 a = entity.shotFrom();
		Vec3 b = entity.shotTo();
		return frustum.isVisible(new AABB(a, b).inflate(0.5));
	}

	// ---------------------------------------------------------------- Master Mold

	static final class MasterMoldRenderer extends GeoEntityRenderer<MasterMoldEntity> {
		MasterMoldRenderer(EntityRendererProvider.Context context) {
			super(context, new Model<>("master_mold") {
				@Override
				boolean headFree(MasterMoldEntity animatable) {
					return !animatable.isDeadOrDying() && !animatable.isBusy();
				}
			});
			this.shadowRadius = 2.6f;
			addRenderLayer(new AutoGlowingGeoLayer<>(this));
		}

		@Override
		protected float getDeathMaxRotation(MasterMoldEntity animatable) {
			return 0.0f;
		}

		@Override
		public void render(MasterMoldEntity entity, float yaw, float partialTick, PoseStack poseStack, MultiBufferSource buffers, int light) {
			super.render(entity, yaw, partialTick, poseStack, buffers, light);
			byte beam = entity.beamState();
			if (beam != 0 && !entity.isDeadOrDying()) {
				renderBeam(entity, beam, partialTick, poseStack, buffers);
			}
		}

		private void renderBeam(MasterMoldEntity entity, byte beam, float partialTick, PoseStack poseStack, MultiBufferSource buffers) {
			Vec3 base = new Vec3(Mth.lerp(partialTick, entity.xo, entity.getX()), Mth.lerp(partialTick, entity.yo, entity.getY()),
					Mth.lerp(partialTick, entity.zo, entity.getZ()));
			Vec3 cam = entityRenderDispatcher.camera.getPosition().subtract(base);
			PoseStack.Pose pose = poseStack.last();
			Vec3 start = entity.beamOrigin().subtract(entity.position());
			Vec3 end = entity.beamTarget().subtract(base);
			float t = entity.tickCount + partialTick;
			float flicker = 0.85f + 0.15f * Mth.sin(t * 1.9f);
			float width = beam == 2 ? 0.7f : 0.05f;
			int glowColor = beam == 2 ? 0xE030C0 : 0xFF3060;
			int coreColor = beam == 2 ? 0xFFE0FF : 0xFF8090;
			// all glow first, then all core -- interleaving the two buffers crashes (see BeamDraw#beam)
			VertexConsumer glow = buffers.getBuffer(RenderType.debugQuads());
			BeamDraw.beam(glow, true, pose, start, end, cam, width, glowColor, flicker * (beam == 2 ? 1.0f : 0.6f));
			if (beam == 2) {
				BeamDraw.beam(glow, true, pose, start.add(0, -0.01, 0), start.add(end.subtract(start).normalize().scale(1.5)), cam, width * 2.2f,
						glowColor, flicker * 0.8f);
			}
			VertexConsumer hot = buffers.getBuffer(RenderType.lightning());
			BeamDraw.beam(hot, false, pose, start, end, cam, width, coreColor, flicker);
		}

		/** Don't cull the beam just because the body's box is off-screen. */
		@Override
		public boolean shouldRender(MasterMoldEntity entity, Frustum frustum, double camX, double camY, double camZ) {
			if (super.shouldRender(entity, frustum, camX, camY, camZ)) {
				return true;
			}
			if (entity.beamState() == 0) {
				return false;
			}
			Vec3 tip = entity.beamTarget();
			return frustum.isVisible(entity.getBoundingBox().minmax(new AABB(tip, tip)).inflate(1.0));
		}
	}
}
