// v0.13.15 docs: CurseForge description (mixed CRLF/LF -- edit in place per line) + HULK_REFERENCE.md section.
const fs = require('fs');
function edit(file, pairs) {
  let s = fs.readFileSync(file, 'utf8');
  for (const [a, b] of pairs) {
    // tolerate either line ending inside the matched block
    const re = new RegExp(a.split('\n').map(x => x.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('\\r?\\n'));
    if (!re.test(s)) throw new Error(file + ': missing ' + a.slice(0, 60));
    s = s.replace(re, b);
  }
  fs.writeFileSync(file, s);
}

edit('docs/CURSEFORGE_DESCRIPTION.md', [
  ['- **Rage (0-100):** fills when you are hurt and when you fight; at **75** press **H** to let the Hulk out, at **100** he\n  comes out on his own. As the Hulk rage burns down, but every hit you take feeds it back.',
   '- **Rage (0-100):** fills when you are hurt and when you fight; past **75** Banner starts pouring off green gamma. At\n  **75** press **H** to let the Hulk out -- a quick change, and he is **yours to command**. At **100** he comes out on his\n  own: Banner **drops to his knees** clutching his head and the Hulk slowly takes him over, then rises roaring. The Hulk\n  **phases onto you as you grow** and back off as you shrink. As the Hulk rage burns down, but every hit you take feeds it back.'],
  ['- **Keep control:** stop hitting things and the Hulk starts to take over -- answer the key prompts or he goes on a',
   '- **Keep control:** only a Hulk who came out **on his own** fights you -- stop hitting things and he starts to take over;\n  answer the key prompts or he goes on a'],
]);

edit('docs/HULK_REFERENCE.md', [
  ['| - | Overhaul: new kit, passives, death save, riding, calm minigame, control / rampage, HUD | v0.13.14 |',
   '| - | Overhaul: new kit, passives, death save, riding, calm minigame, control / rampage, HUD | v0.13.14 |\n| - | Willing vs unwilling change, kneeling change, cross-fade, rage glow, Banner HUD | v0.13.15 |'],
  ['## v0.13.14 overhaul',
   '## v0.13.15: willing and unwilling changes\n\n' +
   '- **Willing** (H at 75+): `Hulk.transform(p, false)` -- 30-tick growth, `HulkState.Combat.unwilling = false`, and\n' +
   '  `HulkControl.tick` does nothing for him: no prompts, no rampage, ever.\n' +
   '- **Unwilling** (rage 100, or the death save): `transform(p, true)` sets `unwilling`. `Hulk.changing` is true for\n' +
   '  `HulkConfig.FORCED_CHANGE_TICKS` (20 kneel + 60 growth + 24 rise): movement / jump multiplied to 0 (transient\n' +
   '  modifiers, so the client stops too), abilities refused (`HulkAbilities.canAct`), melee refused, all damage vetoed\n' +
   '  (`HulkDamage`), no calm-down. Growth waits for the kneel, then runs over 60 ticks. Roar + shake at the rise\n' +
   '  (`Hulk.roar`); heartbeats / tearing sounds / gamma while kneeling (`tickForcedChange`). Control grace starts when the\n' +
   '  change ends.\n' +
   '- **Cross-fade**: `Hulk.visibility(player, partial)` 0..1 on the growth clock. `PlayerRendererHulkMixin` lets vanilla\n' +
   '  draw Banner first (see-through + no render layers via `client/mixin/LivingEntityHulkFadeMixin`), then draws the Hulk on\n' +
   '  top at RETURN (`HulkRenderer.renderFaded`: `entityTranslucent` + alpha in `getRenderColor`); solid = HEAD-cancel as\n' +
   '  before. **Draw order matters**: drawing the GeckoLib Hulk *before* the vanilla player (at HEAD) visibly sheared\n' +
   '  Banner\'s model mid-fade -- keep the fading Hulk after vanilla. During the unwilling change the Hulk is drawn from tick\n' +
   '  0 at alpha 0 so its GeckoLib clip starts in sync.\n' +
   '- **Kneel**: Banner = `client/hulk/HulkPose` (vanilla model, from `HumanoidModelMixin`: hips down 8 px, legs folded\n' +
   '  back 1.23 rad, 0.38 rad hunch from the hips, hands on the head, a shiver); Hulk = `animation.hulk.transform_forced`\n' +
   '  (5.2 s, generated by `scratchpad/add_hulk_forced_anim_v01315.js`: same kneel, fists into the ground, rise, roar).\n' +
   '- **Rage glow**: Banner above 75 -- `Hulk.rageGlow`, green dust every 3 ticks, denser and with a faster heartbeat toward 100.\n' +
   '- **HUD**: Banner shows "Rage N%" + bar (throbbing past 75), or "Exhausted Ns" with the bar running the timer down;\n' +
   '  "THE HULK IS TAKING OVER..." + progress mid-screen during the unwilling change.\n' +
   '- Verified in-client with the screenshot harness (`scratchpad/V01315DebugHarness.java.txt` + the temporary\n' +
   '  `HarnessCameraMixin.java.txt` camera orbit -- a detached camera entity hides the local player).\n\n' +
   '## v0.13.14 overhaul'],
  ['- Tests: `HulkGameTests` (28).', '- Tests: `HulkGameTests` (28; 31 as of v0.13.15).'],
]);
console.log('docs ok');
