// v0.12.25 docs updates. Run from the repo root.
const fs = require('fs');
function edit(file, fn) { const s = fs.readFileSync(file, 'utf8'); const o = fn(s); if (o === s) throw new Error('no change: ' + file); fs.writeFileSync(file, o); }
function rep(s, a, b) { if (!s.includes(a)) throw new Error('missing: ' + a.slice(0, 60)); return s.replace(a, b); }

edit('docs/CURSEFORGE_DESCRIPTION.md', s => {
  s = rep(s, '**Adamantium Serum** (4 diamonds, 2 netherite ingots, 2 blaze powder, a golden apple) and use it: your\nregenerative mutation is consumed and rebuilt as Wolverine.',
    '**Wolverine Serum** (4 diamonds, 2 netherite ingots, 2 blaze powder, a golden apple) and use it: your\nregenerative mutation is consumed and rebuilt as Wolverine — with no claws yet. Craft a **Bone Claw Serum** for\nthree natural bone claws a hand (weaker: 9 bare-handed), then an **Adamantium Serum** (hold to use, 3 s) to\nturn them into full-strength adamantium claws and unlock Adamantium Execution.');
  s = rep(s, '- **Adamantium claws:** three curved blades per hand', '- **Bone → Adamantium claws:** three curved blades per hand');
  return s;
});
edit('docs/curseforge_description.html', s => {
  s = rep(s, 'craft an <strong>Adamantium Serum</strong> (4 diamonds, 2 netherite ingots, 2 blaze powder, a\ngolden apple) and use it: the mutation is consumed and rebuilt as Wolverine.</p>',
    'craft a <strong>Wolverine Serum</strong> (4 diamonds, 2 netherite ingots, 2 blaze powder, a\ngolden apple) and use it: the mutation is consumed and rebuilt as Wolverine &mdash; with no claws yet. A\n<strong>Bone Claw Serum</strong> grows natural bone claws (weaker); a hold-to-use <strong>Adamantium Serum</strong>\nupgrades them to adamantium and unlocks Adamantium Execution.</p>');
  s = rep(s, '<li><strong>Adamantium claws:</strong>', '<li><strong>Bone &rarr; Adamantium claws:</strong>');
  return s;
});
edit('docs/WOLVERINE_REFERENCE.md', s => {
  s = rep(s, '2. Craft an **Adamantium Serum** (`DND / BGB / DND`', '2. Craft a **Wolverine Serum** (`DND / BGB / DND`');
  s += `
## v0.12.25 — claw progression

You no longer start with claws: **Wolverine → Bone Claw Serum → Bone Claws → Adamantium Serum → Adamantium Claws.**

- **Items.** \`wolverine_serum\` (the old ascension item, renamed, same recipe), \`bone_claw_serum\`
  (\`BNB / GLG / BQB\`: bone block, netherite scrap, gold ingot, glass bottle, ghast tear), \`adamantium_serum\`
  (\`NDN / GSG / NLN\`: netherite ingot, diamond block, gold block, nether star, glass bottle). The Bone Claw Serum
  is instant and only works on a Wolverine with no claws; the Adamantium Serum is a 3-second hold-to-use
  (\`AdamantiumSerumItem\`: slows + regenerates you, cancelling early consumes nothing, upgrade + consumption happen
  only in \`finishUsingItem\` on the server) and only works on a Wolverine with Bone Claws. Every refusal has a message.
- **State.** \`data/ClawTier\` (NONE / BONE / ADAMANTIUM) in \`WolverineState.clawTier\` (persistent, copy-on-death,
  synced). A save from before v0.12.25 has no tier and loads as ADAMANTIUM so existing Wolverines keep their claws;
  a fresh ascension starts at NONE. \`Wolverine.unlockBoneClaws\` / \`upgradeToAdamantium\` / \`setClawTier\` are the only mutators.
- **Numbers** (\`WolverineConfig\`): bone bare-hand 9, Slash 15, Cross 10+10, Dash 10, Frenzy 6; adamantium is the
  original kit (12 / 18 / 12+12 / 12 / 8). Adamantium Execution needs ADAMANTIUM ("Adamantium Claws required."); H and every claw move
  say "Bone Claws required." while the tier is NONE. Berserker Rage needs no claws. The key layout is unchanged.
- **Models.** \`WolverineClawsModel.createBoneLayer()\` — a second code-built model (layer \`wolverine_bone_claws\`,
  texture \`textures/entity/wolverine_bone_claws.png\`, generated by \`scratchpad/gen_wolverine_bone.js\`): three thicker,
  shorter, more curved five-segment blades per hand, outer two fanned. The layer, the first-person renderer and the
  extension animation all pick model + texture from the tier; exactly one model is ever drawn. No GeckoLib/animation
  file is used — the existing 6-tick extend/retract runs on both.
- **Commands.** \`/wolverine claws tier none|bone|adamantium\` (op); \`grant\` starts a Wolverine at NONE.
`;
  return s;
});
