// v0.14.3: the Power Ring item as a real 3D model -- an octagonal band standing upright, a dark bezel and a glowing gem.
const fs = require('fs');
const UV = { band: [0, 0, 16, 4], hi: [0, 4, 16, 6], bezel: [0, 6, 16, 10], gem: [4, 10, 12, 16] };
function el(name, from, to, uvKey) {
	const uv = UV[uvKey];
	const faces = {};
	for (const f of ['north', 'south', 'east', 'west', 'up', 'down']) {
		faces[f] = { uv, texture: '#t' };
	}
	return { name, from, to, faces };
}
const Z0 = 6.5, Z1 = 9.5;
const elements = [
	el('band_bottom', [5, 1, Z0], [11, 2.5, Z1], 'band'),
	el('band_top', [5, 9.5, Z0], [11, 11, Z1], 'band'),
	el('band_left', [3, 3.5, Z0], [4.5, 8.5, Z1], 'band'),
	el('band_right', [11.5, 3.5, Z0], [13, 8.5, Z1], 'band'),
	el('corner_bl', [3.6, 2, Z0], [5.4, 3.8, Z1], 'band'),
	el('corner_br', [10.6, 2, Z0], [12.4, 3.8, Z1], 'band'),
	el('corner_tl', [3.6, 8.2, Z0], [5.4, 10, Z1], 'band'),
	el('corner_tr', [10.6, 8.2, Z0], [12.4, 10, Z1], 'band'),
	el('rim_front', [5, 10.4, Z0 - 0.3], [11, 10.9, Z1 + 0.3], 'hi'),
	el('bezel', [5.25, 10.75, 5.25], [10.75, 12.75, 10.75], 'bezel'),
	el('bezel_lip', [5.75, 12.75, 5.75], [10.25, 13.25, 10.25], 'hi'),
	el('gem', [6.5, 12.75, 6.5], [9.5, 14.25, 9.5], 'gem'),
	el('gem_crown', [7.25, 14.25, 7.25], [8.75, 14.75, 8.75], 'gem'),
];
const model = {
	credit: 'Project Hero v0.14.3 -- generated by scratchpad/gen_ring_model_v0143.js',
	textures: { t: 'projecthero:item/power_ring_model', particle: 'projecthero:item/power_ring' },
	elements,
	display: {
		gui: { rotation: [20, -35, 0], translation: [0, -1, 0], scale: [0.95, 0.95, 0.95] },
		ground: { rotation: [0, 0, 0], translation: [0, 2, 0], scale: [0.5, 0.5, 0.5] },
		fixed: { rotation: [0, 0, 0], translation: [0, 0, 0], scale: [0.9, 0.9, 0.9] },
		head: { rotation: [0, 0, 0], translation: [0, 13, 7], scale: [1, 1, 1] },
		thirdperson_righthand: { rotation: [0, 90, 0], translation: [0, 2.5, 1], scale: [0.28, 0.28, 0.28] },
		thirdperson_lefthand: { rotation: [0, 90, 0], translation: [0, 2.5, 1], scale: [0.28, 0.28, 0.28] },
		firstperson_righthand: { rotation: [0, -60, 15], translation: [1.5, 3.5, 0], scale: [0.4, 0.4, 0.4] },
		firstperson_lefthand: { rotation: [0, -60, 15], translation: [1.5, 3.5, 0], scale: [0.4, 0.4, 0.4] },
	},
};
fs.writeFileSync('src/main/resources/assets/projecthero/models/item/power_ring.json', JSON.stringify(model, null, 2)
	.replace(/\[\s*([-0-9.,\s]+?)\s*\]/g, (m, g) => '[' + g.split(',').map(x => x.trim()).join(', ') + ']') + '\n');
console.log('ok');
