// Moon Knight guide chapter + move names (v0.13.20).
require('./langset.js')([
	{ anchor: null, entries: {
		'projecthero.guide.moon_knight': 'Moon Knight',
		'projecthero.guide.moon_knight.tier': 'Primary Power -- the Fist of Khonshu',
		'projecthero.guide.moon_knight.body': 'Marc Spector died on an altar under the moon and came back as Khonshu\'s avenger. Moon Knight is a street-level hero who grows with the moon: strongest on a full moon night, weakest by day or underground, and fuelled by Vengeance for the ones who hunt the innocent.',
		'projecthero.guide.moon_knight.origin': 'Becoming Moon Knight',
		'projecthero.guide.moon_knight.origin.body': 'Find a Temple of Khonshu in a desert (rarer than a desert pyramid). A hidden lower chamber holds the Scarab of Khonshu. At night, with the moon above the temple\'s open roof, right-click the altar with the Scarab, then stand on the altar and sneak -- kneel -- for 10 seconds while Khonshu speaks. Stop kneeling, step off or let the sun rise and the Scarab pops back out. Finish and you die in a flash of white... and rise again on the altar as his fist. Each altar only answers once. Sealed under a full moon, you begin with full Vengeance.',
		'projecthero.guide.moon_knight.suit': 'The suit (H)',
		'projecthero.guide.moon_knight.suit.body': 'Press H: for a second and a half white bandages spiral up your body (you can\'t be hurt while they do), then the suit of Khonshu is on, with its cape. The armour you were wearing is kept safe and handed back exactly as it was when you press H again. The suit can\'t be taken off, dropped or stored, and none of Moon Knight\'s abilities or HUD work without it. While suited, his keys win over vanilla\'s creative hotbar save / load (C / X).',
		'projecthero.guide.moon_knight.lunar': 'Lunar power',
		'projecthero.guide.moon_knight.lunar.body': 'Every ability\'s damage, range and duration is multiplied by the moon, and every cooldown divided by it: x1.5 at night under a full moon, x1.3 down to x1.0 as the moon wanes, x0.8 under a new moon, x0.7 by day (and in the Nether and the End). With no open sky above you it drops by another 0.15 (never below x0.6). The HUD shows tonight\'s moon and the live multiplier.',
		'projecthero.guide.moon_knight.vengeance': 'Vengeance',
		'projecthero.guide.moon_knight.vengeance.body': 'A 0-100 meter. Killing a hostile mob that was hunting a villager, a wandering trader, an iron golem or another player gives +5; any other hostile kill gives +2 at night and +1 by day. Go two in-game days without a hostile kill and it slowly drains. Some abilities cost Vengeance. If it runs dry while you are suited your mind Fractures: another alter takes over for 20 seconds (it can only happen once every ten minutes).',
		'projecthero.guide.moon_knight.alters': 'The three alters',
		'projecthero.guide.moon_knight.alters.body': 'Marc Spector, the fighter: +4 armour, +20% melee damage, harder to knock back. Steven Grant, the thinker: 15% less melee damage taken, extra loot from mobs, better prices from villagers. Jake Lockley, the shadow: faster while sneaking, mobs notice you from half as far away, +50% damage attacking from behind.',
		'projecthero.guide.moon_knight.resurrection': 'Khonshu\'s Resurrection',
		'projecthero.guide.moon_knight.resurrection.body': 'While suited, the first fatal hit is cancelled: you rise at 6 hearts with a flash of white and a burst of crescents, untouchable for 2 seconds. It recharges only at the start of the next full moon night. The crescent on the HUD shows whether it is ready.',
		'projecthero.guide.moon_knight.controls': 'Abilities',
		'projecthero.guide.moon_knight.controls.body': 'Every key has three moves: tap it, hold it, or press it while sneaking. They only work in the suit.',
		'projecthero.guide.moon_knight.commands': 'Admin commands',
		'projecthero.guide.moon_knight.commands.body': 'Operators: /moonknight grant | revoke | vengeance <0-100> | locate_temple | moon <0-7> [day|night] | suit on|off | status.',
		'projecthero.moon_knight.move.darts': 'Crescent Dart',
		'projecthero.moon_knight.move.darts.desc': 'Throw a spinning crescent dart (5). At night it gently homes on a nearby hostile mob, and if it misses it curves back to you like a boomerang.',
		'projecthero.moon_knight.move.dart_fan': 'Crescent Fan',
		'projecthero.moon_knight.move.dart_fan.desc': 'Charge for up to 1.5 s and release to throw a fan of 3 darts -- 5 under a full moon.',
		'projecthero.moon_knight.move.moon_mark': 'Moon Mark',
		'projecthero.moon_knight.move.moon_mark.desc': 'A dart that sticks in its target: it glows for 10 s and takes 30% more damage from you.',
		'projecthero.moon_knight.move.grapple': 'Grappling Line',
		'projecthero.moon_knight.move.grapple.desc': 'Fire a line up to 24 blocks into the block you are looking at and get pulled to it.',
		'projecthero.moon_knight.move.dive_kick': 'Line Dive Kick',
		'projecthero.moon_knight.move.dive_kick.desc': 'Grapple to the mob you are looking at and crash into it feet first (8 + knockback).',
		'projecthero.moon_knight.move.yank': 'Yank',
		'projecthero.moon_knight.move.yank.desc': 'Pull the mob you are looking at to you and stun it for 1.5 s.',
		'projecthero.moon_knight.move.truncheon': 'Truncheon',
		'projecthero.moon_knight.move.truncheon.desc': 'Summon or stow your truncheon. Every third hit in a quick chain is a heavy slam, and each hit at night heals you half a heart. It only exists while you are suited.',
		'projecthero.moon_knight.move.staff_spin': 'Staff Spin',
		'projecthero.moon_knight.move.staff_spin.desc': 'Extend the truncheon into a staff and spin, hitting everything within 3.5 blocks (6).',
		'projecthero.moon_knight.move.slam': 'Crescent Slam',
		'projecthero.moon_knight.move.slam.desc': 'On the ground: a shockwave that throws everything within 4 blocks into the air. In the air: dive straight down and slam where you land -- harder the further you fell, and you take no fall damage.',
		'projecthero.moon_knight.move.glide': 'Cape Glide',
		'projecthero.moon_knight.move.glide.desc': 'In the air, spread the cape and glide (no elytra needed, no fall damage). Glides go further at night. Tap again, or land, to stop.',
		'projecthero.moon_knight.move.shroud': 'Cape Shroud',
		'projecthero.moon_knight.move.shroud.desc': 'Wrap the cape around yourself while you hold: 60% less projectile damage, 25% less melee damage, but you move slowly. Up to 5 s.',
		'projecthero.moon_knight.move.shadow_step': 'Shadow Step',
		'projecthero.moon_knight.move.shadow_step.desc': 'Dash 5 blocks backwards into a puff of shadow and vanish for 3 s.',
		'projecthero.moon_knight.move.alter': 'Switch Alter',
		'projecthero.moon_knight.move.alter.desc': 'Marc -> Steven -> Jake -> Marc.',
		'projecthero.moon_knight.move.alter_pick': 'Alter Picker',
		'projecthero.moon_knight.move.alter_pick.desc': 'Open a small picker and choose an alter directly; let go to confirm.',
		'projecthero.moon_knight.move.alter_special': 'Alter Special',
		'projecthero.moon_knight.move.alter_special.desc': 'Marc -- Fist of Khonshu: Strength II and knockback resistance for 10 s (15 Vengeance). Steven -- Scholar\'s Sight: chests, ores and spawners within 16 blocks glow through walls for 8 s. Jake -- Vanish: 8 s invisible, and everything hunting you loses track of you.',
		'projecthero.moon_knight.move.moonbeam': 'Moonbeam',
		'projecthero.moon_knight.move.moonbeam.desc': 'Call a beam of moonlight down on the block you are looking at (up to 40 blocks): 10 damage in 2 blocks, double to the undead. Night only; costs 10 Vengeance.',
		'projecthero.moon_knight.move.eye': 'Eye of Khonshu',
		'projecthero.moon_knight.move.eye.desc': 'The ultimate. Only under a full moon with 100 Vengeance: hold for 2 s. Every hostile mob within 32 blocks glows and is weakened for 30 s, you gain Strength II and Speed II, and Khonshu\'s skull looks down from the sky. Once per night.',
		'projecthero.moon_knight.move.judgement': 'Khonshu\'s Judgement',
		'projecthero.moon_knight.move.judgement.desc': 'Mark the mob you are looking at. If it dies within 10 s you get 20 Vengeance back and heal 3 hearts.',
	} },
]);
