// v0.15.3: lang keys for the Gladiator Hulk's twelve moves (names, descriptions, HUD, messages, entities, guidebook).
require('./langset.js')([
	{
		anchor: 'projecthero.hulk.ability.calm.desc',
		entries: {
			'projecthero.hulk.gladiator.ability.axe_cleave': 'Axe Cleave',
			'projecthero.hulk.gladiator.ability.axe_cleave.desc': 'A wide sweep of the axe in front of him: 34 to everything in a 160-degree arc out to 5.5 blocks, heavy knockback, and the cut bleeds (2 a second for 4 seconds). 5 s.',
			'projecthero.hulk.gladiator.ability.hammer_uppercut': 'Hammer Uppercut',
			'projecthero.hulk.gladiator.ability.hammer_uppercut.desc': 'Shift+R: the hammer swung up from the ground into the one enemy in front of him (5 blocks): 36 damage and launched high into the air. 6 s.',
			'projecthero.hulk.gladiator.ability.hammer_quake': 'Hammer Quake',
			'projecthero.hulk.gladiator.ability.hammer_quake.desc': 'Both hands on the hammer, overhead, into the ground: a fissure tears forward 14 blocks in a 60-degree cone, 36 damage, everything thrown back and up. It cracks soft ground (dirt, sand, gravel) along the way. 7 s.',
			'projecthero.hulk.gladiator.ability.earthsplitter': 'Earthsplitter',
			'projecthero.hulk.gladiator.ability.earthsplitter.desc': 'Shift+G: the axe driven blade-first into the ground. The earth erupts in a straight line 18 blocks ahead, 3 wide: 30 damage and everything on the line launched into the air. 9 s.',
			'projecthero.hulk.gladiator.ability.champions_roar': "Champion's Roar",
			'projecthero.hulk.gladiator.ability.champions_roar.desc': 'Weapons raised, a roar for the crowd: +6 attack and full knockback resistance for 8 seconds, +15 rage, and everything within 12 blocks is staggered (weakened, slowed) and runs from him. 20 s.',
			'projecthero.hulk.gladiator.ability.weapon_clash': 'Weapon Clash',
			'projecthero.hulk.gladiator.ability.weapon_clash.desc': 'Shift+Z: axe and hammer smashed together. The ringing shockwave hits everything within 7 blocks for 18 and stuns it for 1.5 seconds. 12 s.',
			'projecthero.hulk.gladiator.ability.arena_leap': 'Arena Leap',
			'projecthero.hulk.gladiator.ability.arena_leap.desc': 'A huge leap (about 28 blocks along your look) that lands weapons-first: 32 damage within 6 blocks and a crater. From the ground. 8 s.',
			'projecthero.hulk.gladiator.ability.meteor_dive': 'Meteor Dive',
			'projecthero.hulk.gladiator.ability.meteor_dive.desc': 'Shift+X: straight up, then a burning dive at wherever you are looking -- steer it on the way down. Smaller blast, much harder: 55 damage within 3.5 blocks and a crater. 15 s.',
			'projecthero.hulk.gladiator.ability.axe_throw': 'Axe Throw',
			'projecthero.hulk.gladiator.ability.axe_throw.desc': 'The axe spins out 24 blocks along your look, cutting through everything in its way (26 each), and flies back to your hand, cutting again. Your left hand is empty until it is back. 5 s.',
			'projecthero.hulk.gladiator.ability.hammer_hurl': 'Hammer Hurl',
			'projecthero.hulk.gladiator.ability.hammer_hurl.desc': 'Shift+C: the hammer thrown in an arc. It lands with a shockwave (30 within 4.5 blocks) and stays stuck in the ground. Press C to call it back -- it flies home and hits everything on the way (20). It comes back by itself after 30 seconds. 8 s.',
			'projecthero.hulk.gladiator.ability.whirlwind': 'Gladiator Whirlwind',
			'projecthero.hulk.gladiator.ability.whirlwind.desc': 'Three seconds spinning with both weapons out -- you can still move. 8 damage to everything close every quarter second, enemies within 7 blocks are dragged into the blades, and it ends with a hammer slam (26 within 5 blocks). 12 s after.',
			'projecthero.hulk.gladiator.ability.arena_grapple': 'Arena Grapple',
			'projecthero.hulk.gladiator.ability.arena_grapple.desc': 'Shift+V: grabs the enemy in front of him, pins it to the ground and pounds it with the hammer -- five blows of 9. Shift+V again throws it (14 more). No bosses or anything too big. 10 s after.',
			'hud.projecthero.hulk.gladiator_form': 'Gladiator Hulk',
			'hud.projecthero.hulk.gladiator_shift': 'Shift +',
			'message.projecthero.hulk.gladiator.axe_away': 'Your axe is still out.',
			'message.projecthero.hulk.gladiator.hammer_away': 'Your hammer is out -- C calls it back.',
			'entity.projecthero.thrown_gladiator_axe': 'Gladiator Axe',
			'entity.projecthero.thrown_gladiator_hammer': 'Gladiator Hammer',
		},
	},
	{
		anchor: 'projecthero.guide.hulk.controls',
		entries: {
			'projecthero.guide.hulk.gladiator_moves': 'Gladiator Hulk -- Moves',
			'projecthero.guide.hulk.gladiator_moves.body': 'With the full gladiator gear on, the Hulk fights with his axe (left hand) and hammer (right hand): R, G, Z, X, C and V become the twelve moves below -- tap the key, or hold Shift for the second move. Rage, control, the death save, Calm Down, riding and his passives stay the same; take a piece of the gear off and the bare-handed kit is back. Hold Shift (or Alt) to see the names above the HUD boxes; the strip under each box is the other move on that key. A thrown weapon leaves that hand empty -- moves that swing it wait until it is back.',
		},
	},
]);
