// v0.14.27 agent D: Mark III weapon wheel, held Unibeam, Energy Shield, JARVIS scan.
require('./langset.js')([
	{ anchor: 'hud.projecthero.ironman.ability.rocket', entries: {
		'hud.projecthero.ironman.ability.mk3_arsenal': 'Weapon (Sneak: Sonic Clap)',
		'hud.projecthero.ironman.ability.mk3_rockets': 'Rockets',
		'hud.projecthero.ironman.ability.mk3_minigun': 'Miniguns',
		'hud.projecthero.ironman.ability.mk3_micro_missiles': 'Micro-Missiles',
		'hud.projecthero.ironman.ability.mk3_flares': 'Flares (Sneak: JARVIS Scan)',
		'hud.projecthero.ironman.ability.mk3_unibeam': 'Unibeam (hold)',
		'hud.projecthero.ironman.ability.mk3_weapon_wheel': 'Weapon Wheel (Sneak: Shield)',
	} },
	{ anchor: 'screen.projecthero.weapon_wheel.desc.rocket', entries: {
		'screen.projecthero.weapon_wheel.mk3_title': 'Mark III Arsenal',
		'screen.projecthero.weapon_wheel.mk3_hint': 'Click a weapon to fire it with [G]',
		'screen.projecthero.weapon_wheel.desc.mk3_rockets': 'One 35-damage blast rocket',
		'screen.projecthero.weapon_wheel.desc.mk3_minigun': 'Hold G: 5 s of shoulder fire',
		'screen.projecthero.weapon_wheel.desc.mk3_micro_missiles': '4 homing shoulder missiles',
	} },
	{ anchor: 'hud.projecthero.ironman.chip.blades', entries: {
		'hud.projecthero.ironman.chip.mk3_shield': 'SHIELD',
	} },
	{ anchor: 'screen.projecthero.ironman_info.missiles', entries: {
		'screen.projecthero.ironman_info.mk3_rockets': 'Rockets',
		'screen.projecthero.ironman_info.mk3_minigun': 'Miniguns',
		'screen.projecthero.ironman_info.mk3_micro': 'Micro-Missiles',
	} },
	{ anchor: 'message.projecthero.ironman.barrier_up', entries: {
		'message.projecthero.ironman.mk3.weapon_selected': 'G weapon: %s',
		'message.projecthero.ironman.mk3.shield_up': 'Energy shield up.',
		'message.projecthero.ironman.mk3.shield_down': 'Energy shield down.',
		'message.projecthero.ironman.mk3.shield_failed': 'Energy shield failed: no power.',
		'message.projecthero.ironman.jarvis.header': 'Scan complete, %s m radius.',
		'message.projecthero.ironman.jarvis.hostiles': 'Hostiles: %s',
		'message.projecthero.ironman.jarvis.threat': 'Main threat: %s, %s HP, %s m %s',
		'message.projecthero.ironman.jarvis.creatures': 'Passive: %s, neutral: %s',
		'message.projecthero.ironman.jarvis.boss': 'BOSS: %s, %s HP, %s m %s',
		'message.projecthero.ironman.jarvis.no_players': 'No other players nearby.',
		'message.projecthero.ironman.jarvis.player': '%s (%s), %s HP, %s m %s',
		'message.projecthero.ironman.jarvis.structure': 'You are inside: %s',
		'message.projecthero.ironman.jarvis.ores': 'Within %s m: %s diamond, %s emerald, %s ancient debris',
		'message.projecthero.ironman.jarvis.no_ores': 'No valuables within %s m.',
		'message.projecthero.ironman.jarvis.env': '%s, %s, %s',
		'message.projecthero.ironman.jarvis.weather.clear': 'clear skies',
		'message.projecthero.ironman.jarvis.weather.rain': 'rain',
		'message.projecthero.ironman.jarvis.weather.thunder': 'thunderstorm',
		'message.projecthero.ironman.jarvis.suit': 'Suit: energy %s, integrity %s',
		'message.projecthero.ironman.jarvis.summary': 'JARVIS: %s hostiles, %s players within %s m',
	} },
]);
