// v0.14.16: Stark Sorting Station + Stark Sorter Bot lang.
require('./langset.js')([
	{ anchor: 'container.projecthero.stark_fabricator', entries: {
		'block.projecthero.stark_sorting_station': 'Stark Sorting Station',
		'item.projecthero.stark_sorting_station': 'Stark Sorting Station',
		'item.projecthero.stark_sorting_station.desc1': 'Fill it and press Sort: a Sorter Bot files everything into the chests and barrels within 10 blocks.',
		'item.projecthero.stark_sorting_station.desc2': 'More chests = finer categories.',
		'container.projecthero.stark_sorting_station': 'Stark Sorting Station',
		'entity.projecthero.stark_sorter_bot': 'Stark Sorter Bot',
		'screen.projecthero.stark_sorting_station.sort': 'Sort',
		'screen.projecthero.stark_sorting_station.busy': 'Busy',
		'screen.projecthero.stark_sorting_station.sort_hint': 'Deploy the Sorter Bot. It scans every chest and barrel within 10 blocks, decides what goes where, and files this station\'s items away.',
		'screen.projecthero.stark_sorting_station.idle': 'Load items, then press Sort.',
		'screen.projecthero.stark_sorting_station.sorting': 'Sorting... %s/%s stacks',
		'screen.projecthero.stark_sorting_station.finished': 'Last sort: %s/%s stacks filed',
		'message.projecthero.stark_sorting_station.already_running': 'The Sorter Bot is already working (%s/%s stacks).',
		'message.projecthero.stark_sorting_station.empty': 'There is nothing in the station to sort.',
		'message.projecthero.stark_sorting_station.no_chests': 'No chests or barrels within %s blocks of the station.',
		'message.projecthero.stark_sorting_station.plan': 'Sorter Bot deployed: %s containers -> %s',
		'message.projecthero.stark_sorting_station.done': 'Sorting complete: %s stacks filed away.',
		'message.projecthero.stark_sorting_station.leftover': '%s stacks did not fit anywhere and stayed in the station.',
		'message.projecthero.stark_sorting_station.lost': 'The Sorter Bot lost contact with its station; everything it was carrying was put back.',
		'sort_group.projecthero.blocks': 'Blocks',
		'sort_group.projecthero.gear': 'Tools & Combat',
		'sort_group.projecthero.food_farming': 'Food & Farming',
		'sort_group.projecthero.misc': 'Misc',
		'sort_category.projecthero.building': 'Stone & Building',
		'sort_category.projecthero.wood': 'Wood',
		'sort_category.projecthero.decoration': 'Decoration',
		'sort_category.projecthero.combat': 'Combat',
		'sort_category.projecthero.tools': 'Tools',
		'sort_category.projecthero.food': 'Food',
		'sort_category.projecthero.farming': 'Farming & Plants',
		'sort_category.projecthero.ores': 'Ores & Minerals',
		'sort_category.projecthero.redstone': 'Redstone',
		'sort_category.projecthero.mob_drops': 'Mob Drops',
		'sort_category.projecthero.brewing': 'Potions & Brewing',
		'sort_category.projecthero.mod_items': 'Project Hero Gear',
		'sort_category.projecthero.misc': 'Misc',
	} },
]);
