// v0.12.25 guide / lang text updates. Run from the repo root: node scratchpad/lang_v01225.js
const fs = require('fs');
const f = 'src/main/resources/assets/projecthero/lang/en_us.json';
const json = JSON.parse(fs.readFileSync(f, 'utf8'));
const set = (k, v) => { if (!(k in json)) throw new Error('missing ' + k); json[k] = v; };

set('projecthero.guide.wolverine.step.serum', '2. Craft a Wolverine Serum (4 diamonds, 2 netherite ingots, 2 blaze powder, a golden apple) and use it. It consumes Super Regeneration and replaces your mutations, like any Primary power. You start with NO claws. Admins: /wolverine power grant.');
set('projecthero.guide.wolverine.claws', 'CLAWS: BONE, THEN ADAMANTIUM');
set('projecthero.guide.wolverine.claws.body', 'You do not start with claws. 3. Craft a Bone Claw Serum (4 bone blocks, netherite scrap, 2 gold ingots, a glass bottle, a ghast tear) and use it: six natural BONE CLAWS (three a hand, ivory and curved) grow through your knuckles. Bone claws hit for 9 bare-handed, Claw Slash 15, Cross Slash 10 + 10, Claw Dash 10, Frenzy 6 each -- and Adamantium Execution stays locked ("Adamantium Claws required"). 4. Craft an Adamantium Serum (4 netherite ingots, a diamond block, 2 gold blocks, a nether star, a glass bottle), retract your claws, then HOLD right-click for 3 seconds: you are rooted while the adamantium bonds to the bone, then the bone claws are replaced by silver ADAMANTIUM CLAWS with the full-strength kit (12 bare-handed, Slash 18, Cross 12 + 12, Dash 12, Frenzy 8 each) and Adamantium Execution unlocks. Letting go early cancels it without using the serum. Both tiers are permanent and survive death. H deploys or retracts the claws ("Bone Claws required" until you have them; Shift+H still opens the power wheel if you also own mutations). While they are out they break blocks like a sword (cobwebs give way at once, plants and leaves 1.5x faster) and you mine 1.5x faster. You cannot hold items in either hand while the claws are out (they are stowed in your inventory). Right-click strikes with your left hand for exactly the same damage as your right. Deploying the claws tears through your hands for 4 damage (never enough to kill you) -- but that is not a fight: it never fills your Rage bar and never tears your suit. Every claw move deploys them for you if they are away. Other players see your claws.');
set('projecthero.guide.wolverine.ability.adamantium_execution', 'Needs ADAMANTIUM claws (locked with Bone Claws). Hold the key for 5 seconds to charge (you move slowly while charging), then release: a short wind-up, a lunge, and a 60-damage claw strike with heavy knockback, range 4 blocks. Needs a target in front of you; a whiff only costs 8 seconds. 30-second cooldown.');
set('projecthero.guide.wolverine.ability.claw_slash', 'A fast forward slash to everything in a box 3.5 blocks deep and 3 blocks wide in front of you: 18 damage with adamantium claws, 15 with bone. 1.5-second cooldown.');
set('projecthero.guide.wolverine.ability.cross_slash', 'Two crossing cuts to everything in a box 3 blocks deep and 3 blocks wide in front of you: 12 + 12 with adamantium claws, 10 + 10 with bone. 4-second cooldown.');
set('projecthero.guide.wolverine.ability.frenzy', 'Five rapid strikes (0.2 s apart), spread over the nearest enemies within 4 blocks: 8 each with adamantium claws, 6 with bone. Needs a target. 15-second cooldown.');
set('projecthero.guide.wolverine.passives.body', 'Healing factor: a flat 1.5 HP every 5 ticks (6 HP/s) -- whatever your health, and it never slows in combat. 35% less physical damage, 75% knockback resistance, 75% less fall damage. Strong Poison and Wither resistance. Melee damage of 4 (12 unarmed with adamantium claws out, 9 with bone), jump 2 blocks high (no passive speed bonus). Any mob hunting you glows orange, for you alone (enhanced senses). Fire still hurts, but you outheal it.');
set('projecthero.guide.wolverine.body', 'Your regenerative mutation, taken all the way: a healing factor that shrugs off almost anything, a stronger and faster body, and -- through two serums -- claws of bone, then adamantium. It is a fighter\'s power -- close range, brutal, and very hard to put down.');
set('projecthero.guide.symbiote.step.bond', 'Right-click it (or use a filled Symbiote Vial). The Symbiote tests you first: a BONDING MINIGAME opens -- a marker sweeps across a bar and you must stop it inside the green zone (Space or click) three times running, faster and tighter each round. Miss and the Symbiote recoils: you are nauseous and cannot try again for 5 seconds (nothing is used up). Win and it does not click cleanly into place -- it spreads through you over 35 seconds. During that time you have its protection but none of its abilities, and your body fights it: nausea, weakness, the shakes. Ride it out. Once it settles, press H to let the suit take hold, and H again to retract it. (An operator granting the Symbiote with a command skips all of this.)');
set('projecthero.guide.green_lantern.constructs.body', json['projecthero.guide.green_lantern.constructs.body'] + ' The Mining Drill breaks a 2x2 patch of blocks every 0.75 seconds while it is switched on.');

fs.writeFileSync(f, JSON.stringify(json, null, 2) + '\n');
console.log('ok');
