// v0.14.1 (built as 0.13.22 prep): mutation acquisition fixes -- new lab devices, trigger text that matches the code,
// H / N utility controls. Run from the repo root: node scratchpad/lang_v01322_acq.js
require('./langset.js')([
	{ anchor: 'block.projecthero.electromagnetic_coil', entries: {
		'block.projecthero.charged_copper_plates': 'Charged Copper Plates',
		'block.projecthero.crystal_chamber': 'Crystal Test Chamber',
		'block.projecthero.enchanting_resonance': 'Enchanting Resonance Array',
		'block.projecthero.blast_chamber': 'Controlled Blast Chamber',
		'block.projecthero.resonant_chamber': 'Resonant Chamber',
		'block.projecthero.gravity_distortion_rig': 'Gravity Distortion Rig',
	} },
	{ anchor: 'projecthero.device.enchanting_resonance', entries: {
		'projecthero.device.enchanting_resonance': 'Enchanting Resonance Array',
	} },
	{ entries: {
		'projecthero.power.power_01_super_strength.trigger': 'Drink the serum, then take an electrical surge from an Overloaded Redstone Coil or Charged Copper Plates (or a natural lightning strike).',
		'projecthero.power.power_03_flight.trigger': 'Drink the serum, then activate an Unstable Gravity Plate, a Gravity Distortion Rig or a Pressure Chamber — or survive a fall of 14+ blocks.',
		'projecthero.power.power_04_super_speed.trigger': 'Drink the serum, then activate Charged Copper Plates or an Overloaded Redstone Coil (or get struck by lightning).',
		'projecthero.power.power_06_crystalkinesis.trigger': 'Drink the serum and stay near 8+ amethyst blocks (a natural geode, a Meteor Impact site) — or activate a Crystal Test Chamber or Geological Resonance Chamber.',
		'projecthero.power.power_09_cryokinesis.trigger': 'Drink the serum and stay sunk in Powder Snow for a few seconds — or activate a Crystal Test Chamber.',
		'projecthero.power.power_10_telekinesis.trigger': 'Drink the serum near an Enchanting Table ringed by 8+ bookshelves, or activate an Enchanting Resonance Array.',
		'projecthero.power.power_11_teleportation.trigger': 'Drink the serum and throw an Ender Pearl while the effect is active, or activate an Enchanting Resonance Array.',
		'projecthero.power.power_13_super_durability.trigger': 'Drink the serum and survive an explosion (TNT, a creeper) or activate a Controlled Blast Chamber.',
		'projecthero.power.power_14_sonic_scream.trigger': 'Blow a Goat Horn while the serum is active, or activate a Resonant Chamber.',
		'projecthero.power.power_17_elasticity.trigger': 'While the serum is active, fall at least 10 blocks onto a Slime Block — or activate a Gravity Distortion Rig.',
		'projecthero.power.power_20_energy_absorption.trigger': 'While the serum is active, survive two different kinds of energy (fire, explosion, lightning) — or activate a Controlled Blast Chamber.',
		'projecthero.power.power_21_shockwave_manipulation.trigger': 'Drink the serum and survive an explosion (TNT, a creeper) or activate a Controlled Blast Chamber.',
		'projecthero.power.power_23_gravity_manipulation.trigger': 'Drink the serum, then activate a Gravity Distortion Rig, an Unstable Gravity Plate or a Pressure Chamber — or survive a fall of 14+ blocks.',
		'projecthero.power.power_25_water_manipulation.trigger': 'Drink the serum and stay fully underwater for 15 seconds (the serum keeps you breathing), or use a Hydrostatic Test Tank.',
		'projecthero.power.power_26_magnetic_manipulation.trigger': 'Drink the serum and stand among 16+ iron or copper blocks, bars or anvils for a few seconds — or activate an Electromagnetic Coil.',
		'projecthero.power.power_27_size_manipulation.trigger': 'Drink the serum, then activate a Mass Compression Chamber (found at Government Experiment Sites, or craft one).',
		'projecthero.guide.controls.select': '  H   Utility 1 - with a mutation selected, H is its Utility 1 ability and Shift+H opens the power wheel (switch which mutation occupies the keys). Hero powers use H first: Iron Man\'s faceplate, Max Steel\'s helmet, the Symbiote suit, the Hulk, Moon Knight\'s suit, Wolverine\'s claws, Thor\'s armour. Alt+H always fires your mutation\'s Utility 1.',
		'projecthero.guide.controls.utility2': '  N   Utility 2 - with a mutation selected, N is its Utility 2 ability and Sneak+N fires a power combo when you own a matching pair. Hero powers use N first: Max Steel\'s Go Turbo, the Symbiote\'s Predator Vision, Spider-Man\'s mode switch, Wolverine\'s sniff. Alt+N always fires your mutation\'s Utility 2.',
		'projecthero.guide.controls.info': '  I   Your Power - open a quick reference for your active power and all of its abilities.',
		'message.projecthero.combo.none': 'No combo: you need to own a matching pair of mutations.',
		'projecthero.combo_move.meteor_slam': 'Meteor Slam',
		'projecthero.combo_move.colossus_stomp': 'Colossus Stomp',
		'projecthero.combo_move.boulder_barrage': 'Boulder Barrage',
		'projecthero.combo_move.thunder_sprint': 'Thunder Sprint',
		'projecthero.combo_move.storm_surge': 'Storm Surge',
		'projecthero.combo_move.glacier_flood': 'Glacier Flood',
		'projecthero.combo_move.comet_dash': 'Comet Dash',
		'projecthero.combo_move.fire_tornado': 'Fire Tornado',
		'projecthero.combo_move.solar_lance': 'Solar Lance',
		'projecthero.combo_move.umbral_leap': 'Umbral Leap',
		'projecthero.combo.strength_flight': 'Super Strength + Flight: Ground Slam / Dive Bomb scale with fall speed, and Sneak+N fires METEOR SLAM — rocket skyward and come down in a 26-damage crater (40 s).',
		'projecthero.combo.speed_electrokinesis': 'Super Speed + Electrokinesis: sprinting builds charge for your next electrical ability, and Sneak+N fires THUNDER SPRINT — a 14-block lightning dash that shocks (18) and slows everything in the path (30 s).',
		'projecthero.combo.water_electrokinesis': 'Water + Electrokinesis: wet targets take extra electrical damage, and Sneak+N fires STORM SURGE — an electrified tidal ring, 22 damage and a heavy slow around you (35 s).',
		'projecthero.combo.geokinesis_strength': 'Geokinesis + Super Strength: stronger earth attacks, and Sneak+N fires BOULDER BARRAGE — rip up three boulders and hurl them (30 s).',
		'projecthero.combo.cryokinesis_water': 'Cryokinesis + Water: Sneak+N fires GLACIER FLOOD — a freezing flood that deals 16, freezes and roots everything within 8 blocks (35 s).',
		'projecthero.combo.pyrokinesis_flight': 'Pyrokinesis + Flight: a fiery trail at high speed, and Sneak+N fires COMET DASH — burn 16 blocks forward, 16 damage and ignition to everything you pass (30 s).',
		'projecthero.combo.energy_absorption_laser': 'Energy Absorption + Laser Vision: stored energy tops up your heat, and Sneak+N fires SOLAR LANCE — a 40-block, 30-damage beam (40 s).',
		'projecthero.combo.durability_size': 'Super Durability + Size Manipulation: steadier Large/Giant forms, and Sneak+N fires COLOSSUS STOMP — 24 damage in a ring that grows with your size (40 s).',
		'projecthero.combo.wind_fire': 'Wind + Pyrokinesis: Sneak+N fires FIRE TORNADO — a burning vortex where you aim that drags enemies in for 6 seconds (45 s).',
		'projecthero.combo.shadow_teleportation': 'Shadow + Teleportation: Sneak+N fires UMBRAL LEAP — vanish and reappear up to 28 blocks away, blinding and hitting everyone near the landing (25 s).',
	} },
]);
