// v0.13.22 mutation revamp, batch C lang: Electrokinesis, Sonic Scream, Energy Absorption, Shockwave Manipulation,
// Wind Manipulation -- every ability name / desc for the new 8-key kits, new passives, messages and the tornado entity.
// Run from the repo root: node scratchpad/lang_v01322_c.js
const E = 'projecthero.power.power_07_electrokinesis';
const S = 'projecthero.power.power_14_sonic_scream';
const N = 'projecthero.power.power_20_energy_absorption';
const K = 'projecthero.power.power_21_shockwave_manipulation';
const W = 'projecthero.power.power_24_wind_manipulation';
require('./langset.js')([
	// ---------------- 07 Electrokinesis ----------------
	{ anchor: E + '.ability.charged_mode.desc', entries: {
		[E + '.desc']: 'A general electricity mutation — intentionally weaker than Thor’s true lightning. Every hit leaves static stacks on its target; three stacks stun it and set it up for Overcharge and Ion Pull.',
		[E + '.ability.electric_bolt']: 'Electric Bolt',
		[E + '.ability.electric_bolt.desc']: 'Fire a 26-block bolt for 12 damage that adds a static stack and briefly powers nearby redstone. 45 charge, 1.7s cooldown.',
		[E + '.ability.chain_lightning']: 'Chain Lightning',
		[E + '.ability.chain_lightning.desc']: 'Lightning arcs from the enemy under your crosshair through up to 6 enemies for 11 damage each, adding a stack to every one. It jumps 8 blocks to a fresh target but 14 to one already carrying static — and always prefers the stacked one. 85 charge, 7s cooldown. Shift + G fires an EMP instead: redstone, powered doors, minecarts and robotic mobs within 20 blocks shut down for 6s (200 charge, 25s cooldown).',
		[E + '.ability.electric_dash']: 'Bolt Form',
		[E + '.ability.electric_dash.desc']: 'Become a streak of lightning: jump up to 10 blocks along your aim (stopping short of walls), zapping everything along the path for 8 damage and a stack. Brief damage immunity and no fall damage on landing. 60 charge, 3.4s cooldown.',
		[E + '.ability.electrical_storm']: 'Electrical Storm',
		[E + '.ability.electrical_storm.desc']: 'Hold Z for 4 seconds, lightning gathering over your raised arms, then call the storm on your aim point (up to 40 blocks): a 36-damage strike on everything within 5 blocks (+2 stacks), then four follow-up bolts over the next 2.4s for 10 each on enemies within 9 blocks — stacked targets first. Small crater when terrain damage is on. 575 charge, 55s cooldown.',
		[E + '.ability.electromagnetic_pull']: 'Power Surge',
		[E + '.ability.electromagnetic_pull.desc']: 'Energise redstone from up to 50 blocks away — plants a short-lived block of redstone against whatever you are looking at. 70 charge, 6s cooldown.',
		[E + '.ability.charged_mode']: 'Charged Mode',
		[E + '.ability.charged_mode.desc']: 'Toggle: a crackling blue shell and glowing blue eyes — +10 ability damage, +8 melee damage, Speed III, and every punch jolts for 3 more and adds a static stack. Drains your charge cell (~28s); getting hit while charged costs you 3 health and staggers you.',
		[E + '.ability.overcharge']: 'Overcharge',
		[E + '.ability.overcharge.desc']: 'Detonate every static stack within 16 blocks: 8 damage per stack on each stacked enemy (+5 in Charged Mode), knocking them back; fully stacked targets are stunned again. Clears the stacks. 140 charge, 10s cooldown — needs at least one stacked enemy.',
		[E + '.ability.ion_pull']: 'Ion Pull',
		[E + '.ability.ion_pull.desc']: 'Magnetise the static: every stacked enemy within 20 blocks is yanked to you and slowed. With nothing stacked it pulls the enemy under your crosshair instead and gives it a stack. 80 charge, 8s cooldown.',
	} },
	{ anchor: E + '.passive.redstone', entries: {
		[E + '.passive.redstone']: 'Every ability spends from a 1150-point charge cell (always shown) that refills on its own in about 40s, far faster during a thunderstorm. Abilities briefly power nearby redstone, and powered rails energise as you run over them.',
		[E + '.passive.static']: 'Static stacks: every Electrokinesis hit adds one (max 3, lasting 8s). Stacked targets crackle with sparks everyone can see, take +10% Electrokinesis damage per stack, and are stunned for 1.5s when they reach three (then immune to that stun for 4s).',
	} },
	// ---------------- 14 Sonic Scream ----------------
	{ anchor: S + '.ability.echolocation.desc', entries: {
		[S + '.desc']: 'Manipulate destructive sound. Every scream spends Voice and travels as visible rings of sound.',
		[S + '.ability.sonic_blast']: 'Sonic Blast',
		[S + '.ability.sonic_blast.desc']: 'A 5-block cone of sound for 12 damage with knockback and a brief stun. 16 Voice, 4.25s cooldown.',
		[S + '.ability.focused_scream']: 'Focused Scream',
		[S + '.ability.focused_scream.desc']: 'A 30-block beam of sound for 19 damage with knockback, nausea and a brief stun. 24 Voice, 8.5s cooldown.',
		[S + '.ability.sonic_jump']: 'Sonic Jump',
		[S + '.ability.sonic_jump.desc']: 'Blast the ground away beneath you to launch high into the air (4 damage and a shove to anything within 3 blocks) — and take no fall damage from the landing. Boosts an open elytra instead. 12 Voice, 4.25s cooldown.',
		[S + '.ability.supersonic_scream']: 'Supersonic Scream',
		[S + '.ability.supersonic_scream.desc']: 'Hold Z for about 4 seconds as the sound builds in your throat, then unleash a 20-block cone of sound for 60 damage with severe knockback, nausea and a stun, shattering glass, ice and leaves along the way (terrain damage on). Start the hold while sneaking to scream all round you instead: 48 damage in a 20-block radius (68s cooldown). 55 Voice, 60s cooldown.',
		[S + '.ability.resonance']: 'Resonance',
		[S + '.ability.resonance.desc']: 'Vibrate a spot up to 14 blocks away: glass, ice, leaves and other fragile blocks in a 3x3x3 shatter (terrain damage on), and anything within 3.5 blocks takes 6 damage and is stunned and nauseous for 2–3s. 18 Voice, 4.25s cooldown.',
		[S + '.ability.echolocation']: 'Echolocation',
		[S + '.ability.echolocation.desc']: 'Toggle: a sonar ping every 2 seconds (4 Voice each) and pale rings of sound around your head — everything living within 20 blocks glows through walls for you alone, and your screams reach 30% further. Pings don’t stop your Voice recovering. Ends when Voice runs dry.',
		[S + '.ability.sound_barrier']: 'Sound Barrier',
		[S + '.ability.sound_barrier.desc']: 'Raise a 5-wide, 3.5-tall wall of sound 3 blocks in front of you for 5 seconds: projectiles that fly into it are shredded, and enemies caught in it take 3 damage every half second and are shoved out. 30 Voice, 12s cooldown.',
		[S + '.ability.disorient']: 'Disorient',
		[S + '.ability.disorient.desc']: 'A warbling pulse: everything within 10 blocks takes 4 damage, is slowed and nauseous for 6 seconds, and every mob forgets who it was fighting for 3 seconds. 20 Voice, 12s cooldown.',
	} },
	{ anchor: S + '.passive.self_resist', entries: {
		[S + '.passive.voice']: 'Voice (115), always shown: every scream spends it, and it recovers 16 per second once you have been quiet for 1.5s.',
	} },
	// ---------------- 20 Energy Absorption ----------------
	{ anchor: N + '.ability.absorption_mode.desc', entries: {
		[N + '.desc']: 'Absorb fire, lightning, explosions and magic — and release them again as the same element.',
		[N + '.ability.energy_blast']: 'Energy Blast',
		[N + '.ability.energy_blast.desc']: 'Spend 10 energy on a 16-damage bolt of your stored element, 1.7s cooldown. Hold to charge: +6 damage and +1.7s cooldown per second held, up to 3s.',
		[N + '.ability.energy_beam']: 'Energy Beam',
		[N + '.ability.energy_beam.desc']: 'Hold for a sustained beam of your element: 11 damage a hit and the element’s effect every half second, draining 20 energy/s; 4.25s cooldown on release. Shift for an 18-damage burst in 9 blocks instead (50 energy, 17s cooldown).',
		[N + '.ability.absorption_shield']: 'Energy Dash',
		[N + '.ability.absorption_shield.desc']: 'Dash forward on a trail of your element, hitting anything in the first few blocks for 7 damage and the element’s effect. 5 energy, 1.7s cooldown.',
		[N + '.ability.overload']: 'Overload',
		[N + '.ability.overload.desc']: 'Hold Z for 3.5 seconds as a ball of your element grows overhead, then release the WHOLE meter at once (at least 100): 25 damage + 1 per 10 energy spent, in a 6–11-block radius that grows with the energy, with the element’s effect on everything hit and a crater when terrain damage is on. 25s cooldown.',
		[N + '.ability.energy_drain']: 'Energy Drain',
		[N + '.ability.energy_drain.desc']: 'Hold on a creature within 12 blocks: every half second it takes 5 magic damage and you take 14 energy and 1 health. Aim at a redstone block, ore, lamp or lightning rod to drink its current instead (10 energy, as lightning). Up to 6s, 8s cooldown. Shift + V instead converts 10 energy into 2 health every half second.',
		[N + '.ability.absorption_mode']: 'Absorption Mode',
		[N + '.ability.absorption_mode.desc']: 'Toggle: a glowing lattice shell in your element’s colour. Soak 80% of elemental and 40% of physical damage (up from 60% / 25%), +10 ability damage, +8 melee, Speed II and Haste II; your punches glow with your element. 7 energy/s; 17s cooldown when it ends.',
		[N + '.ability.redirect']: 'Redirect',
		[N + '.ability.redirect.desc']: 'For 3 seconds the next projectile flying at you is caught and thrown back at whoever fired it, and a melee blow is negated and fired back at the attacker for 1.5x its damage + 6 with your element’s effect. Half the caught damage becomes energy. 25 energy, 10s cooldown.',
		[N + '.ability.empower']: 'Empower',
		[N + '.ability.empower.desc']: 'Spend 100 energy on a 12-second buff that depends on the stored element: Fire — Strength and Fire Resistance; Lightning — Speed II and Haste II; Explosion — Resistance II; Magic — Regeneration II and Absorption II; raw — Strength and Speed. Your punches carry the element while it lasts. 25s cooldown.',
	} },
	{ anchor: N + '.passive.meter', entries: {
		[N + '.passive.meter']: '575-point Energy meter, always shown and coloured by its element: fire orange, lightning blue, explosion yellow, magic purple, raw cyan. Trickle-regenerates to 25% after 10s without absorbing. 80% grants Strength and Speed; a full meter slowly hurts you. Redstone charges it as lightning (stand on it, harvest dust, or Sneak + use a block or dust to burn it).',
		[N + '.passive.elements']: 'Fire, lightning, explosion and magic damage: 60% is soaked into the meter and sets its element. Other hits: 25% soaked, element unchanged. Everything you fire comes out as the element — fire ignites, lightning arcs to a second target and stuns, explosion blows the target away, magic withers and weakens.',
	} },
	// ---------------- 21 Shockwave Manipulation ----------------
	{ anchor: K + '.ability.charge.desc', entries: {
		[K + '.desc']: 'Store kinetic force — the blows, falls and blasts you take — and release it as pressure waves.',
		[K + '.ability.shockwave_punch']: 'Shockwave Punch',
		[K + '.ability.shockwave_punch.desc']: 'A 7-block pressure cone for 12 damage with knockback, trailing distortion rings. Spends up to 10 Kinetic for up to x1.5 damage and knockback. 1.7s cooldown.',
		[K + '.ability.ground_wave']: 'Ground Wave',
		[K + '.ability.ground_wave.desc']: 'A shockwave that races about 20 blocks along the ground (2-block step assist) for 16 damage to everything it passes, throwing it up. Shift + G bursts all round you instead: 18 damage in 8 blocks (6s cooldown). Spends up to 15 Kinetic for up to x1.5 damage. 5s cooldown.',
		[K + '.ability.recoil_jump']: 'Recoil Jump',
		[K + '.ability.recoil_jump.desc']: 'Blast yourself up and forward like a super-leap — no fall damage on landing. With 10+ Kinetic it spends 10 for a 30% bigger jump and a 6-damage blast on the spot you left. 2.5s cooldown.',
		[K + '.ability.kinetic_detonation']: 'Kinetic Detonation',
		[K + '.ability.kinetic_detonation.desc']: 'Hold for about 4 seconds with a full Kinetic gauge to release a 20-block shockwave for 72 damage, launching everything. Spends the whole gauge, 85s cooldown.',
		[K + '.ability.repulsion_field']: 'Repulsion Field',
		[K + '.ability.repulsion_field.desc']: 'Hold to keep a 3-block field of force up: enemies are shoved away, projectiles thrown back, and damage you take is cut by 30%. Drains 6 Kinetic/s.',
		[K + '.ability.charge']: 'Charge',
		[K + '.ability.charge.desc']: 'Hold to brace: bank 5 Kinetic/s, and every blow, fall or blast you take while bracing stores double and hurts less (melee 40% off). 4.25s cooldown once released.',
		[K + '.ability.aftershock']: 'Aftershock',
		[K + '.ability.aftershock.desc']: 'A delayed second wave where your last wave landed (within 12s and 48 blocks): rings tighten on the spot for 0.8s, then it erupts for 14 damage in 5 blocks and launches everything up. Spends up to 15 Kinetic for up to x1.5. 8s cooldown.',
		[K + '.ability.kinetic_parry']: 'Kinetic Parry',
		[K + '.ability.kinetic_parry.desc']: 'Open a 0.7s parry window: the next melee hit is negated, stored at double its damage, and the attacker takes 5 damage and is thrown back and slowed. A successful parry cuts the cooldown to 2s. 6s cooldown.',
	} },
	{ anchor: K + '.passive.knockback_resist', entries: {
		[K + '.passive.knockback_resist']: '70% less knockback taken; immune to your own shockwaves.',
		[K + '.passive.kinetic']: 'Kinetic storage (a gauge of 115, always shown): melee hits you take are 15% dampened and banked, falls 40% dampened and banked at 1.2x, explosions halved and banked at 1.5x. Only kinetic force — never fire, lightning or magic.',
	} },
	// ---------------- 24 Wind Manipulation ----------------
	{ anchor: W + '.ability.tailwind.desc', entries: {
		[W + '.desc']: 'Ride the air: glide on currents, raise updrafts, and throw blades, gusts and storms.',
		[W + '.ability.wind_blade']: 'Wind Blade',
		[W + '.ability.wind_blade.desc']: 'A crescent of air: 10 damage at up to 26 blocks, 1.7s cooldown. Sneak + hold R about 1.7s: a wide blade that pierces every enemy in a 6-wide corridor for 19 damage (19s cooldown).',
		[W + '.ability.tornado']: 'Wind Burst',
		[W + '.ability.tornado.desc']: 'A 6-block cone of pressure for 14 damage that hurls enemies away and turns projectiles around. 8.5s cooldown.',
		[W + '.ability.glide']: 'Glide / Updraft',
		[W + '.ability.glide.desc']: 'On the ground: raise an updraft that throws you up (50 Wind, 5s cooldown) — for 12s anyone gliding through or over it keeps climbing (up to three at once). In the air: start or stop gliding. Sprint-jumping off a ledge also starts a glide. Steer by looking, look down to dive, Sneak to drop out; no fall damage from a glide.',
		[W + '.ability.hurricane']: 'Hurricane',
		[W + '.ability.hurricane.desc']: 'Hold Z for about 4 seconds to charge, then an 11-second storm around you — 10 damage a second in a 15-block radius, everything whirled around, projectiles thrown back. 51s cooldown.',
		[W + '.ability.wind_push']: 'Wind Push',
		[W + '.ability.wind_push.desc']: 'A wall of air that hurls everything in front of you far away and turns projectiles back. 3.4s cooldown.',
		[W + '.ability.tailwind']: 'Tailwind',
		[W + '.ability.tailwind.desc']: 'Toggle a supporting current: Speed II, high jumps, a 2-block step, +10 ability damage, +8 melee, faster glides, and a gust that shoves anything within 2 blocks away — with a pale air shell while it runs. Drains Wind over ~20s; 20s cooldown when it ends.',
		[W + '.ability.rideable_tornado']: 'Rideable Tornado',
		[W + '.ability.rideable_tornado.desc']: 'Summon a tornado under you and ride it for 12 seconds: it follows your look, hugs the ground and water, drags every enemy within 8 blocks into a spiral and grinds those at its core for 4 damage a second. Press H again (or Sneak) to get off — no fall damage. 120 Wind, 30s cooldown.',
		[W + '.ability.vacuum']: 'Vacuum',
		[W + '.ability.vacuum.desc']: 'Rip the air out of a spot 4 blocks ahead for 2 seconds: every enemy within 12 blocks is dragged in, and those near the centre suffocate for 2.5 damage every half second (ignores armour) and are slowed. 12s cooldown.',
	} },
	{ anchor: W + '.passive.fall', entries: {
		[W + '.passive.fall']: '80% less fall damage (none out of a glide or off a tornado), 30% faster sprint, a 3-block jump, sneak-fall drifting, rocket-free elytra boosts, and you drown 50% slower',
		[W + '.passive.glide']: 'A 575-point Wind reserve, always shown. Sprint-jump off anything with 3+ blocks of air below to glide; updrafts lift gliders; a thin pale air shell shows while you glide, ride or run Tailwind.',
	} },
	// ---------------- messages + entity ----------------
	{ anchor: 'message.projecthero.electro.emp', entries: {
		'message.projecthero.electro.no_target': 'No target in range',
		'message.projecthero.electro.no_room': 'No room to become lightning that way',
		'message.projecthero.electro.no_stacks': 'No static-stacked enemies in range',
		'message.projecthero.sonic.voice_low': 'Your voice is spent — stay quiet a moment',
		'message.projecthero.energy.overload_low': 'Overload needs at least 100 energy',
		'message.projecthero.energy.empower_low': 'Empower needs 100 energy',
		'message.projecthero.shockwave.charge_low': 'Not enough Kinetic',
		'message.projecthero.shockwave.charge_full_needed': 'Kinetic Detonation needs a full Kinetic gauge',
		'message.projecthero.shockwave.no_wave': 'No recent wave to follow up',
	} },
	{ anchor: 'entity.projecthero.colossal_rock', entries: {
		'entity.projecthero.wind_tornado': 'Tornado',
	} },
]);
