// v0.13.21 Green Lantern lang: hard-light block names + guidebook text for directional flight, the suit's
// pixel-row sweep and the construct overhaul. Run from the repo root: node scratchpad/lang_v01321_greenlantern.js
require('./langset.js')([
	{ anchor: 'projecthero.guide.green_lantern.flight', entries: {
		'projecthero.guide.green_lantern.flight.body': 'Double-tap Space while airborne to take off, or land to end it automatically — the same gesture Thor and Iron Man use for their own flight. Ring Flight is directional: hold forward and you fly exactly where you are looking, climbing or diving with your aim, while strafing, Space (up) and Sneak (down) still work like creative flight and letting go of everything eases you into a steady hover. Costs a flat 1 charge/sec while flying, with a trailing green hard-light streak the whole time. Sneak + Sprint to Boost for far more speed at 40 charge/sec plus a thicker trail (while boosting, Sneak no longer descends — look down to dive). Ends safely on depletion with a brief controlled descent instead of a plummet.',
	} },
	{ anchor: 'projecthero.guide.green_lantern.ability.suit', entries: {
		'projecthero.guide.green_lantern.ability.suit.desc': 'Forms or retracts the hard-light suit — it sweeps onto your body from the shoulders down one row of light at a time behind a bright green scan line, and dissolves from the feet back up when you take it off. Full diamond-level protection (20 armour, 2.0 toughness) plus a flat +8 melee damage bonus while worn. Costs 10 charge to summon, plus 1 charge every 5 seconds while worn — running out of charge forces it to retract. Shift casts Ring Scan: every living creature within 50 blocks glows through walls for 6 seconds, red for hostiles and green for everything else — visible only to you, on a 5-second cooldown.',
	} },
	{ anchor: 'projecthero.guide.green_lantern.constructs', entries: {
		'projecthero.guide.green_lantern.constructs.body': 'Temporary shapes of glowing, translucent hard light, not free building blocks — each costs charge up front plus ongoing upkeep, builds itself out in a few ticks as a beam of light traces from your ring, flickers over its last three seconds, and dissolves in green sparks when it ends. Aimed constructs form on the open space in front of whatever you point at; Walls and Sentry Turrets settle onto the ground there, and nothing ever forms inside a player — you included. No cap on how many can be active at once (Sentry Turret is the one exception: 5 live, 12 seconds each — a spinning core of light that only fires at hostiles it can see). Every construct is available the moment you bond. Platform forms a raised floor where you aim — or, if you are falling and looking down, right under your feet to catch you. Stair/Ramp is a 3-wide flight of real steps you can walk straight up. Lantern Light is a floating orb of light. Atmosphere Bubble forms around you and gives you and your squad air. Battering Ram fires a hard-light ram head along your aim that smashes the first creature it meets (up to 16 blocks) or bursts open a door. Rescue Tether is a proper grab (30-block range): press the construct key on whatever\'s under your crosshair to pick it up and carry it in front of you on a visible tether, press again to throw it, or Shift the construct key to set it down safely — holding one costs charge every second. Containment Cage traps whatever\'s under your crosshair — any living target — in a closed box of light sized to fit it, pulls it back in if it tries to slip out, and collapses on its own after 15 seconds or the moment its prisoner dies. Carry Platform is a bright 3x3 platform spawned level with you; press the construct key again to toggle whether it chases your aim or stays parked, and anyone can right-click a tile to ride along. Mining Drill and Energy Blade deploy for free as an equipped stance — a second press switches the drill or blade itself on (only then does it cost anything, and you can see it on your hand), a third turns it off. The Mining Drill breaks a 2x2 patch of blocks every 0.5 seconds while it is on. The Hard-Light Tool Kit\'s tools shimmer and never wear out.',
	} },
	{ anchor: 'projecthero.guide.green_lantern.battery', entries: {
		'projecthero.guide.green_lantern.battery.body': 'Craft one (Lantern Core + 4 Emerald Blocks + 2 Amethyst Blocks + an Ender Eye + an Echo Shard) — a green lantern with a glowing emblem behind glass — and right-click it below max charge to recite the Oath: four lines appear on screen, one at a time, in green. Finish the recitation and your ring fills instantly; any movement, turning, damage or ability use cancels it with nothing gained. This is now the only way to recharge — the ring no longer regenerates charge on its own.',
	} },
	{ anchor: 'block.projecthero.fallen_lantern_pedestal', entries: {
		'block.projecthero.hard_light': 'Hard Light',
		'block.projecthero.hard_light_stairs': 'Hard-Light Steps',
		'block.projecthero.hard_light_lamp': 'Hard-Light Orb',
	} },
]);
