// v0.14.27 guidebook: Iron Man controls, suit-up, Mark 1/2/III kits, landing, platform
require('./langset.js')([{ anchor: 'projecthero.guide.iron_man.furnaces.body', entries: {
  'projecthero.guide.iron_man.controls': 'Wearing a suit the six ability keys are R / G / X / Z / V / C; every mark has its own kit (see the Mark pages below, or press I for the spec sheet). Double-tap jump in the air to fly (except the Mark 1, which flies only with its Flight Burst). Unarmoured, C puts on any armour you are carrying straight away, and Sneak + C opens the Call Armour picker -- it also lists Iron Man armour in your inventory, and picking it sends those pieces home to your Suit Platform. Iron Man armour makes you immune to fall damage, and flying hard into the ground slams down for 20 damage, knocking everything nearby away.',
  'projecthero.guide.iron_man.suit_up.body': 'Each piece takes 3 seconds to build onto you, boots first, then legs, chest and helmet: the inner layer closes around you in two halves, then the outer plating fills in one pixel at a time. You strike one of four random suit-up poses that change with the piece being built and react as each one locks home. The suit only comes online -- abilities and flight unlocked -- once every piece is fully built. Called armour flies in from its platform first; the Mark VII arrives by pod and the Mark V unfolds from its suitcase.',
  'projecthero.guide.iron_man.targeting.body': 'The Mark 2 and Mark III lock onto the hostile nearest your crosshair (a gold and red reticle marks it) and auto-aim at it: repulsors, the Unibeam, rockets and missiles go straight to it.',
  'projecthero.guide.iron_man.mark_1': 'Mark 1',
  'projecthero.guide.iron_man.mark_1.body': '500 energy (+2/s), 750 integrity that soaks half of every hit, immune to arrows and fire, diamond-grade, +6 melee. No underwater air, no auto-feed. R Strong Punch (15). G Flamethrower (8/s + burning, overheats at 100 heat). Z Rocket (30). X Flight Burst: 20 s of flight at 8 blocks/s that never drops below half a block off the ground -- X again ends it; Sneak + X launches you far ahead first. V Mob Highlight (only you see it). C store suit.',
  'projecthero.guide.iron_man.mark_2': 'Mark 2',
  'projecthero.guide.iron_man.mark_2.body': '1250 energy (+3/s), 1000 integrity soaking half of every hit, immune to arrows and fire, Resistance I with the chestplate, +6 melee, targeting HUD. R Repulsor (10; hold 1 s for an 18 charged shot), Sneak + R Repulsor Dash (15). G Sonic Clap (15 in a 12-block cone). Z Unibeam (6 s, 20 per hit). X Flares (blind + Slowness IV); Sneak + X lights fires like flint and steel, or while flying gives 30 s of supersonic flight. V Mob Highlight. C store suit.',
  'projecthero.guide.iron_man.mark_iii': 'Mark III',
  'projecthero.guide.iron_man.mark_iii.body': '2000 energy (+5/s), 1000 integrity soaking half of every hit, immune to arrows and fire, Resistance I, +7 melee, breathes underwater, auto-feeds, targeting HUD. R Repulsor (15; hold 1 s for 20), Sneak + R Repulsor Dash (20). G fires the weapon picked on the V weapon wheel: Rockets (35, area), Miniguns (hold for 5 s) or Micro-Missiles (4 homing, 25 each). Sneak + G Sonic Clap (20). Z hold the Unibeam as long as you like (80 energy/s). X homing Flares that burn and knock back (supersonic flight if used while flying); Sneak + X JARVIS Scan of the area. Sneak + V Energy Shield blocks everything. C store suit.',
  'projecthero.guide.iron_man.platform': 'Suit Platform',
  'projecthero.guide.iron_man.platform.body': 'Any suit docked on a Suit Platform recharges 10 energy and repairs 10 integrity every second. The platform no longer holds a reserve.',
}}]);
